export const articleManagerMarkup=`<section class="article-manager"><p role="status" data-article-status>正在连接文章服务…</p><div class="article-manager-grid"><form data-article-form><h2 data-form-title>撰写文章</h2><label>标题<input name="title" maxlength="200" required/></label><div class="article-field-row"><label>语言<select name="locale"><option value="zh">中文</option><option value="ja">日本語</option><option value="en">English</option></select></label><label>分类<select name="category"><option value="archival">史料与考据</option><option value="profile">人物专访</option><option value="business">商业与组织</option><option value="art-philosophy">艺术与观点</option><option value="infrastructure">技术与基础设施</option></select></label></div><label>摘要<textarea name="summary" maxlength="1000" rows="3"></textarea></label><div class="article-controls" role="toolbar" aria-label="正文格式"><button type="button" data-insert="heading">标题</button><button type="button" data-insert="bold">粗体</button><button type="button" data-insert="link">链接</button><button type="button" data-insert="image">图片网址</button></div><label>正文 · Markdown<textarea name="body" maxlength="200000" rows="22" required></textarea></label><p class="article-form-hint">支持标题、列表、链接和图片网址。正文直接存入文章数据库。</p><label>关联词条 ID · 选填<input name="relatedEntities" placeholder="kaf, vwp"/></label><div class="article-controls"><button type="button" data-save>保存草稿</button><button type="submit">提交审核</button><button type="button" data-new>新建文章</button></div><details><summary>正文预览</summary><div data-preview class="wiki-prose"></div></details></form><aside><div class="article-queue-heading"><h2 data-queue-title>我的文章提案</h2><button type="button" data-refresh>刷新</button></div><div data-revisions></div><div data-documents></div></aside></div></section>`;
export const articleManagerStyles=`.article-manager{color:inherit;min-width:0}.article-manager-grid{display:grid;grid-template-columns:minmax(0,1.6fr) minmax(260px,1fr);gap:28px}.article-manager form,.article-manager aside{min-width:0}.article-manager label{display:grid;gap:8px;margin:16px 0;font-size:12px}.article-manager :is(input,textarea,select){box-sizing:border-box;width:100%;background:var(--theme-bg,transparent);color:inherit;border:1px solid rgb(140 150 148/.3);border-radius:8px;padding:12px;font:inherit}.article-manager textarea[name=body]{font:13px/1.9 var(--font-mono,monospace);resize:vertical}.article-manager h2{font:400 22px/1.6 var(--font-serif,serif)}.article-manager h3{font:400 17px/1.6 var(--font-serif,serif)}.article-manager button,.article-manager a{font-size:12px}.article-manager button{min-height:40px;padding:10px 14px;border:1px solid rgb(140 150 148/.3);border-radius:10px;background:transparent;color:inherit;cursor:pointer}.article-manager button:hover{background:rgb(140 150 148/.08)}.article-manager button:disabled{opacity:.5;cursor:wait}.article-field-row{display:grid;grid-template-columns:1fr 1fr;gap:16px}.article-controls,.article-queue-heading{display:flex;flex-wrap:wrap;align-items:center;gap:10px}.article-queue-heading{justify-content:space-between}.article-manager article{padding:18px;border:1px solid rgb(140 150 148/.22);border-radius:12px;margin:16px 0;background:rgb(140 150 148/.025)}.article-manager pre{white-space:pre-wrap;overflow-wrap:anywhere;max-height:400px;overflow:auto;font:12px/1.8 monospace}.article-manager details{margin:16px 0}.article-manager summary{cursor:pointer;font-size:12px}.article-form-hint{font-size:11px;opacity:.65}.article-manager [hidden]{display:none!important}.article-manager :focus-visible{outline:2px solid var(--theme-accent-color,#85bfb4);outline-offset:3px}@media(max-width:760px){.article-manager-grid{grid-template-columns:1fr}.article-manager button{min-height:44px}}`;
export function initArticleManager(root,{api='',admin=false,locale='zh',login='/zh/account/'}={}){
 const form=root.querySelector('[data-article-form]'),status=root.querySelector('[data-article-status]');
 let revisionId=null,articleId=null,baseVersion=0,busy=false,queueOffset=0,documentOffset=0;
 const setStatus=text=>status.textContent=text;
 const node=(tag,text)=>{const e=document.createElement(tag);if(text!==undefined)e.textContent=text;return e;};
 const field=name=>form.elements.namedItem(name);
 const request=async(path,method='GET',body)=>{const response=await fetch(api+`/api/${admin?'admin/':''}articles`+path,{method,credentials:'include',headers:body?{'Content-Type':'application/json'}:{},body:body?JSON.stringify(body):undefined});const result=await response.json();if(!response.ok){if(response.status===401){setStatus('请登录后保存或投稿。');const a=node('a','登录');a.href=login;status.append(' ',a);}throw Error(result.error?.message||'请求失败');}return result;};
 const wrap=async(action)=>{if(busy)return;busy=true;root.querySelectorAll('button').forEach(b=>b.disabled=true);try{await action();}catch(e){if(!status.querySelector('a'))setStatus(e.message);}finally{busy=false;root.querySelectorAll('button').forEach(b=>b.disabled=false);}};
 const content=()=>({title:field('title').value,summary:field('summary').value,body:field('body').value,category:field('category').value,relatedEntities:field('relatedEntities').value.split(/[,，]/).map(x=>x.trim()).filter(Boolean)});
 const preview=()=>{const box=root.querySelector('[data-preview]');box.textContent=field('body').value;root.dispatchEvent(new CustomEvent('article-preview',{detail:field('body').value}));};
 const fill=data=>{for(const key of ['title','summary','body','category'])field(key).value=data[key]||'';field('relatedEntities').value=(data.relatedEntities||[]).join(', ');preview();};
 const save=async()=>{const result=await request('/drafts?locale='+field('locale').value,'POST',{revisionId,articleId,baseVersion,content:content()});revisionId=result.revisionId;articleId=result.id;field('locale').disabled=true;setStatus('草稿已保存到数据库。');return result;};
 const pager=(box,offset,next,set)=>{const controls=node('div');controls.className='article-controls';for(const [label,value]of [['上一页',Math.max(0,offset-20)],['下一页',next]]){if(label==='上一页'&&!offset||value===null)continue;const b=node('button',label);b.type='button';b.onclick=()=>wrap(async()=>{set(value);queueOffset=0;await load();});controls.append(b);}box.append(controls);};
 const load=async()=>{
  const result=await request((admin?'/revisions':'/mine')+'?offset='+queueOffset),list=root.querySelector('[data-revisions]');list.replaceChildren();
  if(!result.revisions.length)list.append(node('p',admin?'暂无待审核提案。':'还没有文章提案。'));
  for(const r of result.revisions){const card=node('article'),title=node('h3',r.content.title||'未命名草稿'),meta=node('p',`${r.locale} · ${r.author_name} · ${r.status}`),detail=node('details'),sum=node('summary','查看全文与修改');detail.append(sum,node('p',r.content.summary),node('pre',r.content.body));card.append(title,meta,detail);if(r.review_note)card.append(node('p','审核意见：'+r.review_note));
   const controls=node('div');controls.className='article-controls';
   if(admin){
    const comparison=node('button','读取当前公开版本');comparison.type='button';comparison.onclick=()=>wrap(async()=>{const {article}=await request('/items/'+r.article_id+'?locale='+r.locale);detail.append(node('h3','当前公开版本'),node('pre',article.body));detail.open=true;});controls.append(comparison);
    const note=node('textarea');note.placeholder='审核意见';note.setAttribute('aria-label','审核意见');card.append(note);
    for(const [action,label]of [['approve','批准发布'],['reject','退回修改']]){const b=node('button',label);b.type='button';b.onclick=()=>wrap(async()=>{await request(`/revisions/${r.id}/${action}`,'POST',{note:note.value});setStatus(label+'完成');queueOffset=0;await load();});controls.append(b);}
   }else if(r.status==='draft'||r.status==='rejected'){
    const b=node('button',r.status==='draft'?'继续编辑':'修改后重新投稿');b.type='button';b.onclick=()=>wrap(async()=>{revisionId=r.status==='draft'?r.id:null;articleId=r.article_id;baseVersion=r.base_version;if(r.status==='rejected'){try{const {article}=await request('/items/'+r.article_id+'?locale='+r.locale);baseVersion=article.version;}catch{articleId=null;baseVersion=0;}}field('locale').value=r.locale;field('locale').disabled=true;fill(r.content);setStatus('已载入提案。');form.scrollIntoView({behavior:'smooth',block:'start'});});controls.append(b);
   }card.append(controls);list.append(card);
  }
  pager(list,queueOffset,result.nextOffset,value=>{queueOffset=value;});
  if(admin){const {items,nextOffset}=await request('/documents?offset='+documentOffset),box=root.querySelector('[data-documents]');box.replaceChildren(node('h2','已发布文章'));for(const item of items){const card=node('article');card.append(node('h3',item.title),node('p',`${item.locale} · v${item.version} · ${item.visibility}`));const b=node('button',item.visibility==='public'?'下架文章':'恢复公开');b.type='button';b.onclick=()=>wrap(async()=>{await request(`/items/${item.id}/${item.visibility==='public'?'hide':'restore'}?locale=${item.locale}`,'POST',{});await load();});card.append(b);box.append(card);}pager(box,documentOffset,nextOffset,value=>{documentOffset=value;});}
 };
 if(admin){root.querySelector('[data-queue-title]').textContent='待审核文章';form.hidden=true;root.querySelector('.article-manager-grid').style.gridTemplateColumns='1fr';}
 field('locale').value=['zh','ja','en'].includes(locale)?locale:'zh';
 root.querySelector('[data-save]').onclick=()=>wrap(async()=>{await save();await load();});
 form.onsubmit=e=>{e.preventDefault();wrap(async()=>{await save();await request(`/revisions/${revisionId}/submit`,'POST',{});setStatus('已提交审核，审核通过后公开。');revisionId=null;articleId=null;baseVersion=0;form.reset();field('locale').disabled=false;await load();});};
 root.querySelector('[data-refresh]').onclick=()=>wrap(load);
 root.querySelector('[data-new]').onclick=()=>{form.reset();revisionId=articleId=null;baseVersion=0;field('locale').disabled=false;setStatus('新文章。保存草稿后可以稍后继续。');preview();};
 root.querySelectorAll('[data-insert]').forEach(button=>{button.onclick=()=>{const area=field('body'),start=area.selectionStart,end=area.selectionEnd,selected=area.value.slice(start,end);const text=({heading:'\n## '+(selected||'小标题')+'\n',bold:'**'+(selected||'文字')+'**',link:'['+(selected||'链接文字')+'](https://)',image:'!['+(selected||'图片说明')+'](https://)'} )[button.dataset.insert];area.setRangeText(text,start,end,'select');area.focus();preview();};});
 field('body').addEventListener('input',preview);
 wrap(async()=>{const id=new URL(location.href).searchParams.get('id');if(id){const {article}=await request('/items/'+encodeURIComponent(id)+'?locale='+locale);articleId=article.id;baseVersion=article.version;field('locale').value=article.locale;field('locale').disabled=true;fill(article);}await load();setStatus(admin?'审核文章后才会公开。':'文章保存到数据库，提交后由管理员审核。');});
}
