// Browser-safe UI copy: do not import the server-side Chinese filesystem converter.
const copies={
 zh:{image:'图片',detailTitle:'展开详情',title:'文章',intro:'记录、观点与研究。登录后可投稿或提出修改，由站长审核发布。',submit:'投稿与我的文章',searchLabel:'搜索文章、作者',category:'分类',all:'全部分类',search:'搜索',clear:'清除',loading:'正在读取文章…',more:'继续显示 24 篇',read:'阅读文章 ↗',edit:'提交修改 ↗',toc:'目录',related:'关联词条',unavailable:'文章服务暂不可用',missing:'缺少文章 ID',fallback:'当前显示中文原文',relatedError:'关联词条暂时无法读取。',empty:'暂无已公开文章。',shown:'已显示 {n} 篇文章',categories:{archival:'史料与考据',profile:'人物专访',business:'商业与组织','art-philosophy':'艺术与观点',infrastructure:'技术与基础设施'}},
 ja:{image:'画像',detailTitle:'詳細を表示',title:'記事',intro:'記録・視点・研究。ログインして投稿や修正を提案できます。管理者の審査後に公開されます。',submit:'投稿・自分の記事',searchLabel:'記事・著者を検索',category:'分類',all:'すべての分類',search:'検索',clear:'クリア',loading:'記事を読み込み中…',more:'さらに24件表示',read:'記事を読む ↗',edit:'修正を提案 ↗',toc:'目次',related:'関連項目',unavailable:'記事を読み込めません',missing:'記事IDがありません',fallback:'中国語の原文を表示しています',relatedError:'関連項目を読み込めません。',empty:'公開された記事はまだありません。',shown:'{n}件の記事を表示',categories:{archival:'史料・考証',profile:'人物インタビュー',business:'ビジネス・組織','art-philosophy':'芸術・視点',infrastructure:'技術・インフラ'}},
 en:{image:'Image',detailTitle:'Details',title:'Articles',intro:'Records, perspectives and research. Sign in to submit an article or propose edits for review by the site owner.',submit:'Write / my articles',searchLabel:'Search articles and authors',category:'Category',all:'All categories',search:'Search',clear:'Clear',loading:'Loading articles…',more:'Show 24 more',read:'Read article ↗',edit:'Propose an edit ↗',toc:'Contents',related:'Related entries',unavailable:'Article service unavailable',missing:'Missing article ID',fallback:'Showing the Chinese original',relatedError:'Related entries are unavailable.',empty:'No published articles yet.',shown:'Showing {n} articles',categories:{archival:'Archives and research',profile:'Profiles and interviews',business:'Business and organizations','art-philosophy':'Art and perspectives',infrastructure:'Technology and infrastructure'}}
};
export const articleCopy=locale=>copies[locale]||copies[locale?.startsWith('zh')?'zh':'en'];

const traditional={...copies.zh,title:'文章',intro:'記錄、觀點與研究。登入後可投稿或提出修改，由站長審核發布。',submit:'投稿與我的文章',searchLabel:'搜尋文章、作者',all:'全部分類',search:'搜尋',clear:'清除',loading:'正在讀取文章…',more:'繼續顯示 24 篇',read:'閱讀文章 ↗',edit:'提交修改 ↗',toc:'目錄',related:'關聯詞條',unavailable:'文章服務暫不可用',missing:'缺少文章 ID',fallback:'目前顯示中文原文',relatedError:'關聯詞條暫時無法讀取。',empty:'暫無已公開文章。',shown:'已顯示 {n} 篇文章',image:'圖片',detailTitle:'展開詳情',categories:{archival:'史料與考據',profile:'人物專訪',business:'商業與組織','art-philosophy':'藝術與觀點',infrastructure:'技術與基礎設施'}};
copies['zh-tw']=traditional;copies['zh-hk']=traditional;
