// Browser-safe UI copy: do not import the server-side Chinese filesystem converter.
const copies={
 zh:{image:'图片',detailTitle:'展开详情',title:'文章',intro:'记录、观点与研究。登录后可投稿或提出修改，由站长审核发布。',submit:'投稿与我的文章',searchLabel:'搜索文章、作者',category:'分类',all:'全部分类',search:'搜索',clear:'清除',loading:'正在读取文章…',more:'继续显示 24 篇',read:'阅读文章 ↗',edit:'提交修改 ↗',toc:'目录',related:'关联词条',unavailable:'文章服务暂不可用',missing:'缺少文章 ID',fallback:'当前显示中文原文',relatedError:'关联词条暂时无法读取。',empty:'暂无已公开文章。',shown:'已显示 {n} 篇文章',categories:{archival:'史料与考据',profile:'人物专访',business:'商业与组织','art-philosophy':'艺术与观点',infrastructure:'技术与基础设施'}},
 ja:{image:'画像',detailTitle:'詳細を表示',title:'記事',intro:'記録・視点・研究。ログインして投稿や修正を提案できます。管理者の審査後に公開されます。',submit:'投稿・自分の記事',searchLabel:'記事・著者を検索',category:'分類',all:'すべての分類',search:'検索',clear:'クリア',loading:'記事を読み込み中…',more:'さらに24件表示',read:'記事を読む ↗',edit:'修正を提案 ↗',toc:'目次',related:'関連項目',unavailable:'記事を読み込めません',missing:'記事IDがありません',fallback:'中国語の原文を表示しています',relatedError:'関連項目を読み込めません。',empty:'公開された記事はまだありません。',shown:'{n}件の記事を表示',categories:{archival:'史料・考証',profile:'人物インタビュー',business:'ビジネス・組織','art-philosophy':'芸術・視点',infrastructure:'技術・インフラ'}},
 en:{image:'Image',detailTitle:'Details',title:'Articles',intro:'Records, perspectives and research. Sign in to submit an article or propose edits for review by the site owner.',submit:'Write / my articles',searchLabel:'Search articles and authors',category:'Category',all:'All categories',search:'Search',clear:'Clear',loading:'Loading articles…',more:'Show 24 more',read:'Read article ↗',edit:'Propose an edit ↗',toc:'Contents',related:'Related entries',unavailable:'Article service unavailable',missing:'Missing article ID',fallback:'Showing the Chinese original',relatedError:'Related entries are unavailable.',empty:'No published articles yet.',shown:'Showing {n} articles',categories:{archival:'Archives and research',profile:'Profiles and interviews',business:'Business and organizations','art-philosophy':'Art and perspectives',infrastructure:'Technology and infrastructure'}}
};
export const articleCopy=locale=>copies[locale]||copies[locale?.startsWith('zh')?'zh':'en'];

const traditional={...copies.zh,title:'文章',intro:'記錄、觀點與研究。登入後可投稿或提出修改，由站長審核發布。',submit:'投稿與我的文章',searchLabel:'搜尋文章、作者',all:'全部分類',search:'搜尋',clear:'清除',loading:'正在讀取文章…',more:'繼續顯示 24 篇',read:'閱讀文章 ↗',edit:'提交修改 ↗',toc:'目錄',related:'關聯詞條',unavailable:'文章服務暫不可用',missing:'缺少文章 ID',fallback:'目前顯示中文原文',relatedError:'關聯詞條暫時無法讀取。',empty:'暫無已公開文章。',shown:'已顯示 {n} 篇文章',image:'圖片',detailTitle:'展開詳情',categories:{archival:'史料與考據',profile:'人物專訪',business:'商業與組織','art-philosophy':'藝術與觀點',infrastructure:'技術與基礎設施'}};
copies['zh-tw']=traditional;copies['zh-hk']=traditional;
Object.assign(copies.zh,{origin:'来源',allOrigins:'全部来源',origins:{'site-original':'站点原创','user-submission':'用户投稿'},writeRelated:'撰写相关文章',allRelated:'查看全部相关文章',relatedArticles:'相关文章',removeRelated:'移除词条筛选',pickRelated:'关联词条（选填）',findRelated:'搜索名称、别名或 ID',remove:'移除',retry:'重试',noMatches:'没有匹配的词条',invalidRelated:'关联词条已失效，请移除后重试',limitRelated:'最多关联 50 个词条',login:'登录后保存或投稿',intro:'站点原创与用户投稿。登录后可投稿或修改自己的文章，由维护者审核发布。'});
Object.assign(copies.ja,{origin:'出典',allOrigins:'すべての出典',origins:{'site-original':'サイトオリジナル','user-submission':'ユーザー投稿'},writeRelated:'関連記事を書く',allRelated:'すべての関連記事',relatedArticles:'関連記事',removeRelated:'項目フィルターを解除',pickRelated:'関連項目（任意）',findRelated:'名前・別名・IDで検索',remove:'削除',retry:'再試行',noMatches:'該当する項目はありません',invalidRelated:'無効な関連項目を削除してください',limitRelated:'最大50項目まで',login:'ログインして保存・投稿',intro:'サイトオリジナルとユーザー投稿。自分の記事を編集し、審査後に公開できます。'});
Object.assign(copies.en,{origin:'Source',allOrigins:'All sources',origins:{'site-original':'Site original','user-submission':'User submission'},writeRelated:'Write a related article',allRelated:'All related articles',relatedArticles:'Related articles',removeRelated:'Remove entry filter',pickRelated:'Related entries (optional)',findRelated:'Search names, aliases or IDs',remove:'Remove',retry:'Retry',noMatches:'No matching entries',invalidRelated:'Remove unavailable related entries before submitting',limitRelated:'Up to 50 related entries',login:'Sign in to save or submit',intro:'Site originals and user submissions. Sign in to submit or edit your own articles for review.'});
Object.assign(traditional,{origin:'來源',allOrigins:'全部來源',origins:{'site-original':'站點原創','user-submission':'用戶投稿'},writeRelated:'撰寫相關文章',allRelated:'查看全部相關文章',relatedArticles:'相關文章',removeRelated:'移除詞條篩選',pickRelated:'關聯詞條（選填）',findRelated:'搜尋名稱、別名或 ID',remove:'移除',retry:'重試',noMatches:'沒有符合的詞條',invalidRelated:'關聯詞條已失效，請移除後重試',limitRelated:'最多關聯 50 個詞條',login:'登入後儲存或投稿',intro:'站點原創與用戶投稿。登入後可投稿或修改自己的文章，由維護者審核發布。'});

for(const [locale,values] of Object.entries({zh:{editorHint:'正文会自动保存在本机。登录后可保存云端草稿，并提交审核。',serverSaved:'草稿已保存到云端。'},en:{editorHint:'Your writing is saved on this device. Sign in to save a cloud draft and submit for review.',serverSaved:'Draft saved to your account.'},ja:{editorHint:'本文はこの端末に自動保存されます。ログインするとクラウド保存・審査への提出ができます。',serverSaved:'下書きをクラウドに保存しました。'},'zh-tw':{editorHint:'正文會自動儲存在本機。登入後可儲存雲端草稿，並提交審核。',serverSaved:'草稿已儲存至雲端。'},'zh-hk':{editorHint:'正文會自動儲存在本機。登入後可儲存雲端草稿，並提交審核。',serverSaved:'草稿已儲存至雲端。'}}))Object.assign(copies[locale],values);
