import { resolveLocaleCopy } from './i18n.mjs';
export const editorGuide = locale => resolveLocaleCopy({
 zh: {
  choose:'选择适合你的投稿方式',editor:'站内编辑器版',github:'GitHub 流程版',
  intro:'修改或新建词条、添加图片，均可使用站内编辑器；公告和其他仓库文件请走 GitHub。两种方式都需要维护者审核。',
  title:'在站内完成第一次投稿',subtitle:'使用已有的 GitHub 或 Google 账号登录 Wiki，无需配置令牌或自己创建分支。',
  scope:'支持艺人、歌曲、专辑、企划和日志的新建与修改，可附加 PNG、JPEG、WebP 图片。支持简中、日文、英文，繁中由简中生成；公告仍使用 GitHub。',
  steps:[
   ['登录并找到原文','打开编辑器，点击“编辑旧词条”。输入名称或路径，按类型筛选，确认标题和语言后选择结果。也可以从词条携带原文链接进入。加载完成后再开始编辑；替换现有草稿前先备份。'],
   ['新建词条与图片','点击顶部“新建词条”，选择类型、语言并填写目录；随后在“词条属性”补齐资料。“图片附件”可选择、拖入或粘贴图片，填写来源后加入，再插入正文或设为封面。图片先保存在本机，提交审核时与正文进入同一个 PR。最多 8 张、合计 4 MB，每张原图不超过 750 KB，不会压缩；更大原图通过 GitHub 上传，详见图片与文件教程。'],
   ['直接写，随时看效果','在正文中输入；选中文字可加粗、添加链接、注音或剧透遮罩。空段落输入 / 打开插入菜单，方向键选择、Enter 插入、Esc 关闭。正文 Enter 新建段落，Shift+Enter 换行。用无序/有序列表按钮，或输入 - 空格、1. 空格开始列表；Enter 继续，空项目 Enter 退出，Tab / Shift+Tab 调整层级。'],
   ['核对属性与来源','“属性”中检查名称、日期和条目标识；不要随意更改路径与 translationKey。新增事实附上直接支持它的来源。用“专注写作”扩大正文区域，用“阅读预览”检查链接、表格和复杂内容。'],
   ['保存草稿，查看差异','浏览器草稿自动保存在当前设备。打开“提交审核”面板，可以手动保存、读取账号下的云端草稿，保留 90 天。含图片的草稿只保存在本机；重要修改仍建议下载 Markdown 备份，另行保管原图。提交前检查差异，确认没有意外删掉原文。'],
   ['填写说明并提交审核','填写这次改了什么、为什么改，以及相关资料来源，再提交。网站会代你创建 GitHub PR。提交后内容与说明会公开；草稿保存不等于已投稿，投稿也不等于已上线。'],
   ['跟进意见，继续完善','在“投稿与评论”查看自己的投稿、检查结果和审核讨论。继续修改会更新同一 PR；遇到冲突先核对双方改动。可撤回投稿，评论和记录保留。站内目前只读评论，回复与审核在 GitHub 完成；合并并部署后正式词条才会更新。'],
  ],
  open:'开始站内编辑',submissions:'查看我的投稿',reference:'上传较大原图或自行管理分支？切换 GitHub 流程版，并阅读图片与文件教程。',
  githubTitle:'通过 GitHub 提交修改',githubIntro:'适合直接修改 Markdown、新建词条、上传已获授权的图片或修改其他仓库文件。可视化编辑器在这个流程里也可作为写作与导出工具。',
  githubSteps:[['准备分支','登录 GitHub，打开目标文件并选择编辑。没有写权限时按提示 Fork；有写权限时也将修改提交到新分支。'],['修改与核对','保留顶部 YAML、条目标识和已有来源。可以直接编辑 Markdown，也可在站内编辑器完成修改后导出完整文件，粘贴到 GitHub。新图片必须提交图片文件，不能只填写本地路径。'],['创建并跟进 PR','向原仓库 main 创建 PR，写明改动与来源。等待自动检查和维护者审核；收到意见后提交到同一分支。合并后等待站点部署完成。']],
 },
 en: {
  choose:'Choose a contribution workflow',editor:'In-site editor',github:'GitHub workflow',
  intro:'Use the editor to create or edit articles and attach images. Use GitHub for announcements and other repository files. Both workflows require maintainer review.',
  title:'Your first in-site submission',subtitle:'Sign in to the Wiki with GitHub or Google. No token setup or manual branch creation is needed.',
  scope:'Existing artists, songs, albums, projects and logs in Simplified Chinese, Japanese and English are supported. Traditional Chinese is generated. New articles and PNG, JPEG or WebP attachments are supported; announcements still use GitHub.',
  steps:[
   ['Sign in and load the original','Choose Edit existing article. Search by title or path, filter by type and verify the language. You can also follow an article’s editing link. Wait for loading to finish; back up your current draft before replacing it.'],
   ['Create articles and add images','Use New article to choose a type, language and folder, then complete Article properties. In Images, select, drop or paste images and provide their source. Insert them into the article or use them as a cover. Images stay local until submission and share the same PR: up to 8 images, 4 MB total, 750 KB per original, without compression. Use GitHub for larger originals; see the image and file guide.'],
   ['Write and preview','Select text for bold, links, ruby or spoilers. Type / in an empty block to insert; use arrow keys, Enter and Escape. Enter creates a paragraph; Shift+Enter adds a line break. Use the list buttons or type - space / 1. space. Enter continues a list; Enter on an empty item exits; Tab / Shift+Tab changes nesting.'],
   ['Check properties and sources','Verify names, dates and the entry key in Properties. Keep the path and translationKey intact. Cite sources that directly support new facts. Focus mode gives you more writing space; Preview helps check links, tables and complex content.'],
   ['Save and compare','Browser drafts stay on this device. The submission panel lets you manually save and restore cloud drafts for your account, retained for 90 days. Image drafts stay local; back up important Markdown and keep original images separately. Review the diff for accidental deletions.'],
   ['Submit for review','Describe what changed and why, and provide sources. The site creates a GitHub PR for you. Submitted content and descriptions are public. Saving is not submitting, and submitting is not publishing.'],
   ['Follow up','Open Submissions and comments for status, checks and review discussion. Continue editing to update the same PR; compare both versions when a conflict occurs. Withdrawal closes the PR and keeps its history. Comments are read-only here; reply and review on GitHub. Publication follows merge and deployment.'],
  ],open:'Open editor',submissions:'My submissions',reference:'Uploading larger originals or managing branches yourself? Use the GitHub workflow and image guide.',
  githubTitle:'Submit through GitHub',githubIntro:'For Markdown edits, new articles, authorized images and other repository files. You can also use the visual editor to write and export the file.',
  githubSteps:[['Prepare a branch','Sign in to GitHub and edit the target file. Fork when prompted if you have no write access; otherwise still commit to a new branch.'],['Edit and check','Preserve YAML, entry keys and sources. Edit Markdown directly or paste the complete file exported by the visual editor. Upload actual image files; a local path alone is not an upload.'],['Open and follow up on a PR','Target the original repository’s main branch. Describe changes and sources, wait for checks and review, and push revisions to the same branch. Publication follows merge and deployment.']],
 },
 ja: {
  choose:'投稿方法を選ぶ',editor:'サイト内エディター版',github:'GitHub フロー版',
  intro:'新規記事・修正・画像添付はエディターで行えます。告知やその他のファイルは GitHub へ。どちらも管理者のレビューが必要です。',
  title:'サイト内で初めての投稿',subtitle:'GitHub または Google で Wiki にログイン。トークン設定や手動のブランチ作成は不要です。',
  scope:'既存のアーティスト、楽曲、アルバム、企画、ログの簡体字中国語・日本語・英語に対応。繁体字は生成されます。新規記事とPNG・JPEG・WebP画像添付に対応しています。告知はGitHubから投稿してください。',
  steps:[
   ['ログインして原文を開く','「既存記事を編集」で名前やパスを検索し、種類で絞り込みます。記事名と言語を確認して選択してください。記事の編集リンクからも開けます。読み込みを待ち、下書きの置き換え前にバックアップします。'],
   ['新規記事と画像','「新規記事」で種類・言語・フォルダーを選び、記事のプロパティを入力します。「画像添付」で画像と出典を追加し、本文に挿入するかカバーに設定します。画像は端末に保存し、送信時に本文と同じ PR に追加します。最大8枚、合計4 MB、原本1枚750 KB以下で、圧縮しません。大きい原本は画像・ファイルガイドに従ってGitHubへアップロードします。'],
   ['本文を書いて確認する','文字を選ぶと太字、リンク、ルビ、ネタバレ表記を設定できます。空ブロックの / で挿入、矢印で選択、Enter で決定、Esc で終了。Enter は段落、Shift+Enter は改行。リストボタンや - スペース、1. スペースでリストを開始し、Enter で続行、空項目で Enter で終了、Tab / Shift+Tab で階層を変えます。'],
   ['属性と出典を確認する','属性で名前、日付、記事キーを確認。パスや translationKey はむやみに変更しません。追加した事実を裏付ける出典を付け、集中モードとプレビューで本文、リンク、表を確認します。'],
   ['下書きを保存し差分を見る','ブラウザー下書きは現在の端末に保存されます。投稿パネルではアカウントのクラウド下書きを手動で保存・復元でき、90 日間保持されます。画像付き下書きは端末のみです。原本を別途保管し、重要な内容は Markdown でも保存し、差分で意図しない削除がないか確認します。'],
   ['レビューに提出する','変更点、理由、出典を入力すると、サイトが GitHub PR を作成します。提出した内容と説明は公開されます。下書き保存は投稿ではなく、投稿も即時公開ではありません。'],
   ['意見を確認し修正する','「投稿とコメント」で進捗、チェック、レビューを確認します。続けて編集すると同じ PR を更新します。競合時は双方の変更を確認。取り下げても履歴は残ります。コメントは閲覧のみで、返信とレビューは GitHub で行います。マージとデプロイ後に公開されます。'],
  ],open:'エディターを開く',submissions:'自分の投稿',reference:'大きい原本のアップロードやブランチ管理は GitHub フロー版と画像ガイドへ。',
  githubTitle:'GitHub から変更を提出する',githubIntro:'Markdown、新規記事、使用許可のある画像、その他のファイルに対応。エディターで書いてファイルをエクスポートすることもできます。',
  githubSteps:[['ブランチを準備','GitHub にログインして対象ファイルを編集します。書き込み権限がなければ案内に従って Fork。権限があっても新しいブランチへコミットします。'],['編集と確認','YAML、記事キー、出典を保持します。直接 Markdown を編集するか、エディターから全文をエクスポートして貼り付けます。画像は実際のファイルをアップロードします。'],['PR を作成して確認','元のリポジトリの main に PR を作成し、変更と出典を説明します。チェックとレビューを待ち、修正は同じブランチへ。マージとデプロイ後に公開されます。']],
 },
},locale);
