import { resolveLocaleCopy } from "./i18n.mjs";
// Keys are the source-language UI text; article content is never passed through this map.
const phrases = [
  ["恢复草稿", "Restore draft", "下書きを復元"],
  ["当前编辑内容", "Current edits", "現在の編集内容"],
  ["服务端草稿", "Server draft", "サーバーの下書き"],
  ["恢复这份草稿", "Restore this draft", "この下書きを復元"],
  ["投稿与评论", "Submissions and comments", "投稿とコメント"],
  ["第 {0} 次提交", "Revision {0}", "バージョン {0}"],
  [
    "正在提交（已重试 {0} 次）",
    "Submitting ({0} retries)",
    "送信中（再試行 {0} 回）",
  ],
  ["检查", "Checks", "チェック"],
  ["审核", "Review", "レビュー"],
  ["{0} 条评论", "{0} comments", "コメント {0} 件"],
  [
    "还有 {0} 行差异未展开。",
    "{0} more changed lines are not shown.",
    "差分があと {0} 行あります。",
  ],
  [
    "PR #{0} 已同步，等待审核。",
    "PR #{0} synced; awaiting review.",
    "PR #{0} を同期しました。レビュー待ちです。",
  ],
  [
    "服务端草稿已保存，第 {0} 版。",
    "Server draft saved, revision {0}.",
    "サーバーに下書きのバージョン {0} を保存しました。",
  ],
  [
    "发现服务端第 {0} 版草稿，可以查看或恢复。",
    "Server draft revision {0} is available to restore.",
    "サーバーに下書きのバージョン {0} があります。復元できます。",
  ],
  ["投稿 · 本地联调", "Submissions · Local testing", "投稿・ローカルテスト"],
  ["投稿审核", "Submission review", "投稿レビュー"],
  [
    "编辑、保存和审核均在本地运行。",
    "Editing, saving and review run locally.",
    "編集・保存・レビューはローカルで実行されます。",
  ],
  [
    "修改会提交给维护者审核，通过后发布。",
    "Changes are reviewed by maintainers before publication.",
    "変更は管理者が確認してから公開されます。",
  ],
  [
    "原文或 PR 分支已变化。内容已保留，请核对冲突后再处理。",
    "The source or PR branch changed. Your content is retained; resolve the conflict to continue.",
    "原文または PR ブランチが更新されました。内容は保持されています。競合を確認してください。",
  ],
  [
    "暂时无法连接 GitHub，内容已保存；系统会自动重试，也可以立即重试。",
    "GitHub is temporarily unavailable. Content is saved; automatic or manual retry is available.",
    "GitHub に接続できません。内容は保存済みで、自動または手動で再試行できます。",
  ],
  [
    "请填写 200 字以内的修改说明",
    "Enter a change summary of up to 200 characters.",
    "200文字以内で変更内容を説明してください。",
  ],
  [
    "原文已更新，请重新加载原文并核对修改",
    "The source changed. Reload it and review your changes.",
    "原文が更新されました。読み直して変更を確認してください。",
  ],
  [
    "草稿已在其他页面更新，请重新读取",
    "The draft changed in another tab. Reload the server draft.",
    "別のタブで下書きが更新されました。読み直してください。",
  ],
  [
    "投稿已更新，请刷新",
    "The submission changed. Refresh it.",
    "投稿が更新されました。再読み込みしてください。",
  ],
  [
    "请先核对并解决原文冲突",
    "Review and resolve the source conflict first.",
    "原文の競合を先に解消してください。",
  ],
  [
    "PR 分支又有更新，请重新核对",
    "The PR branch changed again. Review it again.",
    "PR ブランチが再度更新されました。もう一度確認してください。",
  ],

  ["提交与审核", "Submit and review", "投稿とレビュー"],
  [
    "站内编辑器 / 投稿审核",
    "Article editor / Review",
    "記事エディター / レビュー",
  ],
  [
    "站内编辑器 / 投稿 · 本地联调",
    "Article editor / Local testing",
    "記事エディター / ローカルテスト",
  ],
  [
    "本地调试：草稿与投稿保存在本机服务中，审核和发布使用模拟服务。",
    "Local testing: drafts and submissions are saved locally; reviews and publishing are simulated.",
    "ローカルテスト：下書きと投稿はローカル保存され、レビューと公開はシミュレーションです。",
  ],
  [
    "提交后将创建公开的 GitHub PR，由维护者审核后发布。请勿填写密码或私人信息。",
    "Submitting creates a public GitHub PR for maintainer review. Do not include passwords or private information.",
    "投稿すると公開の GitHub PR が作成され、管理者が確認します。パスワードや個人情報を含めないでください。",
  ],
  ["关闭投稿面板", "Close submission panel", "投稿パネルを閉じる"],
  ["未连接", "Not connected", "未接続"],
  [
    "切换本地测试账号",
    "Switch local test account",
    "ローカルアカウントを切り替え",
  ],
  ["登录站内账号", "Sign in to Wiki", "Wiki にログイン"],
  ["投稿面板", "Submission panel", "投稿パネル"],
  ["提交修改", "Submit changes", "変更を投稿"],
  ["审核讨论", "Review discussion", "レビュー"],
  ["我的投稿", "My submissions", "自分の投稿"],
  ["模拟 GitHub", "Simulate GitHub", "GitHub をシミュレート"],
  ["本次修改", "Changes", "今回の変更"],
  ["保存服务端草稿", "Save server draft", "サーバーに下書きを保存"],
  ["读取服务端草稿", "Load server draft", "サーバーの下書きを読み込む"],
  ["修改说明", "Change summary", "変更の説明"],
  ["说明改动的内容与原因", "Describe what changed and why", "変更内容と理由"],
  ["资料来源（可选）", "Source URL (optional)", "出典 URL（任意）"],
  [
    "正式接入后，投稿内容和审核讨论将成为公开的 GitHub PR。",
    "Submissions and reviews on the live service are public on GitHub.",
    "正式サービスでは投稿とレビューが GitHub で公開されます。",
  ],
  ["返回编辑", "Back to editing", "編集に戻る"],
  ["提交审核", "Submit for review", "レビューを依頼"],
  ["核对并解决冲突", "Review and resolve conflicts", "競合の確認と解消"],
  [
    "对照原稿、最新原文和你的修改，在下方填写最终内容。提交时会再次检查版本；不会强推或自动覆盖其他文件。",
    "Compare the original, latest source and your changes, then write the resolved content below. Versions are checked again on submission; other files are not overwritten.",
    "元の原文、最新の原文、自分の変更を比較し、最終内容を入力してください。投稿時にバージョンを再確認し、他のファイルは上書きしません。",
  ],
  ["开始编辑时的原文", "Original at editing start", "編集開始時の原文"],
  ["现在的原文", "Latest source", "最新の原文"],
  ["你的修改", "Your changes", "自分の変更"],
  [
    "PR 分支上的最新内容",
    "Latest content on the PR branch",
    "PR ブランチの最新内容",
  ],
  ["核对后的最终 Markdown", "Resolved Markdown", "確認後の Markdown"],
  ["本次解决说明", "Resolution summary", "解消内容の説明"],
  [
    "我已核对最新原文和分支内容",
    "I have reviewed the latest source and branch content",
    "最新の原文とブランチ内容を確認しました",
  ],
  ["提交核对后的内容", "Submit resolved content", "確認済みの内容を投稿"],
  ["查看更多评论", "More comments", "コメントをさらに表示"],
  ["返回编辑器继续修改", "Return to editor", "エディターに戻る"],
  ["更多投稿", "More submissions", "投稿をさらに表示"],
  [
    "清除模拟投稿记录",
    "Clear simulated submissions",
    "シミュレーション投稿を消去",
  ],
  [
    "投稿保存在本地后端数据库，刷新或重启服务后仍然保留。",
    "Submission records remain available after refresh or service restart.",
    "投稿記録は再読み込みやサービスの再起動後も保持されます。",
  ],
  [
    "扮演审核者操作。正式接入后，这些事件来自你在 GitHub 上的操作。",
    "Local reviewer controls. On the live service, these events come from GitHub.",
    "ローカルのレビュー操作です。正式サービスでは GitHub の操作が反映されます。",
  ],
  ["审核评论", "Review comment", "レビューコメント"],
  [
    "请补充这一段的来源。",
    "Please add a source for this paragraph.",
    "この段落の出典を追加してください。",
  ],
  ["评论类型", "Comment type", "コメントの種類"],
  ["PR 普通评论", "PR comment", "PR コメント"],
  ["行内评论", "Inline comment", "行コメント"],
  [
    "关联已提交版本的行号",
    "Line in the submitted version",
    "投稿バージョンの行番号",
  ],
  ["发表评论", "Post comment", "コメントを追加"],
  ["要求修改", "Request changes", "変更を依頼"],
  ["检查通过", "Checks pass", "チェック成功"],
  ["检查失败", "Checks fail", "チェック失敗"],
  ["批准", "Approve", "承認"],
  ["合并 PR", "Merge PR", "PR をマージ"],
  ["部署成功", "Publishing succeeds", "公開成功"],
  ["部署失败", "Publishing failed", "公開失敗"],
  ["关闭 PR", "Close PR", "PR を閉じる"],
  ["撤回投稿", "Withdraw submission", "投稿を取り下げ"],
  ["核对原文冲突", "Resolve source conflict", "原文の競合を確認"],
  ["立即重试", "Retry now", "今すぐ再試行"],
  ["请选择投稿", "Select a submission", "投稿を選択"],
  ["待创建", "Pending", "作成待ち"],
  ["原文或分支冲突", "Source or branch conflict", "原文またはブランチの競合"],
  ["尚未提交", "Not submitted", "未投稿"],
  ["没有新的修改。", "No new changes.", "新しい変更はありません。"],
  ["更新此 PR", "Update this PR", "この PR を更新"],
  ["等待", "Pending", "待機中"],
  ["通过", "Passed", "成功"],
  ["失败", "Failed", "失敗"],
  ["已批准", "Approved", "承認済み"],
  ["等待批准", "Awaiting approval", "承認待ち"],
  [
    "提交后在这里查看审核结果。",
    "Review results appear here after submission.",
    "投稿後にレビュー結果が表示されます。",
  ],
  ["审核者", "Reviewer", "レビュアー"],
  [" · 较早版本", " · Earlier version", " · 以前のバージョン"],
  [
    "暂无审核评论。",
    "No review comments yet.",
    "レビューコメントはまだありません。",
  ],
  ["查看投稿", "View submission", "投稿を表示"],
  ["继续修改", "Continue editing", "編集を続ける"],
  [
    "当前账号还没有投稿。",
    "No submissions for this account.",
    "このアカウントの投稿はありません。",
  ],
  [
    "正在连接投稿服务…",
    "Connecting to submission service…",
    "投稿サービスに接続中…",
  ],
  [
    "已加载当前账号的投稿记录。",
    "Submissions loaded for the current account.",
    "現在のアカウントの投稿を読み込みました。",
  ],
  [
    "已连接本地服务，本次操作不会写入线上仓库。",
    "Connected locally. These actions do not write to the live repository.",
    "ローカルに接続しました。オンラインのリポジトリには書き込みません。",
  ],
  [
    "已连接投稿服务。提交前请核对差异。",
    "Connected. Review the differences before submitting.",
    "接続しました。投稿前に差分を確認してください。",
  ],
  [
    "投稿已保存，后台正在创建或更新 PR。",
    "Submission saved. The PR is being created or updated.",
    "投稿を保存しました。PR を作成または更新しています。",
  ],
  ["已请求撤回。", "Withdrawal requested.", "取り下げを依頼しました。"],
  [
    "已请求重试，投稿内容保持不变。",
    "Retry requested. Submission content is unchanged.",
    "再試行を依頼しました。投稿内容は変更されません。",
  ],
  ["没有服务端草稿", "No server draft", "サーバーに下書きがありません"],
  ["尚未创建远程分支", "No remote branch yet", "リモートブランチは未作成です"],
  [
    "无法连接投稿服务。编辑内容仍保留在本机；恢复连接后可以重试。",
    "Cannot connect. Your edits remain on this device; retry when connected.",
    "接続できません。編集内容は端末に保持されています。接続後に再試行してください。",
  ],
  [
    "投稿服务暂时不可用。编辑内容仍保留在本机，请恢复连接后重试。",
    "The service is unavailable. Your edits are retained locally; retry after reconnecting.",
    "サービスを利用できません。編集内容は端末に保持されています。接続後に再試行してください。",
  ],
  [
    "请先登录站内账号，再提交或查看投稿。",
    "Sign in to submit or view your submissions.",
    "投稿や投稿履歴の表示にはログインしてください。",
  ],
  ["请求失败", "Request failed", "リクエストに失敗しました"],
  [
    "登录账号已变化，请关闭面板后重新核对内容。",
    "The account changed. Close this panel and review your content again.",
    "アカウントが変わりました。パネルを閉じて内容を再確認してください。",
  ],
  [
    "已重新连接投稿服务，投稿记录已恢复。当前编辑内容保持不变。",
    "Reconnected and restored submission records. Your current edits are unchanged.",
    "再接続して投稿記録を復元しました。現在の編集内容は変わりません。",
  ],
  [
    "原文已更新。请保留草稿并重新加载原文核对，不能直接覆盖新版本。",
    "The source changed. Keep your draft and review the latest version before resubmitting.",
    "原文が更新されました。下書きを保持して最新の原文を確認してください。",
  ],
  [
    "无法核对旧草稿原文",
    "Unable to verify the old draft source",
    "以前の下書きの原文を確認できません",
  ],
  [
    "原文已变化，请点“核对原文冲突”继续处理。",
    "The source changed. Use “Resolve source conflict” to continue.",
    "原文が更新されました。「原文の競合を確認」から続けてください。",
  ],
  [
    "词条已变化，请重新打开面板。",
    "The article changed. Reopen the panel.",
    "記事が変わりました。パネルを開き直してください。",
  ],
  [
    "撤回这份投稿并关闭对应 PR？正文会保留在投稿记录中。",
    "Withdraw this submission and close its PR? Its content will remain in your records.",
    "この投稿を取り下げて PR を閉じますか？内容は投稿記録に保持されます。",
  ],
  [
    "已切换本地账号。当前编辑内容仍保留，请核对后再提交。",
    "Local account switched. Your edits remain; review them before submitting.",
    "ローカルアカウントを切り替えました。編集内容を確認してから投稿してください。",
  ],
  [
    "本地 GitHub 事件已通过签名 Webhook 同步。",
    "Local GitHub event synced through the signed webhook.",
    "ローカル GitHub イベントを署名付き Webhook で同期しました。",
  ],
  [
    "没有保存旧版原文，请核对最新原文与修改内容。",
    "The old source is unavailable. Compare the latest source with your changes.",
    "以前の原文は保存されていません。最新の原文と変更を比較してください。",
  ],
  [
    "请先核对最新原文和分支内容并勾选确认。",
    "Review the latest source and branch content, then check the confirmation box.",
    "最新の原文とブランチ内容を確認してチェックしてください。",
  ],
  [
    "核对后的内容已保存，等待更新 PR。请从“我的投稿”继续编辑这一版。",
    "Resolved content saved. Continue editing this version from My submissions.",
    "確認済みの内容を保存しました。「自分の投稿」からこのバージョンを編集できます。",
  ],
  [
    "账号已变化，请重新加载草稿。",
    "The account changed. Reload the draft.",
    "アカウントが変わりました。下書きを読み直してください。",
  ],
  ["待审核", "Awaiting review", "レビュー待ち"],
  ["需要修改", "Changes requested", "変更が必要"],
  ["已合并 · 发布中", "Merged · Publishing", "マージ済み・公開待ち"],
  ["已发布", "Published", "公開済み"],
  ["已关闭", "Closed", "終了"],
  ["查看服务端草稿", "View server draft", "サーバーの下書きを表示"],
  [
    "服务器草稿保留 90 天；本机草稿可随时导出。",
    "Server drafts are retained for 90 days. Local drafts can be exported anytime.",
    "サーバーの下書きは90日間保存されます。端末の下書きはいつでも書き出せます。",
  ],
];
export function submissionCopy(locale) {
  return Object.fromEntries(
    phrases.map(([zh, en, ja]) => [
      zh,
      resolveLocaleCopy({ zh, en, ja }, locale),
    ]),
  );
}
