import {resolveLocaleCopy} from './i18n.mjs';
const labels={
 'creative-network':['创作者协作网络','Creator network','クリエイターネットワーク'],event:['交流活动','Event','イベント'],
 'virtual-singer':['虚拟歌手','Virtual singer','バーチャルシンガー'],'singer-songwriter':['创作歌手','Singer-songwriter','シンガーソングライター'],'vocalist':['歌手','Vocalist','ボーカリスト'],'virtual-group':['虚拟组合','Virtual group','バーチャルグループ'],'visual-director':['视觉监督','Visual director','ビジュアルディレクター'],'scenario-writer':['编剧','Scenario writer','シナリオライター'],'mixer':['混音','Mixing','ミックス'],
 live:['现场演出','Live performance','ライブ'],release:['作品发行','Release','作品発売'],announcement:['公告','Announcement','告知'],'organization-change':['组织变动','Organization change','組織変更'],anime:['动画','Anime','アニメ'],game:['游戏','Game','ゲーム'],publication:['出版','Publication','出版'],exhibition:['展览','Exhibition','展示'],album:['专辑','Album','アルバム'],single:['单曲','Single','シングル'],ep:['迷你专辑','EP','EP'],soundtrack:['原声带','Soundtrack','サウンドトラック'],'live-album':['现场专辑','Live album','ライブアルバム'],
 'character-sheet':['角色设定','Character sheet','キャラクター設定'],'front-view':['正面','Front view','正面'],'back-view':['背面','Back view','背面'],'side-view':['侧面','Side view','側面'],'full-body':['全身','Full body','全身'],'close-up':['局部特写','Close-up','クローズアップ'],costume:['衣装','Costume','衣装'],'expression-sheet':['表情设定','Expressions','表情設定'],'3d-model-mesh':['三维模型','3D model','3Dモデル'],'concept-art':['概念设计','Concept art','コンセプトアート'],'prop-accessory':['道具与配饰','Props & accessories','小道具・装飾'],'official-final':['官方定稿','Official final','公式完成稿'],'design-draft':['设计草稿','Design draft','デザイン草案'],
 'kaf-default-v1':['花譜 · 初期形态','KAF · Original form','花譜・初期形態'],'kaf-combat-v2':['花譜 · 战斗形态','KAF · Combat form','花譜・戦闘形態'],'kaf-vwp-form':['花譜 · V.W.P','KAF · V.W.P','花譜・V.W.P'],'kaf-kaika':['廻花','KAIKA','廻花'],'rim-default-v1':['理芽 · 初期形态','RIM · Original form','理芽・初期形態'],'rim-vwp-form':['理芽 · V.W.P','RIM · V.W.P','理芽・V.W.P'],'kafu-default':['可不 · 标准形态','KAFU · Standard form','可不・標準形態'],'morisaki-kaho-default':['森先化步 · 标准形态','KAFU MORISAKI · Standard form','森先化歩・標準形態'],'sinka-special':['SINKA · 特别形态','SINKA · Special form','SINKA・特別形態'],

 'business':['行业与商业','Industry & business','業界・ビジネス'],'art-philosophy':['艺术与观点','Arts & perspectives','芸術・視点'],'profile':['人物故事','Profiles','人物紹介'],'infrastructure':['技术与建设','Technology & infrastructure','技術・基盤'],'archival':['资料与考据','Archives & research','資料・考察'],
 'person':['创作者','Person','人物'],'virtual-avatar':['虚拟艺人','Virtual artist','バーチャルアーティスト'],'unit':['组合','Group','グループ'],'software-voice':['音乐同位体','Voice software','音楽的同位体'],'work-track':['歌曲','Song','楽曲'],'work-release':['音乐发行','Release','音楽作品'],'project':['企划','Project','企画'],'organization':['组织与厂牌','Organization','組織・レーベル'],'live-event':['演出','Live event','公演'],'lore-concept':['世界观概念','Lore','世界観'],'editorial-article':['文章','Editorial','記事'],
 'member-of':['所属组合','Member of','所属グループ'],'has-member':['成员','Member','メンバー'],'persona-related':['关联形态','Related persona','関連する姿'],'based-on-voice':['声音来源','Voice source','声の提供'],'voice-source-of':['衍生音源','Derived voice','派生音源'],'fictional-counterpart':['世界观对应角色','Fictional counterpart','世界観の対応人物'],'character-designed-by':['角色设计','Character design','キャラクターデザイン'],'designed-character':['设计角色','Designed character','デザインした人物'],'affiliated-with':['所属机构','Affiliation','所属'],'has-affiliated-entity':['关联成员','Affiliated member','所属メンバー'],'related-project':['关联企划','Related project','関連企画'],'has-related-entity':['关联资料','Related record','関連資料'],'related-release':['关联发行','Related release','関連作品'],'related-to-event':['关联活动','Related event','関連イベント'],'derived-from':['衍生自','Derived from','派生元'],'derivative-work':['衍生作品','Derivative work','派生作品'],'soundtrack-for':['原声配乐','Soundtrack for','サウンドトラック'],'has-soundtrack':['原声音乐','Soundtrack','サウンドトラック'],'theme-song-for':['主题曲所属','Theme song for','主題歌の作品'],'has-theme-song':['主题曲','Theme song','主題歌'],
 'performed-by':['演唱','Performed by','歌唱'],'credited-to':['制作','Created by','制作'],'includes-track':['收录曲目','Included track','収録曲'],'performed-track':['现场曲目','Setlist track','披露曲'],'headlined-by':['主要出演','Headliner','主な出演者'],'guest-performer':['嘉宾','Guest performer','ゲスト'],'discusses':['相关研究','Discussed entity','関連研究'],'primaryArtist':['主要艺人','Primary artist','主要アーティスト'],'label':['发行厂牌','Label','レーベル'],'parentOrg':['上级机构','Parent organization','上位組織'],'organizer':['主办方','Organizer','主催'],'belongToUniverse':['所属世界观','Universe','所属世界観'],
 'active':['活动中','Active','活動中'],'hiatus':['暂停活动','On hiatus','活動休止'],'ended':['活动结束','Activity ended','活動終了'],'unknown':['未确认','Unconfirmed','未確認'],'historical':['历史关联','Historical','過去の関係'],
 'lead-vocal':['主唱','Lead vocal','主唱'],'guest-vocal':['客座演唱','Guest vocal','ゲスト歌唱'],'composer':['作曲','Composer','作曲'],'lyricist':['作词','Lyricist','作詞'],'arranger':['编曲','Arranger','編曲'],'illustrator':['插画','Illustrator','イラスト'],'producer':['制作人','Producer','プロデューサー'],'literature-rock':['文学摇滚','Literature rock','文学ロック'],
};
export function entityLabel(key,locale='zh'){const row=labels[key];return row?resolveLocaleCopy({zh:row[0],en:row[1],ja:row[2]},locale):key;}
