export const galleryManagerStyles=`
.gallery-manager{--gallery-line:rgb(145 155 153 / .22);max-width:1200px;margin:auto;color:inherit}.gallery-manager header{border-bottom:1px solid var(--gallery-line);padding-bottom:24px;margin-bottom:28px}.gallery-manager h1{font:400 30px/1.5 var(--font-serif,serif);letter-spacing:.06em}.gallery-manager p{font-size:13px;line-height:1.9;opacity:.7}.gallery-workbench{display:grid;grid-template-columns:minmax(280px,1fr) minmax(300px,1.2fr);gap:40px}.gallery-manager label{display:grid;gap:9px;font-size:12px;margin:18px 0}.gallery-manager input,.gallery-manager textarea,.gallery-manager select{width:100%;box-sizing:border-box;color:inherit;background:transparent;border:1px solid var(--gallery-line);border-radius:4px;padding:12px;font:inherit}.gallery-manager select option{color:#111;background:#fff}.gallery-manager textarea{min-height:100px}.gallery-manager button,.gallery-manager .gallery-login{display:inline-block;padding:10px 16px;border:1px solid var(--gallery-line);background:transparent;color:inherit;border-radius:4px;cursor:pointer;font:12px/1.6 inherit}.gallery-manager button:hover{background:rgb(145 155 153 / .08)}.gallery-manager button:disabled{opacity:.4;cursor:wait}.gallery-manager details{border-block:1px solid var(--gallery-line);padding:14px 0;margin:20px 0}.gallery-manager summary{cursor:pointer;font-size:13px}.gallery-manager .gallery-upload-preview{width:100%;height:220px;object-fit:contain;background:rgb(145 155 153 / .04)}.gallery-manager [data-gallery-status]{min-height:24px;opacity:1}.gallery-submissions article{padding:20px 0;border-bottom:1px solid var(--gallery-line)}.gallery-submissions img{width:100%;height:180px;object-fit:contain;margin-bottom:14px}.gallery-submissions h3{font:400 18px/1.6 var(--font-serif,serif);margin:0}.gallery-manager .gallery-actions{display:flex;gap:10px;flex-wrap:wrap}.gallery-manager pre{white-space:pre-wrap;overflow-wrap:anywhere;font:12px/1.8 inherit}.gallery-manager :focus-visible{outline:2px solid #85bfb4;outline-offset:3px}@media(max-width:760px){.gallery-workbench{grid-template-columns:1fr;gap:24px}}`;
export const galleryManagerMarkup=`<section class="gallery-manager"><header><p>LABs / VISUAL ARCHIVE</p><h1 data-manager-title>上传与完善设定资料</h1><p>选择角色并上传图片，其他资料可稍后补充。每次修改经审核后公开。</p><a class="gallery-login" data-gallery-login hidden>登录后参与</a></header><p data-gallery-status role="status" aria-live="polite">正在载入角色…</p><div class="gallery-workbench"><form data-gallery-form><h2 data-edit-title>新建图片</h2><label>角色 · 必填<input data-character-search type="search" placeholder="搜索角色名称或 ID" aria-label="搜索角色"/><select name="character" required aria-label="角色"><option value="">请选择角色</option></select></label><label>图片<input name="image" type="file" accept="image/png,image/jpeg,image/webp,image/gif"/><span>PNG、JPEG、WebP、GIF，单张不超过 20 MB。</span></label><img class="gallery-upload-preview" data-upload-preview alt="待提交图片预览" hidden/><details><summary>补充资料 · 选填</summary><label>标题<input name="title" maxlength="200"/></label><label>形态<input name="form" maxlength="100"/></label><label>资料日期<input name="date" placeholder="YYYY-MM-DD" maxlength="10"/></label><label>标签<input name="tags" placeholder="用逗号分隔"/></label><label>来源链接<input name="sourceUrl" type="url"/></label><label>来源名称<input name="sourceTitle" maxlength="300"/></label><label>发布机构<input name="publisher" maxlength="200"/></label><label>资料备注<textarea name="notes" maxlength="5000"></textarea></label></details><div class="gallery-actions"><button type="submit">提交审核</button><button type="button" data-gallery-new>新建图片</button></div></form><section><h2 data-queue-title>我的提交</h2><button type="button" data-gallery-refresh>刷新记录</button><button type="button" data-gallery-documents hidden>已收录图片</button><div class="gallery-submissions" data-gallery-revisions></div><div class="gallery-actions"><button type="button" data-queue-prev hidden>上一页</button><button type="button" data-queue-next hidden>下一页</button></div></section></div></section>`;
export function initGalleryManager(root,config){
 if(!root)return;
 const form=root.querySelector('[data-gallery-form]'),status=root.querySelector('[data-gallery-status]'),queue=root.querySelector('[data-gallery-revisions]'),preview=root.querySelector('[data-upload-preview]');
 const api=config.api.replace(/\/$/,''),admin=!!config.admin,base=api+`/api/${admin?'admin/':''}gallery`;
 let characters=[],current=null,objectUrl='',busy=false,offset=0,next=null,documents=false;
 const field=name=>form.elements.namedItem(name);
 const say=message=>status.textContent=message;
 const login=()=>{const a=root.querySelector('[data-gallery-login]');a.hidden=false;a.href=config.login||'/api/auth/oauth/github/start?returnTo='+encodeURIComponent(location.href);};
 async function request(path,options={}){const response=await fetch(path,{credentials:'include',signal:AbortSignal.timeout(options.method==='POST'?120000:15000),...options});let data;try{data=await response.json();}catch{throw Error('服务返回异常，请稍后重试');}if(response.status===401)login();if(!response.ok){const error=Error(data.error?.message||'请求失败');error.status=response.status;throw error;}return data;}
 const text=(tag,value,parent)=>{const el=document.createElement(tag);el.textContent=value;parent.append(el);return el;};
 function populate(search=''){const selected=field('character').value;field('character').replaceChildren(new Option('请选择角色',''));characters.filter(c=>c.id===selected||`${c.id} ${c.name}`.toLowerCase().includes(search.toLowerCase())).forEach(c=>field('character').add(new Option(c.name,c.id)));field('character').value=selected;}
 function reset(){current=null;form.reset();root.querySelector('[data-edit-title]').textContent='新建图片';preview.hidden=true;field('image').required=true;if(objectUrl)URL.revokeObjectURL(objectUrl);populate();}
 function fill(item){current=item;for(const name of ['character','title','form','date','notes','sourceUrl','sourceTitle','publisher'])field(name).value=item[name]||'';field('tags').value=(item.tags||[]).join(', ');field('image').value='';field('image').required=false;preview.src=item.src||item.previewUrl||'';preview.hidden=!(item.src||item.previewUrl);root.querySelector('[data-edit-title]').textContent='完善图片资料';form.scrollIntoView({behavior:'smooth',block:'start'});}
 async function refresh(){const data=await request(base+(documents?'/documents':'/revisions')+'?offset='+offset);next=data.nextOffset;root.querySelector('[data-queue-prev]').hidden=offset===0;root.querySelector('[data-queue-next]').hidden=next===null;queue.replaceChildren();if(documents){if(!data.items.length)text('p','暂无已收录图片。',queue);for(const item of data.items){const card=document.createElement('article');queue.append(card);const image=document.createElement('img');image.src=item.src;image.alt=item.title||item.character;image.loading='lazy';card.append(image);text('h3',image.alt,card);text('p',item.visibility==='public'?'已公开':'已隐藏',card);const edit=text('button','完善资料',card);edit.onclick=()=>{if(!busy)fill(item);};const button=text('button',item.visibility==='public'?'隐藏图片':'恢复公开',card);button.onclick=async()=>{button.disabled=true;try{await request(base+'/items/'+item.id+(item.visibility==='public'?'/hide':'/restore'),{method:'POST'});await refresh();say('公开状态已更新，审核记录已保留。');}catch(error){say(error.message);}finally{button.disabled=false;}};}return;}if(!data.revisions.length)text('p',admin?'暂无待审核提案。':'还没有提交记录。',queue);
 for(const revision of data.revisions){const article=document.createElement('article');queue.append(article);if(revision.previewUrl){const img=document.createElement('img');img.src=revision.previewUrl;img.alt='提案图片';article.append(img);}text('h3',revision.metadata.title||characters.find(c=>c.id===revision.metadata.character)?.name||revision.metadata.character,article);text('p',`${revision.author_name} · ${revision.created_at} · ${{pending:'待审核',approved:'已公开',rejected:'已退回'}[revision.status]||revision.status}`,article);text('pre',[revision.metadata.form,revision.metadata.date,revision.metadata.tags.join(' / '),revision.metadata.sourceTitle,revision.metadata.sourceUrl,revision.metadata.notes,revision.review_note].filter(Boolean).join('\n'),article);
 const actions=document.createElement('div');actions.className='gallery-actions';article.append(actions);
 if(admin){const note=document.createElement('textarea');note.placeholder='审核备注（选填）';note.setAttribute('aria-label','审核备注');article.append(note);for(const [action,label]of [['approve','通过并公开'],['reject','退回修改']]){const button=text('button',label,actions);button.type='button';button.onclick=async()=>{button.disabled=true;try{await request(`${base}/revisions/${revision.id}/${action}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({note:note.value})});say('已处理');await refresh();}catch(error){say(error.message);}finally{button.disabled=false;}};}}
 else if(revision.status==='rejected'){const button=text('button','修改后重新提交',actions);button.type='button';button.onclick=async()=>{try{let item;try{item=(await request(base+'/items/'+revision.item_id)).item;}catch(error){if(revision.base_version!==0||error.status!==404)throw error;}reset();fill({...revision.metadata,...(item?{id:item.id,version:item.version,src:item.src}:{previewUrl:revision.previewUrl})});if(!item){current=null;field('image').required=true;say('请重新选择原图，再提交审核。');}}catch(error){say(error.message);}};}
 else if(revision.status==='approved'){const button=text('button','继续完善',actions);button.type='button';button.onclick=async()=>{try{fill((await request(base+'/items/'+revision.item_id)).item);}catch(e){say(e.message);}};}
 }}
 field('image').addEventListener('change',()=>{const file=field('image').files[0];if(objectUrl)URL.revokeObjectURL(objectUrl);preview.hidden=!file;if(file){objectUrl=URL.createObjectURL(file);preview.src=objectUrl;}});
 root.querySelector('[data-character-search]').addEventListener('input',event=>populate(event.target.value));
 root.querySelector('[data-gallery-new]').onclick=()=>{if(!busy)reset();};
 root.querySelector('[data-queue-prev]').onclick=()=>{offset=Math.max(0,offset-20);refresh().catch(e=>say(e.message));};
 root.querySelector('[data-queue-next]').onclick=()=>{if(next!==null){offset=next;refresh().catch(e=>say(e.message));}};
 root.querySelector('[data-gallery-documents]').onclick=()=>{documents=!documents;offset=0;root.querySelector('[data-gallery-documents]').textContent=documents?'待审核提案':'已收录图片';root.querySelector('[data-queue-title]').textContent=documents?'已收录图片':'待审核提案';refresh().catch(e=>say(e.message));};
 root.querySelector('[data-gallery-refresh]').onclick=()=>refresh().catch(e=>say(e.message));
 form.onsubmit=async event=>{event.preventDefault();if(busy||!form.reportValidity())return;busy=true;const submit=form.querySelector('[type=submit]');submit.disabled=true;root.querySelector('[data-gallery-new]').disabled=true;say('正在上传，请勿关闭页面…');try{const metadata=Object.fromEntries(['character','title','form','date','notes','sourceUrl','sourceTitle','publisher'].map(name=>[name,field(name).value]));metadata.tags=field('tags').value.split(/[,，]/).map(t=>t.trim()).filter(Boolean);if(current)metadata.version=current.version;const body=new FormData();body.set('metadata',JSON.stringify(metadata));const file=field('image').files[0];if(file)body.set('image',file);await request(base+'/items'+(current?'/'+current.id:''),{method:'POST',body});reset();say('已提交审核，通过后会自动出现在图库。');await refresh();}catch(error){say(error.message);}finally{busy=false;submit.disabled=false;root.querySelector('[data-gallery-new]').disabled=false;}};
 if(admin){root.querySelector('[data-gallery-documents]').hidden=false;root.querySelector('[data-manager-title]').textContent='图库管理';root.querySelector('[data-queue-title]').textContent='待审核提案';}
 (async()=>{try{characters=(await request(api+'/api/gallery/characters')).characters;populate();reset();const edit=new URL(location.href).searchParams.get('edit');if(edit)fill((await request(base+'/items/'+encodeURIComponent(edit))).item);say('角色必填，其余资料可以稍后完善。');await refresh();}catch(error){say(error.message);}})();
}
