import {lockModalScroll} from './modalScroll.mjs';
import '../styles/imageViewer.css';
let singleton;
export function imageViewer(){if(singleton)return singleton;
 const make=(tag,text)=>{const node=document.createElement(tag);if(text)node.textContent=text;return node;};
 const zh=document.documentElement.lang.startsWith('zh'),ja=document.documentElement.lang.startsWith('ja');const label=(cn,en,jp)=>zh?cn:ja?jp:en;
 const dialog=make('dialog');dialog.className='image-viewer';dialog.setAttribute('aria-label',label('图片查看器','Image viewer','画像ビューアー'));
 const header=make('header'),title=make('h2'),close=make('button','×');close.type='button';close.setAttribute('aria-label',label('关闭','Close','閉じる'));header.append(title,close);
 const stage=make('div');stage.className='image-viewer__stage';const img=new Image();img.draggable=false;const feedback=make('p');feedback.setAttribute('role','status');const retry=make('button',label('重新载入图片','Retry image','再読み込み'));retry.type='button';retry.hidden=true;stage.append(img,feedback,retry);
 const info=make('aside');info.className='image-viewer__info';const caption=make('p'),details=make('p'),links=make('div');info.append(caption,details,links);
 const footer=make('footer'),prev=make('button','←'),next=make('button','→'),fit=make('button',label('适应窗口','Fit','全体表示')),native=make('button','100%'),minus=make('button','−'),plus=make('button','＋'),scaleLabel=make('output');for(const b of [prev,next,fit,native,minus,plus])b.type='button';prev.setAttribute('aria-label',label('上一张','Previous','前へ'));next.setAttribute('aria-label',label('下一张','Next','次へ'));minus.setAttribute('aria-label',label('缩小','Zoom out','縮小'));plus.setAttribute('aria-label',label('放大','Zoom in','拡大'));footer.append(prev,fit,native,minus,scaleLabel,plus,next);dialog.append(header,stage,info,footer);document.body.append(dialog);
 let items=[],index=0,trigger,release,scale=1,fitScale=1,x=0,y=0,points=new Map(),drag=null,pinch=null,ready=false,onChange,onClose,preloaded=[];
 const render=()=>{img.style.transform=`translate(${x}px,${y}px) scale(${scale})`;scaleLabel.textContent=Math.round(scale*100)+'%';stage.dataset.zoomed=String(scale>fitScale+.01);};
 const clamp=()=>{const r=stage.getBoundingClientRect();x=Math.max(-Math.max(0,(img.naturalWidth*scale-r.width)/2+24),Math.min(x,Math.max(0,(img.naturalWidth*scale-r.width)/2+24)));y=Math.max(-Math.max(0,(img.naturalHeight*scale-r.height)/2+24),Math.min(y,Math.max(0,(img.naturalHeight*scale-r.height)/2+24)));};
 function zoom(value){scale=Math.max(Math.min(fitScale,1),Math.min(8,value));clamp();render();}
 function fitImage(){const r=stage.getBoundingClientRect();fitScale=Math.min(1,(r.width-32)/img.naturalWidth,(r.height-32)/img.naturalHeight);scale=fitScale;x=y=0;render();}
 function load(){ready=false;points.clear();pinch=drag=null;img.style.visibility='hidden';retry.hidden=true;feedback.hidden=false;feedback.textContent=label('正在载入…','Loading…','読み込み中…');const item=items[index];title.textContent=item.title||label('图片','Image','画像');caption.textContent=item.notes||'';details.textContent=`${index+1} / ${items.length}`;links.replaceChildren();for(const link of item.links||[]){let url;try{url=new URL(link.href,location.href);}catch{continue;}if(!['http:','https:'].includes(url.protocol))continue;const a=make('a',link.label);a.href=url.href;if(url.origin!==location.origin){a.target='_blank';a.rel='noopener noreferrer';}links.append(a);}img.alt=item.title||'';img.src=item.src;prev.disabled=index===0;next.disabled=index===items.length-1;onChange?.(item,index);preloaded=[items[index-1],items[index+1]].filter(Boolean).map(item=>{const p=new Image();p.src=item.src;return p;});}
 img.onload=()=>{ready=true;img.style.visibility='visible';feedback.hidden=true;details.textContent=`${index+1} / ${items.length} · ${img.naturalWidth} × ${img.naturalHeight} px`;fitImage();};img.onerror=()=>{feedback.textContent=label('图片载入失败','Image failed to load','読み込めませんでした');retry.hidden=false;};retry.onclick=load;
 const move=delta=>{if(index+delta<0||index+delta>=items.length)return;index+=delta;load();};prev.onclick=()=>move(-1);next.onclick=()=>move(1);fit.onclick=fitImage;native.onclick=()=>zoom(1);minus.onclick=()=>zoom(scale/1.25);plus.onclick=()=>zoom(scale*1.25);close.onclick=()=>dialog.close();
 stage.addEventListener('wheel',event=>{if(!ready)return;event.preventDefault();zoom(scale*Math.exp(-event.deltaY*.002));},{passive:false});stage.ondblclick=()=>{if(ready)scale>fitScale+.01?fitImage():zoom(Math.max(1,fitScale*2));};
 stage.onpointerdown=event=>{if(!ready||event.target===retry)return;stage.setPointerCapture(event.pointerId);points.set(event.pointerId,{x:event.clientX,y:event.clientY});if(points.size===1)drag={startX:event.clientX,startY:event.clientY,x,y,zoomed:scale>fitScale+.01};if(points.size===2){const [a,b]=[...points.values()];pinch={distance:Math.hypot(a.x-b.x,a.y-b.y),scale};drag=null;}};
 stage.onpointermove=event=>{if(!points.has(event.pointerId))return;points.set(event.pointerId,{x:event.clientX,y:event.clientY});if(points.size===2&&pinch){const[a,b]=[...points.values()];zoom(pinch.scale*Math.hypot(a.x-b.x,a.y-b.y)/Math.max(1,pinch.distance));}else if(drag?.zoomed){x=drag.x+event.clientX-drag.startX;y=drag.y+event.clientY-drag.startY;clamp();render();}};
 stage.onpointerup=event=>{if(drag&&!drag.zoomed&&Math.abs(event.clientX-drag.startX)>65&&Math.abs(event.clientY-drag.startY)<65)move(event.clientX<drag.startX?1:-1);points.delete(event.pointerId);drag=pinch=null;};stage.onpointercancel=event=>{points.delete(event.pointerId);drag=pinch=null;};
 dialog.addEventListener('keydown',event=>{if(event.key==='ArrowLeft'){event.preventDefault();move(-1);}if(event.key==='ArrowRight'){event.preventDefault();move(1);}if(event.key==='+'||event.key==='=')zoom(scale*1.25);if(event.key==='-')zoom(scale/1.25);});
 dialog.addEventListener('close',()=>{release?.();release=null;trigger?.focus({preventScroll:true});onClose?.();});new ResizeObserver(()=>{if(dialog.open&&ready)fitImage();}).observe(stage);
 singleton={open(list,selected=0,source=document.activeElement,options={}){items=list.filter(item=>item.src);if(!items.length)return;index=Math.max(0,Math.min(items.length-1,selected));if(!dialog.open){trigger=source;release=lockModalScroll();dialog.showModal();}onChange=options.onChange;onClose=options.onClose;load();close.focus({preventScroll:true});},close(){if(dialog.open)dialog.close();},get isOpen(){return dialog.open;}};return singleton;
}
export function enhanceImageLinks(root){const images=[...root.querySelectorAll('img')].filter(img=>!img.closest('button,[contenteditable=true]')&&!img.dataset.viewerReady);for(const img of images){img.dataset.viewerReady='true';const button=document.createElement('button');button.type='button';button.className='image-viewer-open';button.textContent='⤢';button.setAttribute('aria-label',document.documentElement.lang.startsWith('zh')?'查看大图':'View image');button.addEventListener('click',event=>{event.preventDefault();event.stopPropagation();const all=[...root.querySelectorAll('img[data-viewer-ready]')];imageViewer().open(all.map(i=>({src:i.dataset.original||i.currentSrc||i.src,title:i.alt})),all.indexOf(img),button);});const linked=img.closest('a');(linked||img.closest('picture')||img).after(button);}}
