import {lockModalScroll} from './modalScroll.mjs';
import '../styles/imageViewer.css';
let singleton;
export function imageViewer(){if(singleton)return singleton;
 const make=(tag,text)=>{const node=document.createElement(tag);if(text)node.textContent=text;return node;};
 const zh=document.documentElement.lang.startsWith('zh'),ja=document.documentElement.lang.startsWith('ja');const label=(cn,en,jp)=>zh?cn:ja?jp:en;
 const dialog=make('dialog');dialog.className='image-viewer';dialog.setAttribute('aria-label',label('图片查看器','Image viewer','画像ビューアー'));
 const header=make('header'),title=make('h2'),infoToggle=make('button',label('查看说明','Details','説明')),close=make('button','×');infoToggle.type='button';infoToggle.setAttribute('aria-expanded','false');infoToggle.setAttribute('aria-controls','image-viewer-info');close.type='button';close.setAttribute('aria-label',label('关闭','Close','閉じる'));header.append(title,infoToggle,close);
 const stage=make('div');stage.className='image-viewer__stage';const img=new Image();img.draggable=false;const feedback=make('p');feedback.setAttribute('role','status');const pageStatus=make('p');pageStatus.className='image-viewer__page-status';pageStatus.setAttribute('role','status');pageStatus.hidden=true;const retry=make('button',label('重新载入图片','Retry image','再読み込み'));retry.type='button';retry.hidden=true;stage.append(img,feedback,pageStatus,retry);
 const info=make('aside');info.className='image-viewer__info';info.id='image-viewer-info';const infoHeading=make('h3',label('图片资料','Image details','画像情報')),metadata=make('dl'),details=make('dd'),dimensions=make('dd'),actionsHeading=make('h3',label('相关操作','Actions','操作')),links=make('div');metadata.className='image-viewer__metadata';details.className='image-viewer__details';dimensions.className='image-viewer__details';links.className='image-viewer__actions';info.append(infoHeading,metadata,actionsHeading,links);
 const metadataRow=(key,value)=>{if(!value)return;const row=make('div'),dt=make('dt',key),dd=typeof value==='string'?make('dd',value):value;row.append(dt,dd);metadata.append(row);};
 const footer=make('footer'),prev=make('button','←'),next=make('button','→'),fit=make('button',label('适应窗口','Fit','全体表示')),native=make('button','100%'),minus=make('button','−'),plus=make('button','＋'),scaleLabel=make('output');for(const b of [prev,next,fit,native,minus,plus])b.type='button';prev.setAttribute('aria-label',label('上一张','Previous','前へ'));next.setAttribute('aria-label',label('下一张','Next','次へ'));minus.setAttribute('aria-label',label('缩小','Zoom out','縮小'));plus.setAttribute('aria-label',label('放大','Zoom in','拡大'));footer.append(prev,fit,native,minus,scaleLabel,plus,next);dialog.append(header,stage,info,footer);document.body.append(dialog);
 let items=[],index=0,totalCount=0,trigger,release,scale=1,fitScale=1,x=0,y=0,points=new Map(),drag=null,pinch=null,ready=false,onChange,onClose,onNeedMore,loadingMore=false,viewRevision=0,preloaded=[];
 const setInfoVisible=visible=>{dialog.classList.toggle('image-viewer--info-open',visible);infoToggle.setAttribute('aria-expanded',String(visible));infoToggle.textContent=visible?label('收起说明','Hide details','説明を閉じる'):label('查看说明','Details','説明');};
 infoToggle.onclick=()=>setInfoVisible(!dialog.classList.contains('image-viewer--info-open'));
 const render=()=>{img.style.transform=`translate(${x}px,${y}px) scale(${scale})`;scaleLabel.textContent=Math.round(scale*100)+'%';stage.dataset.zoomed=String(scale>fitScale+.01);};
 const clamp=()=>{const r=stage.getBoundingClientRect();x=Math.max(-Math.max(0,(img.naturalWidth*scale-r.width)/2+24),Math.min(x,Math.max(0,(img.naturalWidth*scale-r.width)/2+24)));y=Math.max(-Math.max(0,(img.naturalHeight*scale-r.height)/2+24),Math.min(y,Math.max(0,(img.naturalHeight*scale-r.height)/2+24)));};
 function zoom(value){scale=Math.max(Math.min(fitScale,1),Math.min(8,value));clamp();render();}
 function fitImage(){const r=stage.getBoundingClientRect();fitScale=Math.min(1,(r.width-32)/img.naturalWidth,(r.height-32)/img.naturalHeight);scale=fitScale;x=y=0;render();}
 const updateNavigation=()=>{details.textContent=`${index+1} / ${Math.max(items.length,totalCount)}`;prev.disabled=loadingMore||index===0;next.disabled=loadingMore||(index===items.length-1&&!onNeedMore);next.setAttribute('aria-busy',String(loadingMore));};
 function load(){ready=false;points.clear();pinch=drag=null;img.style.visibility='hidden';retry.hidden=true;feedback.hidden=false;pageStatus.hidden=true;feedback.textContent=label('正在载入…','Loading…','読み込み中…');const item=items[index];title.textContent=item.title||label('图片','Image','画像');metadata.replaceChildren();const rows=Array.isArray(item.metadata)?item.metadata:[{label:label('说明','Description','説明'),value:item.notes||label('暂无补充说明','No additional description','補足説明はありません')}];for(const row of rows)metadataRow(row.label,row.value);dimensions.textContent='—';metadataRow(label('浏览位置','Position','表示位置'),details);metadataRow(label('图片尺寸','Dimensions','画像サイズ'),dimensions);links.replaceChildren();const actions=[{href:item.downloadUrl||item.src,label:item.downloadLabel||label('下载图片','Download image','画像を保存'),download:true,kind:'primary'},...(item.links||[])];for(const link of actions){let url;try{url=new URL(link.href,location.href);}catch{continue;}if(!['http:','https:'].includes(url.protocol))continue;const a=make('a',link.label);a.href=url.href;a.className='image-viewer__action';if(link.kind==='primary')a.classList.add('image-viewer__action--primary');if(link.download){a.dataset.download='true';if(url.origin===location.origin)a.download=item.fileName||'';}else if(url.origin!==location.origin){a.target='_blank';a.rel='noopener noreferrer';a.dataset.external='true';}links.append(a);}img.alt=item.title||'';img.src=item.src;updateNavigation();onChange?.(item,index);preloaded=[items[index-1],items[index+1]].filter(Boolean).map(item=>{const p=new Image();p.src=item.src;return p;});}
 img.onload=()=>{ready=true;img.style.visibility='visible';feedback.hidden=true;dimensions.textContent=`${img.naturalWidth} × ${img.naturalHeight} px`;fitImage();};img.onerror=()=>{feedback.textContent=label('图片载入失败','Image failed to load','読み込めませんでした');retry.hidden=false;};retry.onclick=load;
 const move=async delta=>{if(index+delta<0||loadingMore)return;if(index+delta<items.length){index+=delta;load();return;}if(delta!==1||!onNeedMore)return;const revision=viewRevision,loader=onNeedMore;loadingMore=true;updateNavigation();pageStatus.textContent=label('正在加载后续照片…','Loading more photos…','次の写真を読み込み中…');pageStatus.hidden=false;try{const result=await loader();if(revision!==viewRevision||!dialog.open)return;const known=new Set(items.map(item=>item.id||item.src)),incoming=(result.items||[]).filter(item=>{const key=item.id||item.src;if(!item.src||known.has(key))return false;known.add(key);return true;});items.push(...incoming);totalCount=Number.isFinite(result.totalCount)?result.totalCount:totalCount;onNeedMore=result.hasMore?loader:null;if(incoming.length){index++;load();}else if(onNeedMore)throw Error('No new photos');else{pageStatus.hidden=true;updateNavigation();}}catch{if(revision!==viewRevision||!dialog.open)return;pageStatus.textContent=label('后续照片加载失败，请再点下一张重试','Could not load more photos. Select Next to retry.','次の写真を読み込めませんでした。もう一度「次へ」を押してください');pageStatus.hidden=false;}finally{if(revision===viewRevision){loadingMore=false;updateNavigation();}}};prev.onclick=()=>void move(-1);next.onclick=()=>void move(1);fit.onclick=fitImage;native.onclick=()=>zoom(1);minus.onclick=()=>zoom(scale/1.25);plus.onclick=()=>zoom(scale*1.25);close.onclick=()=>dialog.close();
 stage.addEventListener('wheel',event=>{if(!ready)return;event.preventDefault();zoom(scale*Math.exp(-event.deltaY*.002));},{passive:false});stage.ondblclick=()=>{if(ready)scale>fitScale+.01?fitImage():zoom(Math.max(1,fitScale*2));};
 stage.onpointerdown=event=>{if(!ready||event.target===retry)return;stage.setPointerCapture(event.pointerId);points.set(event.pointerId,{x:event.clientX,y:event.clientY});if(points.size===1)drag={startX:event.clientX,startY:event.clientY,x,y,zoomed:scale>fitScale+.01};if(points.size===2){const [a,b]=[...points.values()];pinch={distance:Math.hypot(a.x-b.x,a.y-b.y),scale};drag=null;}};
 stage.onpointermove=event=>{if(!points.has(event.pointerId))return;points.set(event.pointerId,{x:event.clientX,y:event.clientY});if(points.size===2&&pinch){const[a,b]=[...points.values()];zoom(pinch.scale*Math.hypot(a.x-b.x,a.y-b.y)/Math.max(1,pinch.distance));}else if(drag?.zoomed){x=drag.x+event.clientX-drag.startX;y=drag.y+event.clientY-drag.startY;clamp();render();}};
 stage.onpointerup=event=>{if(drag&&!drag.zoomed&&Math.abs(event.clientX-drag.startX)>65&&Math.abs(event.clientY-drag.startY)<65)move(event.clientX<drag.startX?1:-1);points.delete(event.pointerId);drag=pinch=null;};stage.onpointercancel=event=>{points.delete(event.pointerId);drag=pinch=null;};
 dialog.addEventListener('keydown',event=>{if(event.key==='ArrowLeft'){event.preventDefault();move(-1);}if(event.key==='ArrowRight'){event.preventDefault();move(1);}if(event.key==='+'||event.key==='=')zoom(scale*1.25);if(event.key==='-')zoom(scale/1.25);});
 dialog.addEventListener('close',()=>{viewRevision++;loadingMore=false;release?.();release=null;trigger?.focus({preventScroll:true});onClose?.();});new ResizeObserver(()=>{if(dialog.open&&ready)fitImage();}).observe(stage);
 singleton={open(list,selected=0,source=document.activeElement,options={}){items=list.filter(item=>item.src);if(!items.length)return;viewRevision++;loadingMore=false;index=Math.max(0,Math.min(items.length-1,selected));totalCount=Number.isFinite(options.totalCount)?options.totalCount:items.length;onNeedMore=options.onNeedMore;dialog.classList.toggle('image-viewer--photo-first',Boolean(options.photoFirst));setInfoVisible(true);if(!dialog.open){trigger=source;release=lockModalScroll();dialog.showModal();}onChange=options.onChange;onClose=options.onClose;load();close.focus({preventScroll:true});},close(){if(dialog.open)dialog.close();},get isOpen(){return dialog.open;}};return singleton;
}
export function enhanceImageLinks(root){
 const images=[...root.querySelectorAll('img')].filter(img=>!img.closest('button,[contenteditable=true]')&&!img.dataset.viewerReady);
 const label=document.documentElement.lang.startsWith('zh')?'查看图片':document.documentElement.lang.startsWith('ja')?'画像を表示':'View image';
 for(const img of images){
  img.dataset.viewerReady='true';
  const link=img.closest('a'),imageOnlyLink=link&&link.querySelectorAll('img').length===1&&!link.textContent.trim();
  const open=event=>{event.preventDefault();event.stopPropagation();const all=[...document.querySelectorAll('.wiki-reader img[data-viewer-ready],.wiki-infobox img[data-viewer-ready]')];imageViewer().open(all.map(i=>({src:i.dataset.original||i.currentSrc||i.src,title:i.alt})),all.indexOf(img),imageOnlyLink||img);};
  if(imageOnlyLink){link.setAttribute('role','button');link.setAttribute('aria-label',img.alt?`${label}：${img.alt}`:label);link.addEventListener('click',open);link.addEventListener('keydown',event=>{if(event.key==='Enter'||event.key===' ')open(event);});}
  else{img.tabIndex=0;img.setAttribute('role','button');img.setAttribute('aria-label',img.alt?`${label}：${img.alt}`:label);img.addEventListener('click',open);img.addEventListener('keydown',event=>{if(event.key==='Enter'||event.key===' ')open(event);});}
 }
}
