import { personalToolsCopy } from './personalToolsCopy.mjs';
import { resolveLocaleCopy } from './i18n.mjs';
const zh = {
  title: 'LABs · 观测实验室',
  intro: '把散落的时间、作品与人，连成自己的观测路径。',
  home: '返回观测站',
  labs: 'LABs',
  tabs: [
    '探索',
    '活动时间线',
    '关系图谱',
    '世界与故事',
    '我的收藏',
    '资料共建',
  ],
  descriptions: [
    '从一个名字、一首歌或一个故事开始。',
    '沿着出道、作品发行和站内记录，回看神椿的轨迹。',
    '从词条中的明确关联出发，寻找艺人、组合、企划与作品之间的连接。',
    '按媒介梳理故事入口，先了解背景，再决定读到哪里。',
    '把喜欢的内容留在这里，整理成歌单和观测清单。',
    '补充一份有出处的资料，让下一位观测者少走一点弯路。',
  ],
  search: '搜索名称、别名或关键词',
  all: '全部',
  kind: '内容类型',
  year: '年份',
  order: '排序',
  newest: '由新到旧',
  oldest: '由旧到新',
  kinds: {
    events: '演出与活动',
    artists: '艺人出道',
    songs: '歌曲发行',
    albums: '专辑发行',
    projects: '企划',
    logs: '站务记录',
  },
  loading: '正在读取词条索引…',
  failure: '索引加载失败，请重试。',
  retry: '重试',
  empty: '没有符合条件的内容。试试其他关键词或清除筛选。',
  more: '加载更多',
  reset: '清除筛选',
  results: '条结果',
  dateNote:
    '日期来自现有词条；仅精确到年或月的日期按原精度显示。站务记录不代表演出日期，缺少日期的词条不会推测补齐。',
  graphNote:
    '连线表示词条推荐关联或作品署名，不自动推断私人关系、成员身份或剧情设定。',
  choose: '选择中心词条',
  affiliation: '所属关联',
  related: '关联词条',
  credit: '作品署名',
  evidence: '查看关联依据',
  open: '打开词条',
  noRelations: '还没有结构化关联，可通过资料共建补充。',
  save: '收藏',
  saved: '已收藏',
  remove: '移除',
  library: '我的收藏',
  storageNote:
    '保存在当前浏览器，不跨设备同步。可导出备份；清除浏览器数据会移除收藏。',
  storageError: '无法读取或保存本地数据，请检查浏览器存储权限。原数据未覆盖。',
  listName: '新清单名称',
  create: '创建清单',
  allSaved: '全部收藏',
  export: '导出备份',
  import: '导入备份',
  imported: '备份已合并',
  importError: '无法导入：请使用有效的观测站收藏备份（最大 2 MB）。',
  noSaved: '还没有收藏。去时间线、关系图或词条页，收藏你的第一个发现。',
  addTo: '加入清单',
  list: '选择清单',
  up: '上移',
  down: '下移',
  rename: '重命名',
  deleteList: '删除空清单',
  renamed: '清单已更新',
  practice: '歌词练习',
  practiceIntro: '在歌曲页面逐句练习，可切换注音、隐藏译文或按自己的速度循环。',
  practiceOpen: '找一首歌练习',
  explore: '发现内容',
  fullSearch: '全文搜索',
  worldNote:
    '阅读顺序是编辑整理的入门路线，不表示不同作品的世界线连续。剧情默认折叠；全文请前往正版来源。',
  spoiler: '展开背景提示（可能包含设定剧透）',
  source: '来源',
  novels: '小说与衍生作品',
  projects: '企划资料库',
  game: '记忆回廊',
  gameIntro: '探索、收集记忆，再从游戏中的传送门回到词条。',
  play: '进入游戏',
  random: '随机观测',
  submissionTitle: '资料标题',
  category: '资料类型',
  sourceUrl: '资料来源链接',
  body: '补充说明 / Markdown 正文',
  attachment: '导入文本资料（.md / .txt，最大 1 MB）',
  rights: '我已核对出处，并确认有权提交这份文字。',
  preview: '预览草稿',
  download: '下载 Markdown 草稿',
  github: '前往 GitHub 提交审核',
  submissionNote:
    '草稿仅保存在本机。选择提交会打开 GitHub Issue 草稿，需登录并由你确认发布；资料经审核后才能进入词条。图片和大型附件可在 GitHub 添加。',
  draftSaved: '草稿已保存到本机',
  draftError: '草稿暂未保存，请下载备份。',
  fileError: '请选择不超过 1 MB 的 Markdown 或文本文件。',
  previewHint: '填写资料后预览；支持标题、列表和链接，不执行 HTML。',
  sourceNote:
    '来源链接用于核对，不代表已审核。请优先提供官方发布、出版机构或获得授权的歌词页面。',
};
const en = {
  title: 'LABs · Observation Lab',
  intro:
    'Connect the people, works and moments into your own path through Kamitsubaki.',
  home: 'Back to the wiki',
  labs: 'LABs',
  tabs: [
    'Explore',
    'Timeline',
    'Relationships',
    'Worlds & stories',
    'My library',
    'Contribute',
  ],
  descriptions: [
    'Start with a name, a song or a story.',
    'Follow debuts, releases and archive updates through time.',
    'Explore explicit connections recorded in the wiki.',
    'Find a reading route across stories and media.',
    'Save discoveries and organize personal playlists.',
    'Share a source-backed addition with the community.',
  ],
  search: 'Search names, aliases or keywords',
  all: 'All',
  kind: 'Content type',
  year: 'Year',
  order: 'Order',
  newest: 'Newest first',
  oldest: 'Oldest first',
  kinds: {
    events: 'Live / event',
    artists: 'Artist debut',
    songs: 'Song release',
    albums: 'Album release',
    projects: 'Project',
    logs: 'Archive update',
  },
  loading: 'Loading the archive…',
  failure: 'Could not load the archive.',
  retry: 'Retry',
  empty: 'No matching entries. Try another term or reset the filters.',
  more: 'Load more',
  reset: 'Reset filters',
  results: 'results',
  dateNote:
    'Dates come from existing entries and retain their year/month precision. Archive updates are not concert dates. Undated entries are excluded.',
  graphNote:
    'Edges show related-entry links or work credits, not inferred personal relationships, membership or fictional canon.',
  choose: 'Choose a central entry',
  affiliation: 'Affiliation',
  related: 'Related entry',
  credit: 'Work credit',
  evidence: 'View evidence',
  open: 'Open entry',
  noRelations: 'No structured connections yet. Help add a source.',
  save: 'Save',
  saved: 'Saved',
  remove: 'Remove',
  library: 'My library',
  storageNote:
    'Saved in this browser only. Export a backup before clearing browser data.',
  storageError:
    'Browser storage is unavailable or invalid. Existing data has not been overwritten.',
  listName: 'New list name',
  create: 'Create list',
  allSaved: 'All saved',
  export: 'Export backup',
  import: 'Import backup',
  imported: 'Backup merged',
  importError: 'Use a valid wiki library backup, up to 2 MB.',
  noSaved:
    'No saved entries yet. Save a discovery from the timeline, graph or any article.',
  addTo: 'Add to list',
  list: 'Choose a list',
  up: 'Move up',
  down: 'Move down',
  rename: 'Rename',
  deleteList: 'Delete empty list',
  renamed: 'List updated',
  practice: 'Lyrics practice',
  practiceIntro:
    'Practice line by line on song pages, with reading aids, hidden translations and a self-paced loop.',
  practiceOpen: 'Find a song',
  explore: 'Discover',
  fullSearch: 'Full-text search',
  worldNote:
    'This editorial reading route does not imply continuity between worlds. Story hints are collapsed. Read full works through legitimate sources.',
  spoiler: 'Show background (possible setting spoilers)',
  source: 'Source',
  novels: 'Novels & related works',
  projects: 'Project archive',
  game: 'Memory Corridor',
  gameIntro:
    'Explore, collect memories and follow portals back to wiki entries.',
  play: 'Enter the game',
  random: 'Random discovery',
  submissionTitle: 'Title',
  category: 'Content type',
  sourceUrl: 'Source URL',
  body: 'Notes / Markdown body',
  attachment: 'Import text (.md / .txt, up to 1 MB)',
  rights: 'I have checked the source and have permission to submit this text.',
  preview: 'Preview draft',
  download: 'Download Markdown',
  github: 'Open GitHub review draft',
  submissionNote:
    'Drafts stay on this device. Submission opens a GitHub Issue draft for you to sign in and publish. Add images or large attachments on GitHub. Contributions require review.',
  draftSaved: 'Draft saved locally',
  draftError: 'Could not save the draft. Download a backup.',
  fileError: 'Choose a Markdown or text file under 1 MB.',
  previewHint:
    'Preview headings, lists and links here. HTML is never executed.',
  sourceNote:
    'A source link is not an approval. Prefer official publishers and authorized lyrics pages.',
};
const ja = {
  ...en,
  title: 'LABs · 観測ラボ',
  intro: '人、作品、時間をつないで、自分だけの観測ルートへ。',
  home: 'Wiki に戻る',
  tabs: [
    '探索',
    'タイムライン',
    '関係図',
    '世界と物語',
    'マイライブラリ',
    '資料の投稿',
  ],
  descriptions: [
    '名前、曲、物語から探索を始めましょう。',
    'デビュー、リリース、更新記録を時系列で。',
    '記事に記された関連をたどります。',
    '物語とメディアの入口を探します。',
    'お気に入りをリストに整理します。',
    '出典付きの資料を共有しましょう。',
  ],
  search: '名前・別名・キーワードで検索',
  all: 'すべて',
  kind: '種類',
  year: '年',
  order: '並び順',
  newest: '新しい順',
  oldest: '古い順',
  kinds: {
    events: '公演・イベント',
    artists: 'デビュー',
    songs: '楽曲発売',
    albums: 'アルバム発売',
    projects: '企画',
    logs: 'サイト更新',
  },
  loading: '読込中…',
  retry: '再試行',
  more: 'もっと見る',
  reset: 'リセット',
  results: '件',
  save: '保存',
  saved: '保存済み',
  remove: '削除',
  library: 'マイライブラリ',
  choose: '中心の記事を選択',
  affiliation: '所属関連',
  related: '関連記事',
  credit: '作品クレジット',
  evidence: '出典を確認',
  open: '記事を開く',
  listName: '新しいリスト名',
  create: 'リスト作成',
  allSaved: 'すべての保存',
  export: 'バックアップ出力',
  import: 'バックアップ読込',
  addTo: 'リストに追加',
  list: 'リストを選択',
  up: '上へ',
  down: '下へ',
  rename: '名前を変更',
  deleteList: '空のリストを削除',
  practice: '歌詞練習',
  practiceOpen: '曲を探す',
  fullSearch: '全文検索',
  novels: '小説・関連作品',
  projects: '企画一覧',
  game: '記憶回廊',
  play: 'ゲームへ',
  random: 'ランダム観測',
  submissionTitle: 'タイトル',
  category: '資料の種類',
  sourceUrl: '出典 URL',
  body: '本文 / Markdown',
  preview: '下書きのプレビュー',
  download: 'Markdown を保存',
  github: 'GitHub でレビューへ',
  source: '出典',
};
Object.assign(ja, {
  failure: '資料を読み込めませんでした。',
  empty: '一致する記事がありません。別のキーワードかリセットをお試しください。',
  dateNote:
    '日付は既存の記事に基づき、年・月のみの日付はその精度で表示します。サイト更新日は公演日ではありません。日付不明の記事は除外します。',
  graphNote:
    '線は記事の関連リンク、所属情報、作品クレジットを示します。個人的な関係や物語の設定を推測しません。',
  noRelations:
    '構造化された関連情報がまだありません。出典付きの資料を投稿できます。',
  storageNote:
    'このブラウザー内に保存します。端末間の同期はありません。ブラウザーのデータを消す前にバックアップしてください。',
  storageError:
    '保存データを読み書きできません。既存のデータは上書きしていません。',
  imported: 'バックアップを統合しました。',
  importError: '2 MB 以下の有効なライブラリーバックアップを選んでください。',
  noSaved:
    'まだ保存した記事がありません。タイムライン、関係図、記事の保存ボタンから始めましょう。',
  renamed: 'リストを更新しました。',
  practiceIntro:
    '楽曲ページで一行ずつ練習。ふりがな、訳の表示、好きなペースでの繰り返しに対応します。',
  explore: 'コンテンツを探す',
  worldNote:
    '編集者による入門ルートで、異なる作品の世界線が連続することを示すものではありません。設定の紹介は折りたたんでいます。全文は正規の提供元でお読みください。',
  spoiler: '背景を表示（設定のネタバレを含む可能性）',
  gameIntro: '記憶を集め、ポータルから関連記事を訪ねましょう。',
  attachment: 'テキストを読み込む（.md / .txt、1 MB 以下）',
  rights: '出典を確認し、この文章を投稿する権利があることを確認しました。',
  submissionNote:
    '下書きは端末にのみ保存します。投稿ボタンで GitHub Issue の下書きを開き、ログイン後に自分で公開します。画像や大きな添付は GitHub で追加してください。記事への反映にはレビューが必要です。',
  draftSaved: '下書きを端末に保存しました。',
  draftError: '保存できませんでした。バックアップをダウンロードしてください。',
  fileError: '1 MB 以下の Markdown またはテキストファイルを選んでください。',
  previewHint:
    '見出し、リスト、リンクをプレビューできます。HTML は実行しません。',
  sourceNote:
    '出典リンクは承認を意味しません。公式発表、出版社、許諾のある歌詞ページを優先してください。',
});
export function labsCopy(locale) {
  const copy = resolveLocaleCopy({ zh, en, ja }, locale);
  copy.clearDraft = resolveLocaleCopy(
    { zh: '清空草稿', ja: '下書きをクリア', en: 'Clear draft' },
    locale,
  );
  copy.entryKinds = resolveLocaleCopy(
    {
      zh: {
        events: '活动',
        artists: '艺人',
        songs: '歌曲',
        albums: '专辑',
        projects: '企划',
        logs: '站务记录',
      },
      ja: {
        events: 'イベント',
        artists: 'アーティスト',
        songs: '楽曲',
        albums: 'アルバム',
        projects: '企画',
        logs: 'サイト更新',
      },
      en: {
        events: 'Event',
        artists: 'Artist',
        songs: 'Song',
        albums: 'Album',
        projects: 'Project',
        logs: 'Archive update',
      },
    },
    locale,
  );
  return { ...copy, ...personalToolsCopy(locale) };
}
export const labsSections = [
  'explore',
  'timeline',
  'relations',
  'world',
  'library',
  'submit',
];
