import { resolveLocaleCopy } from './i18n.mjs';
const text = {
  strike: ['删除线','Strikethrough','取り消し線'],
  workbench: ['词条编辑器','Article editor','記事エディター'],
  commands: ['搜索命令或插入内容…','Search commands or insert content…','コマンド検索・内容の挿入…'],
  outline: ['大纲','Outline','アウトライン'],
  files: ['词条','Articles','記事'],
  properties: ['属性','Properties','プロパティ'],
  visual: ['可视化','Visual','ビジュアル'],
  codeView: ['源码','Source','ソース'],
  insert: ['插入内容','Insert content','内容を挿入'],
  split: ['并排预览','Split preview','並べて表示'],
  writeOnly: ['专注写作','Focus on writing','執筆に集中'],
  previewOnly: ['只看预览','Preview only','プレビューのみ'],
  toggleSidebar: ['切换侧栏','Toggle sidebar','サイドバー切替'],
  emptyTitle: ['词条标题','Article title','記事のタイトル'],
  emptyParagraph: ['在这里写正文，或按 / 插入内容…','Start writing, or press / to insert…','本文を書く、または / で挿入…'],
  emptyOutline: ['写下第一个章节，大纲会出现在这里。','Add a heading to build your outline.','見出しを追加するとここに表示されます。'],
  selectBlock: ['点击正文中的内容，查看它的设置。','Select content in the document to edit its settings.','本文を選択すると設定が表示されます。'],
  duplicate: ['复制内容块','Duplicate block','ブロックを複製'],
  insertAfter: ['在此后插入','Insert after','後ろに挿入'],
  sourceError: ['源码暂时无法解析。内容已保留，请修正 YAML 后继续。','Source cannot be parsed yet. Your text is retained; fix the YAML to continue.','ソースを解析できません。入力は保持されています。YAML を修正してください。'],
  sourceRecovered: ['已恢复尚未应用的源码。修正后将同步到可视化视图。','Unapplied source restored. Fix it to sync the visual view.','未適用のソースを復元しました。修正するとビジュアル表示に反映されます。'],
  sourcePending: ['源码尚未同步','Source not synced','ソース未同期'],
  exportMenu: ['导出 Markdown','Export Markdown','Markdown を出力'],
  exportDraft: ['下载草稿','Download draft','下書きを保存'],
  exportHint: ['可以先下载草稿；提交前请补全下列信息。','You can download a draft now. Complete these items before submitting.','下書きは保存できます。投稿前に以下を確認してください。'],
  noCommands: ['没有匹配项','No matches','一致する項目がありません'],
  searchText: ['查找正文','Find in document','本文を検索'],
  nextMatch: ['查找下一个','Find next','次を検索'],
  noMatches: ['未找到','No matches','見つかりません'],
  blockCount: ['个内容块','blocks','ブロック'],
  removeRow: ['删除末行','Remove last row','最終行を削除'],
  removeColumn: ['删除末列','Remove last column','最終列を削除'],
  light: ['浅色','Light','ライト'],
  dark: ['深色','Dark','ダーク'],
  system: ['跟随系统','System','システム'],
  theme: ['外观','Appearance','外観'],
  toolsHint: ['选中文字使用格式工具；点击内容块可查看属性。','Select text to format it; select a block to inspect its properties.','文字を選択して書式設定。ブロックを選択してプロパティを編集。'],

  advanced: ['高级属性', 'Advanced properties', '詳細プロパティ'],
  addProperty: ['添加属性组', 'Add property group', 'プロパティを追加'],
  specialFormat: ['特殊格式', 'Special formatting', '特殊書式'],
  apply: ['应用', 'Apply', '適用'],
  argument: ['内容', 'Content', '内容'],
  explanation: ['解释 / 日期', 'Explanation / date', '説明 / 日付'],
  taiwan: ['台湾繁体用词', 'Taiwan Traditional Chinese', '台湾繁体字'],
  hongkong: ['香港繁体用词', 'Hong Kong Traditional Chinese', '香港繁体字'],
  timestamp: ['开始时间（00:03.50）', 'Start time (00:03.50)', '開始時刻（00:03.50）'],
  addUnit: ['拆分为逐字单元', 'Add timed unit', '時刻付き単位を追加'],
  addMedia: ['添加播放平台', 'Add platform', 'プラットフォームを追加'],
  languageName: ['代码语言', 'Code language', 'コードの言語'],
  formula: ['公式表达式', 'Formula expression', '数式'],
  displayMath: ['独立公式', 'Display equation', '独立した数式'],
  lyricsTiming: ['时间请按实际试听填写，按先后顺序递增；留空则使用普通歌词展示。', 'Enter timings from actual listening, in increasing order. Leave blank for untimed lyrics.', '実際に聴いて時刻を昇順に入力。空欄なら通常の歌詞として表示します。'],

  newEntry: ['新建词条', 'New article', '記事を新規作成'],
  editExisting: ['编辑旧词条', 'Edit existing article', '既存の記事を編集'],
  findEntry: ['搜索名称或文件路径', 'Search by title or file path', '記事名・ファイルパスで検索'],
  load: ['载入原文', 'Load original', '原文を読み込む'],
  loading: ['正在读取原始文件…', 'Loading the original file…', '原文を読み込み中…'],
  loaded: ['原有资料与正文已载入，未修改的内容会保留。', 'Original details and content loaded. Unchanged content is preserved.', '元の記事情報と本文を読み込みました。未編集の内容は保持されます。'],
  loadFailed: ['原文暂时无法读取，请重试或使用「导入原文」。当前草稿没有被替换。', 'Could not load the source. Retry or use Import source. Your draft has not been replaced.', '原文を読み込めません。再試行するか原文をインポートしてください。下書きは保持されています。'],
  notFound: ['没有找到匹配的词条', 'No matching articles', '一致する記事はありません'],

  title: ['可视化编辑器', 'Visual editor', 'ビジュアルエディター'],
  intro: ['把资料写成词条，不必先学语法。', 'Turn your research into an article, without learning markup.', '構文を覚えずに、調べた資料を記事に。'],
  open: ['打开可视化编辑器', 'Open visual editor', 'ビジュアルエディターを開く'],
  entryIntro: ['用内容块编写词条、填写资料并预览，完成后复制到 GitHub。', 'Write with visual blocks, preview, then copy the finished file to GitHub.', 'ブロックで記事を書き、プレビューして GitHub にコピー。'],
  back: ['资料共建', 'Contribute', '資料の共同編集'],
  guide: ['贡献指南', 'Contribution guide', '貢献ガイド'],
  syntax: ['语法参考', 'Syntax reference', '構文リファレンス'],
  format: ['格式指南', 'Style guide', 'スタイルガイド'],
  metadata: ['词条资料', 'Article details', '記事情報'],
  kind: ['词条类型', 'Article type', '記事の種類'],
  locale: ['内容语言', 'Content language', '本文の言語'],
  path: ['GitHub 文件路径（可选）', 'GitHub file path (optional)', 'GitHub ファイルパス（任意）'],
  pathHint: ['例如 src/content/songs/kaf/originals/entry-name/zh.md。已有文件请先导入原文。', 'For example: src/content/songs/kaf/originals/entry-name/en.md. Import the source before editing an existing file.', '例：src/content/songs/kaf/originals/entry-name/ja.md。既存ファイルは原文を読み込んでから編集してください。'],
  content: ['正文', 'Content', '本文'], preview: ['阅读预览', 'Preview', 'プレビュー'], source: ['导出内容', 'Export source', '出力内容'],
  add: ['添加内容', 'Add block', 'ブロックを追加'],
  import: ['导入原文', 'Import source', '原文を読み込む'],
  importHint: ['粘贴 GitHub 文件原文，或选择 .md 文件（最大 1 MB）。复杂语法会原样保留。', 'Paste the original GitHub file, or choose a .md file (up to 1 MB). Complex markup is preserved.', 'GitHub の原文を貼り付けるか .md ファイルを選択（最大 1 MB）。複雑な構文はそのまま保持します。'],
  applyImport: ['载入编辑器', 'Load into editor', 'エディターに読み込む'], cancel: ['取消', 'Cancel', 'キャンセル'],
  copy: ['复制完整 Markdown', 'Copy complete Markdown', 'Markdown 全体をコピー'], download: ['下载 .md', 'Download .md', '.md をダウンロード'],
  github: ['打开 GitHub 文件位置', 'Open file location on GitHub', 'GitHub の保存先を開く'],
  saved: ['草稿已保存在此浏览器', 'Draft saved in this browser', 'このブラウザーに下書きを保存しました'],
  unsaved: ['无法自动保存，请下载备份', 'Autosave unavailable. Please download a backup.', '自動保存できません。ダウンロードして保存してください。'],
  copied: ['已复制，可粘贴到 GitHub 文件编辑区', 'Copied. Paste into the GitHub file editor.', 'コピーしました。GitHub のファイル編集欄に貼り付けてください。'],
  copyFailed: ['复制失败，请切换「导出内容」手动复制，或下载文件', 'Copy failed. Copy manually from Export source, or download the file.', 'コピーできませんでした。出力内容から手動でコピーするかダウンロードしてください。'],
  review: ['导出前检查', 'Before you export', '出力前の確認'],
  ready: ['必填资料已齐全。请核对来源、授权和预览，再到 GitHub 检查差异并提交 PR。', 'Required fields are complete. Check sources, rights and the preview, then review your GitHub diff and open a PR.', '必須情報を入力済みです。出典・権利・プレビューを確認し、GitHub の差分を確認して PR を送ってください。'],
  missing: ['请填写或检查：', 'Complete or check: ', '入力・確認してください：'],
  note: ['媒体按需载入；图片文件需另行上传到仓库。', 'Media loads on demand. Upload image files to the repository separately.', 'メディアは必要に応じて読み込みます。画像は別途リポジトリにアップロードしてください。'],
  rule: ['先写可核实的事实，明确引用来源；正文从二级标题开始。各语言文件使用同一个条目标识。繁体中文由简体原稿生成。', 'Use verifiable facts and cite sources. Body headings start at level 2. Share the entry key across languages. Traditional Chinese is generated from Simplified Chinese.', '確認できる事実と出典を記載。本文は見出し 2 から始め、言語間で記事キーを共通にします。繁体字版は簡体字原稿から生成されます。'],
  sourceHint: ['用「段落」中的链接按钮添加来源。转载内容请保留原有授权字段。', 'Add source links with the paragraph link tool. Keep existing license fields for reused content.', '段落のリンクボタンで出典を追加。転載内容のライセンス情報は保持してください。'],
  preserved: ['原样保留的内容', 'Preserved source', 'そのまま保持する原文'],
  preservedHint: ['这部分含有复杂排版，不自动改写。导出时会完整保留；可在前后添加可视化内容块。', 'This section contains complex formatting and is exported unchanged. Add visual blocks before or after it.', '複雑な書式を含むため、そのまま出力します。前後にビジュアルブロックを追加できます。'],
  replace: ['这会替换当前草稿。请先复制或下载需要保留的内容，继续吗？', 'This replaces the current draft. Copy or download anything you want to keep. Continue?', '現在の下書きを置き換えます。必要な内容をコピーまたは保存しましたか？'],
  invalid: ['无法导入：请使用含完整词条资料的原始 .md 文件，语言为 zh、ja 或 en。', 'Import failed. Use an original .md file with valid frontmatter and a zh, ja or en locale.', '読み込めません。有効な記事情報を含む原文 .md（zh・ja・en）を使用してください。'],
  empty: ['在左侧填写资料，添加内容后即可预览。', 'Fill in the details and add content to see your article here.', '情報を入力し、本文を追加するとここに表示されます。'],
  up: ['上移', 'Move up', '上へ'], down: ['下移', 'Move down', '下へ'], remove: ['删除内容块', 'Remove block', 'ブロックを削除'],
  undo: ['撤销', 'Undo', '元に戻す'], redo: ['重做', 'Redo', 'やり直す'],
  bold: ['加粗', 'Bold', '太字'], italic: ['斜体', 'Italic', '斜体'], link: ['添加链接', 'Add link', 'リンクを追加'],
  url: ['链接地址', 'URL', 'URL'], text: ['文字', 'Text', 'テキスト'], caption: ['图片说明', 'Caption', 'キャプション'],
  paragraphHint: ['直接输入文字，选中文字后可加粗、斜体或添加链接。', 'Type here. Select text to make it bold, italic, or add a link.', '直接入力。文字を選択して太字・斜体・リンクを設定できます。'],
  lines: ['每行一项', 'One item per line', '1 行に 1 項目'], ordered: ['有序列表', 'Numbered list', '番号付きリスト'],
  row: ['添加一行', 'Add row', '行を追加'], column: ['添加一列', 'Add column', '列を追加'],
  kana: ['假名注音', 'Kana reading', 'かな'], romaji: ['罗马音', 'Romaji', 'ローマ字'], translation: ['译文', 'Translation', '訳文'],
  original: ['原文', 'Original text', '原文'], detailTitle: ['折叠标题', 'Disclosure title', '折りたたみの見出し'],
  loadOriginal: ['请先导入此文件的完整原文', 'Import the complete original file first', '先にファイルの原文全体を読み込んでください'],
};
const kinds = { artists: ['艺人 / 角色','Artist / character','アーティスト / キャラクター'], songs: ['歌曲','Song','楽曲'], albums: ['专辑','Album','アルバム'], projects: ['企划','Project','企画'], logs: ['活动记录','Event record','活動記録'] };
const blocks = { inline: ['行内特殊格式','Special inline formatting','特殊なインライン書式'], 'media-switcher':['多平台媒体切换','Media switcher','メディア切替'],code:['代码块','Code block','コードブロック'],math:['数学公式','Math equation','数式'], paragraph: ['段落','Paragraph','段落'], heading: ['章节标题','Heading','見出し'], list: ['列表','List','リスト'], quote: ['引用','Quote','引用'], image: ['图片','Image','画像'], table: ['表格','Table','表'], media: ['媒体播放','Media','メディア'], ruby: ['文字注音','Ruby text','ルビ'], details: ['折叠内容','Disclosure','折りたたみ'], lyrics: ['双语歌词','Bilingual lyrics','対訳歌詞'], divider: ['分隔线','Divider','区切り線'] };
/**
 * @template {Record<string, string[]>} T
 * @param {T} items
 * @param {string} locale
 * @returns {{[K in keyof T]: string}}
 */
function localized(items, locale) { return /** @type {{[K in keyof T]: string}} */ (Object.fromEntries(Object.entries(items).map(([key, [zh, en, ja]]) => [key, resolveLocaleCopy({zh, en, ja}, locale)]))); }
const inline = {ruby:['注音','Ruby','ルビ'],spoiler:['剧透黑幕','Spoiler','ネタバレ'],mark:['高亮','Highlight','強調'],abbr:['缩写解释','Abbreviation','略語の説明'],kbd:['按键','Keyboard key','キー'],time:['日期','Date','日付'],small:['小字','Small text','小さい文字'],sub:['下标','Subscript','下付き'],sup:['上标','Superscript','上付き'],'zh-variant':['繁体用词覆写','Chinese variant wording','繁体字表現の指定']};
export function editorCopy(locale) { return {...localized(text,locale), kinds:localized(kinds,locale), blocks:localized(blocks,locale),inline:localized(inline,locale)}; }
