const root=document.querySelector('[data-chronicle-editor]');
if(root){
 const $=selector=>root.querySelector(selector),form=$('[data-chronicle-form]'),c=JSON.parse(root.dataset.copy),api=root.dataset.api.replace(/\/$/,'');
 const params=new URLSearchParams(location.search),locale=root.dataset.locale;
 let viewerId=null,draftId=params.get('draft')||crypto.randomUUID(),draftVersion=0,operation=crypto.randomUUID(),submissionId=params.get('submission'),submissionVersion=null,mode=params.has('event')?'revise':'create',eventId=params.get('event'),year=Number(params.get('year'))||new Date().getFullYear(),baseSha=null,expectedHead=null,conflict=null,resolveConflict=false,busy=false,saveTimer;
 const field=name=>form.querySelector(`[name="${name}"]`);
 const say=(message,href,action)=>{const target=$('[data-editor-status]');target.replaceChildren(document.createTextNode(message));if(href){const link=document.createElement('a');link.href=href;link.textContent=` ${action||c.continueLogin} →`;target.append(link);}};
 const localKey=()=>`kamitsubaki-chronicle-draft-v1:${viewerId||'guest'}:${draftId}`;
 const request=async(path,method='GET',body)=>{const response=await fetch(api+'/api/chronicle'+path,{method,credentials:'include',cache:'no-store',signal:AbortSignal.timeout(20000),headers:body?{'Content-Type':'application/json'}:{},body:body?JSON.stringify(body):undefined});const data=await response.json().catch(()=>({}));if(!response.ok)throw Object.assign(Error(data.error?.message||c.status),{status:response.status});return data;};
 function selected(name){return [...form.querySelectorAll(`[name="${name}"]:checked`)].map(input=>input.value);}
 function sourceRows(){return [...form.querySelectorAll('[data-source-row]')].map(row=>({title:row.querySelector('[name=sourceTitle]').value.trim(),url:row.querySelector('[name=sourceUrl]').value.trim(),publisher:row.querySelector('[name=sourcePublisher]').value.trim(),page:row.querySelector('[name=sourcePage]').value.trim()})).filter(row=>row.title||row.url);}
 function eventData(){const text={};for(const lang of ['zh','ja','en']){const title=field(`title-${lang}`).value.trim(),summary=field(`summary-${lang}`).value.trim();if(title||summary)text[lang]={title,summary};}const related=field('related').value.split(',').map(value=>value.trim()).filter(Boolean).map(entity=>({entity,role:'subject'}));return {date:{start:field('start').value.trim(),end:field('end').value.trim(),precision:field('precision').value},text,sourceLocale:field('sourceLocale').value,tracks:selected('tracks'),eventTypes:selected('eventTypes'),importance:field('importance').value,related,sources:sourceRows()};}
 function addSource(source={}){const first=$('[data-source-row]'),row=first.cloneNode(true);row.querySelector('[name=sourceTitle]').value=source.title||'';row.querySelector('[name=sourceUrl]').value=source.url||'';row.querySelector('[name=sourcePublisher]').value=source.publisher||'';row.querySelector('[name=sourcePage]').value=source.page||'';row.querySelector('[data-remove-source]').onclick=()=>{if(form.querySelectorAll('[data-source-row]').length===1){row.querySelectorAll('input').forEach(input=>input.value='');}else row.remove();preview();};$('[data-sources]').append(row);return row;}
 function setSources(sources){const rows=$('[data-sources]');while(rows.children.length>1)rows.lastElementChild.remove();const first=rows.firstElementChild;first.querySelector('[name=sourceTitle]').value=sources?.[0]?.title||'';first.querySelector('[name=sourceUrl]').value=sources?.[0]?.url||'';first.querySelector('[name=sourcePublisher]').value=sources?.[0]?.publisher||'';first.querySelector('[name=sourcePage]').value=sources?.[0]?.page||'';for(const source of (sources||[]).slice(1))addSource(source);}
 function fill(event){if(!event)return;field('start').value=event.date?.start||'';field('end').value=event.date?.end||'';field('precision').value=event.date?.precision||'day';field('sourceLocale').value=event.sourceLocale||Object.keys(event.text||{})[0]||'zh';for(const lang of ['zh','ja','en']){field(`title-${lang}`).value=event.text?.[lang]?.title||'';field(`summary-${lang}`).value=event.text?.[lang]?.summary||'';}for(const box of form.querySelectorAll('[name=tracks],[name=eventTypes]'))box.checked=(event[box.name]||[]).includes(box.value);field('importance').value=event.importance||'regular';field('related').value=(event.related||[]).map(row=>row.entity).join(', ');setSources(event.sources);setLanguage(field('sourceLocale').value);syncDateFormat();preview();}
 function setLanguage(lang){for(const panel of form.querySelectorAll('[data-language-panel]'))panel.hidden=panel.dataset.languagePanel!==lang;for(const tab of form.querySelectorAll('[data-language]'))tab.setAttribute('aria-pressed',String(tab.dataset.language===lang));}
 function syncDateFormat(){const precision=field('precision').value,format=precision==='year'?'YYYY':precision==='month'?'YYYY-MM':'YYYY-MM-DD';for(const name of ['start','end'])field(name).placeholder=format;$('[data-date-format]').textContent=c[`dateFormat${precision[0].toUpperCase()+precision.slice(1)}`];}
 function preview(){const event=eventData(),lang=event.sourceLocale,authored=Object.keys(event.text).filter(key=>event.text[key].title&&event.text[key].summary);$('[data-preview-date]').textContent=event.date.start+(event.date.end?' — '+event.date.end:'');$('[data-preview-language]').textContent=authored.length?`${lang.toUpperCase()} · ${event.date.precision==='day'?c.day:event.date.precision==='month'?c.month:c.year}`:'';$('[data-preview-title]').textContent=event.text[lang]?.title||'—';$('[data-preview-summary]').textContent=event.text[lang]?.summary||'';$('[data-preview-meta]').textContent=[...event.tracks.map(value=>c.tracks[['music-live','project-verse','isotope-synth','organization-biz'].indexOf(value)]),...event.eventTypes.map(value=>c.types[['live','release','announcement','organization-change','anime','game','publication','exhibition'].indexOf(value)])].filter(Boolean).join(' / ');$('[data-preview-sources]').textContent=event.sources.map(source=>source.title).filter(Boolean).join(' · ');for(const lang of ['zh','ja','en'])$(`[data-language-state="${lang}"]`).textContent=authored.includes(lang)?'✓':c.missing;}
 function backup(){try{localStorage.setItem(localKey(),JSON.stringify({ownerId:viewerId,mode,year,eventId,baseSha,version:draftVersion,event:eventData(),updated:Date.now()}));return true;}catch{return false;}}
 function updateDraftUrl(){const url=new URL(location.href);url.searchParams.set('draft',draftId);if(mode==='revise'&&eventId){url.searchParams.set('event',eventId);url.searchParams.set('year',String(year));}history.replaceState(null,'',url);}
 async function save(){if(busy)return;busy=true;const localSaved=backup();try{if(!viewerId){updateDraftUrl();if(!localSaved){say(c.localUnavailable);return;}say(`${c.save} ✓ · ${c.guest}`,`/${locale}/account/?returnTo=${encodeURIComponent(location.pathname+location.search)}`,c.continueLogin);return;}const event=eventData(),draft={accountId:viewerId,version:draftVersion,mode,year:Number(event.date.start.slice(0,4))||year,eventId,baseSha,event};const result=await request('/drafts/'+draftId,'PUT',draft);draftVersion=result.version;year=draft.year;updateDraftUrl();say(c.save+' ✓');}catch(error){say(error.message);updateDraftUrl();}finally{busy=false;}}
 const conflictSummary=event=>{if(!event)return '—';const lang=event.sourceLocale||Object.keys(event.text||{})[0],entry=event.text?.[lang]||{};return [event.date?.start+(event.date?.end?' — '+event.date.end:''),entry.title,entry.summary].filter(Boolean).join(' · ');};
 async function showConflict(){if(!submissionId&&(mode!=='revise'||!eventId))return;try{const data=submissionId?await request('/submissions/'+encodeURIComponent(submissionId)+'/conflict'):await request('/source?year='+encodeURIComponent(year)+'&eventId='+encodeURIComponent(eventId));conflict={currentSha:data.currentSha??data.baseSha??null,currentEvent:data.currentEvent||data.event,headSha:data.headSha||null};$('[data-conflict-current]').textContent=conflictSummary(conflict.currentEvent);$('[data-conflict-yours]').textContent=conflictSummary(eventData());$('[data-chronicle-conflict]').hidden=false;}catch(error){say(error.message);}};
 async function submit(){if(busy)return;if(!viewerId){updateDraftUrl();if(!backup()){say(c.localUnavailable);return;}say(c.login,`/${locale}/account/?returnTo=${encodeURIComponent(location.pathname+location.search)}`,c.continueLogin);return;}busy=true;$('[data-submit]').disabled=true;backup();try{const event=eventData(),targetYear=Number(event.date.start.slice(0,4));if(!Number.isInteger(targetYear)||targetYear<2000)throw Error(c.date);const result=await request('/submissions','POST',{accountId:viewerId,operation,mode,year:mode==='revise'?year:targetYear,eventId,baseSha,event,draftId,submissionId,version:submissionVersion,resolve:resolveConflict,expectedHead});submissionId=result.id;submissionVersion=result.version;operation=crypto.randomUUID();resolveConflict=false;conflict=null;$('[data-chronicle-conflict]').hidden=true;try{localStorage.removeItem(localKey());}catch{}const url=new URL(location.href);url.searchParams.delete('draft');url.searchParams.set('submission',result.id);history.replaceState(null,'',url);say(c.reviewHint,`/${locale}/account/creator/?recordType=timeline&record=${encodeURIComponent(result.id)}`,c.viewRecord);}catch(error){say(error.status===409?`${error.message} ${c.save}`:error.message);if(error.status===409)void showConflict();}finally{busy=false;$('[data-submit]').disabled=false;}}
 async function initialize(){field('sourceLocale').value=locale==='ja'?'ja':locale==='en'?'en':'zh';setLanguage(field('sourceLocale').value);syncDateFormat();if(!submissionId&&!params.has('draft'))updateDraftUrl();try{const response=await fetch(api+'/api/auth/me',{credentials:'include',cache:'no-store',signal:AbortSignal.timeout(12000)});const data=await response.json();viewerId=data.viewer?.kind==='user'?data.viewer.userId:null;}catch{}
  if(submissionId&&viewerId){try{const saved=await request('/submissions/'+encodeURIComponent(submissionId));submissionVersion=saved.version;mode=saved.create?'create':'revise';year=Number(saved.structuredEvent.date.start.slice(0,4));eventId=saved.eventId;baseSha=saved.baseSha;fill(saved.structuredEvent);say(saved.syncError||c.status);if(saved.sync==='conflict')void showConflict();return;}catch(error){say(error.message);}}
  if(params.has('draft')){let loaded=false,cloud=false;if(viewerId)try{const saved=await request('/drafts/'+draftId);draftVersion=saved.version;mode=saved.mode;year=saved.year;eventId=saved.eventId;baseSha=saved.baseSha||baseSha;fill(saved.event);loaded=cloud=true;}catch{}if(!loaded)try{const saved=JSON.parse(localStorage.getItem(localKey())||localStorage.getItem(`kamitsubaki-chronicle-draft-v1:guest:${draftId}`)||'null');if(saved){mode=saved.mode;year=saved.year;eventId=saved.eventId;baseSha=saved.baseSha;fill(saved.event);loaded=true;}}catch{}if(loaded){if(cloud)say(c.save+' ✓');else if(viewerId)say(c.status);else say(c.guest,`/${locale}/account/?returnTo=${encodeURIComponent(location.pathname+location.search)}`,c.continueLogin);return;}}
  if(mode==='revise'&&eventId&&viewerId){try{const source=await request(`/source?year=${encodeURIComponent(year)}&eventId=${encodeURIComponent(eventId)}`);baseSha=source.baseSha;fill(source.event);say(c.status);}catch(error){say(error.message);}}
  if(!viewerId)say(c.guest,`/${locale}/account/?returnTo=${encodeURIComponent(location.pathname+location.search)}`,c.continueLogin);
  preview();
 }
 for(const tab of form.querySelectorAll('[data-language]'))tab.onclick=()=>setLanguage(tab.dataset.language);
 field('sourceLocale').onchange=()=>{setLanguage(field('sourceLocale').value);preview();};
 $('[data-confirm-conflict]').onclick=()=>{if(!conflict)return;baseSha=conflict.currentSha;expectedHead=conflict.headSha;resolveConflict=Boolean(submissionId);$('[data-chronicle-conflict]').hidden=true;backup();say(c.rechecked);};
 $('[data-add-source]').onclick=()=>{addSource();preview();};$('[data-remove-source]').onclick=()=>{form.querySelectorAll('[data-source-row] input').forEach(input=>input.value='');preview();};
 form.addEventListener('input',()=>{preview();clearTimeout(saveTimer);saveTimer=setTimeout(backup,450);});
 form.addEventListener('change',()=>{syncDateFormat();preview();});
 $('[data-save-draft]').onclick=()=>void save();form.onsubmit=event=>{event.preventDefault();void submit();};
 void initialize();
}
