const root=document.querySelector('[data-contribution-dashboard]');
if(root){
 const copy=JSON.parse(root.dataset.copy),locale=root.dataset.locale,button=root.querySelector('[data-progress-load]'),results=root.querySelector('[data-progress-results]');
 const request=async(base,path)=>{const response=await fetch(base.replace(/\/$/,'')+path,{credentials:'include',cache:'no-store',signal:AbortSignal.timeout(15000)});if(!response.ok)throw Object.assign(Error(copy.error),{status:response.status});return response.json();};
 const localDrafts=document.createElement('section');results.before(localDrafts);
 const sources=[
  {title:copy.tasks[0],href:`/${locale}/contribute/editor/?view=submissions`,load:async()=>{const session=await request(root.dataset.editorApi,'/api/editor/session');const data=await request(root.dataset.editorApi,'/api/editor/submissions?accountId='+encodeURIComponent(session.account.id));return data.submissions.map(item=>({title:item.title,status:item.status}));}},
  {title:copy.tasks[1],href:`/${locale}/articles/submit/`,load:async()=>(await request(root.dataset.api,'/api/articles/mine')).revisions.map(item=>({title:item.content.title,status:item.status,note:item.review_note}))},
  {title:copy.tasks[2],href:`/${locale}/gallery/manage/`,load:async()=>(await request(root.dataset.galleryApi,'/api/gallery/revisions')).revisions.map(item=>({title:item.metadata.title||item.metadata.character,status:item.status,note:item.review_note}))}
 ];
 const text=(tag,value,parent)=>{const node=document.createElement(tag);node.textContent=value;parent.append(node);return node;};
 try{for(let index=0;index<localStorage.length;index++){const key=localStorage.key(index);const match=key?.match(/^kamitsubaki-(?:visual-editor(?:-pr-demo)?-v1|article-workbench-v1:([^:]+)):(zh|ja|en)$/);if(!match)continue;const draft=JSON.parse(localStorage.getItem(key)||'null');if(!draft?.meta||!draft.blocks||!(draft.meta.title||draft.meta.name))continue;const article=key.startsWith('kamitsubaki-article-');const card=document.createElement('article');text('strong',draft.meta.title||draft.meta.name,card);text('p',locale==='en'?'Saved in this browser':locale==='ja'?'このブラウザーの下書き':'保存在此浏览器的草稿',card);const link=text('a',copy.open,card);link.href=article?`/${match[2]}/articles/submit/?draft=${encodeURIComponent(match[1])}`:`/${match[2]}/contribute/editor/`;localDrafts.append(card);}}catch{/* Browser storage may be unavailable; remote progress can still be loaded. */}
 button.addEventListener('click',async()=>{button.disabled=true;results.replaceChildren();await Promise.allSettled(sources.map(async source=>{const section=document.createElement('section');results.append(section);text('h3',source.title,section);const status=text('p',copy.loading,section);try{const items=await source.load();status.textContent=items.length?'':copy.empty;for(const item of items){const card=document.createElement('article');text('strong',item.title,card);text('p',copy.states[item.status]||item.status,card);if(item.note)text('p',item.note,card);text('a',copy.open,card).href=source.href;section.append(card);}if(!items.length)text('a',copy.open,section).href=source.href;}catch(error){status.textContent=error.status===401?copy.login:copy.error;if(error.status===401)text('a',copy.login,section).href=`/${locale}/account/?returnTo=${encodeURIComponent(location.pathname)}`;}}));button.disabled=false;});
 // Preserve previously shared guide anchors without duplicating the documents.
 const legacy={overview:'contributing',editor:'editor',github:'contributing',files:'files-and-images',licensing:'licensing',syntax:'metadata-schema',format:'metadata-schema'};
 const key=location.hash.slice(1).split('--')[0];if(legacy[key])location.replace(`/${locale}/docs/${legacy[key]}/`);
}
