import {state} from './accountStore.js';
const root=document.querySelector('[data-creator-center]');
if(root){
 const c=JSON.parse(root.dataset.copy),locale=root.dataset.locale,api=root.dataset.api,editorApi=root.dataset.editorApi;
 const create=(tag,value)=>{const e=document.createElement(tag);e.textContent=value||'';return e;};
 let generation=0,owner,active='all',controllers=[];
 const sources=[...root.querySelectorAll('[data-creator-source]')].map(section=>({section,type:section.dataset.creatorSource,cursor:null,loaded:false,busy:false}));
 const request=async(base,path,signal)=>{const response=await fetch(base.replace(/\/$/,'')+path,{credentials:'include',cache:'no-store',signal:AbortSignal.any([signal,AbortSignal.timeout(15000)])});if(!response.ok)throw Object.assign(Error(c.error),{status:response.status});return response.json();};
 function localDrafts(){const container=root.querySelector('[data-creator-drafts]');container.replaceChildren();try{for(let i=0;i<localStorage.length;i++){const key=localStorage.key(i),match=key?.match(/^kamitsubaki-(?:visual-editor(?:-pr-demo)?-v1|article-workbench-v1:([^:]+)):(zh|ja|en)$/);if(!match)continue;let draft;try{draft=JSON.parse(localStorage.getItem(key));}catch{continue;}if(!draft?.meta||!draft.blocks||!(draft.meta.title||draft.meta.name))continue;const article=key.startsWith('kamitsubaki-article-'),row=create('article');row.className='creator-record';row.append(create('strong',draft.meta.title||draft.meta.name),create('small',c.local));const link=create('a',c.continue);link.href=article?`/${match[2]}/articles/submit/?draft=${encodeURIComponent(match[1])}`:`/${match[2]}/contribute/editor/`;row.append(link);container.append(row);}}catch{}if(!container.children.length)container.append(create('p',c.emptyDrafts));}
 async function load(source,append=false){if(source.busy)return;source.busy=true;const current=generation,abort=new AbortController();controllers.push(abort);const {section,type}=source,status=section.querySelector('[data-source-status]'),items=section.querySelector('[data-source-items]'),more=section.querySelector('[data-source-more]'),retry=section.querySelector('[data-source-retry]');status.textContent=c.loading;retry.hidden=true;more.disabled=true;
 try{let rows,data,cursor;if(type==='entry'){const session=await request(editorApi,'/api/editor/session',abort.signal);const params=new URLSearchParams({accountId:session.account.id});if(append&&source.cursor){params.set('before',source.cursor.before);params.set('beforeId',source.cursor.id);}data=await request(editorApi,'/api/editor/submissions?'+params,abort.signal);rows=data.submissions.map(x=>({title:x.title||x.path,status:x.status||x.sync,date:x.updated,href:`/${locale}/contribute/editor/?view=submissions&submission=${encodeURIComponent(x.id)}`}));cursor=data.nextBefore?{before:data.nextBefore,id:data.nextId}:null;}else{data=await request(api,(type==='article'?'/api/articles/mine':'/api/gallery/mine')+'?offset='+(append?source.cursor||0:0),abort.signal);rows=(data.revisions||data.records).map(x=>({title:x.content?.title||x.metadata?.title||x.metadata?.character||x.metadata?.sets?.[0]?.metadata?.title||'上传批次',status:x.partial?'部分通过':x.status,date:x.updated_at||x.created_at,note:x.review_note,href:type==='article'?`/${x.locale||locale}/articles/submit/?revision=${encodeURIComponent(x.id)}`:x.kind==='batch'?`/${locale}/gallery/manage/?batch=${encodeURIComponent(x.id)}`:x.kind==='set'?`/${locale}/account/creator/?revision=${encodeURIComponent(x.id)}`:`/${locale}/gallery/manage/legacy/` ,images:x.images}));cursor=data.nextOffset;}
 if(current!==generation)return;source.cursor=cursor;if(!append)items.replaceChildren();for(const x of rows){const row=create('article');row.className='creator-record';row.append(create('strong',x.title),create('span',c.states[x.status]||x.status),create('small',x.date));const link=create('a',c.open);link.href=x.href;row.append(link);if(x.note)row.append(create('p',x.note));if(x.images?.length)row.append(create('small',`${x.images.length} 张图片 · ${x.images.filter(i=>i.published).length} 张已公开 · ${x.images.filter(i=>i.status==='rejected').length} 张退回，进入记录查看逐图结果。`));items.append(row);}status.textContent=items.children.length?'':c.empty;more.hidden=source.cursor===null;source.loaded=true;
 }catch(error){if(current!==generation||abort.signal.aborted)return;status.textContent=error.status===401?c.login:c.error;if(error.status===401){const link=create('a',c.login);link.href=`/${locale}/account/?returnTo=${encodeURIComponent(location.pathname)}`;status.append(' · ',link);}else retry.hidden=false;}finally{if(current===generation){source.busy=false;more.disabled=false;}}}
 function refresh(){root.querySelector('[data-creator-detail]')?.remove();generation++;controllers.forEach(c=>c.abort());controllers=[];for(const source of sources){source.busy=false;source.loaded=false;source.cursor=null;source.section.querySelector('[data-source-items]').replaceChildren();source.section.querySelector('[data-source-more]').hidden=true;if(active==='all'||active===source.type)void load(source);}}
 for(const source of sources){source.section.querySelector('[data-source-more]').onclick=()=>void load(source,true);source.section.querySelector('[data-source-retry]').onclick=()=>void load(source);}
 root.querySelector('[data-creator-refresh]').onclick=refresh;root.querySelectorAll('[data-creator-type]').forEach(button=>button.addEventListener('click',()=>{active=button.dataset.creatorType;root.querySelectorAll('[data-creator-type]').forEach(b=>b.setAttribute('aria-pressed',String(b===button)));for(const source of sources){source.section.hidden=active!=='all'&&active!==source.type;if(!source.section.hidden&&!source.loaded)void load(source);}}));
 window.addEventListener('kamitsubaki-account-state',()=>{const next=state.viewer?.userId||null;if(next!==owner){owner=next;refresh();}});owner=state.viewer?.userId||null;localDrafts();refresh();void showRevision();
 async function showRevision(){const capturedOwner=state.viewer?.userId;const id=new URLSearchParams(location.search).get('revision');if(!id)return;try{const abort=new AbortController();const data=await request(api,'/api/gallery/set-revisions/'+encodeURIComponent(id),abort.signal);if(capturedOwner!==state.viewer?.userId)return;const section=create('section');section.className='creator-source';section.dataset.creatorDetail='';section.append(create('h2',data.revision.metadata.title||data.revision.metadata.character),create('p',data.revision.review_note||c.states[data.revision.status]||data.revision.status));for(const image of data.images){const row=create('article');row.className='creator-record';const img=document.createElement('img');img.src=image.previewUrl;img.alt=image.metadata.title||image.metadata.name||'';img.width=100;img.height=100;img.style.objectFit='contain';row.append(img,create('strong',image.metadata.title||image.metadata.name),create('span',(c.states[image.status]||image.status)+(image.published?' · 已公开':'')),create('p',image.review_note));section.append(row);}if(data.revision.status!=='pending'&&data.images.every(i=>i.status!=='pending')){const link=create('a','修改资料 / 重新提交');link.href=`/${locale}/gallery/manage/?revision=${encodeURIComponent(id)}`;section.append(link);}root.prepend(section);}catch{}}
}
