import {state,refreshAuth} from './accountStore.js';

const root=document.querySelector('[data-creator-center]');
if(root){
 const $=selector=>root.querySelector(selector),c=JSON.parse(root.dataset.copy),locale=root.dataset.locale;
 const api=root.dataset.api.replace(/\/$/,''),editorApi=root.dataset.editorApi.replace(/\/$/,'');
 const text=(tag,value,className)=>{const node=document.createElement(tag);node.textContent=String(value??'');if(className)node.className=className;return node;};
 let owner=null,ownerGeneration=0,listGeneration=0,items=[],notifications=[],unreadCount=0,nextOffset=null,detailTrigger=null,openedFromList=false,searchTimer;
 const request=async(base,path,method='GET',body)=>{
  const response=await fetch(base+path,{method,credentials:'include',cache:'no-store',signal:AbortSignal.timeout(15000),headers:body?{'Content-Type':'application/json'}:{},body:body?JSON.stringify(body):undefined});
  const data=await response.json().catch(()=>({}));if(!response.ok)throw Object.assign(Error(data.error?.message||data.error?.code||c.error),{status:response.status});return data;
 };
 const account=(path,method,body)=>request(api,'/api/account'+path,method,body);
 const params=()=>new URLSearchParams(location.search);
 const normalizeLegacy=()=>{const p=params();if(p.has('batch')){p.set('recordType','gallery');p.set('record',p.get('batch'));p.delete('batch');history.replaceState(history.state,'',location.pathname+'?'+p);}else if(p.has('revision')){p.set('recordType','gallery');p.set('record',p.get('revision'));p.delete('revision');history.replaceState(history.state,'',location.pathname+'?'+p);}};
 const filters=()=>{const p=params();return {q:p.get('q')||'',type:p.get('type')||'',state:p.get('state')||'',offset:Math.max(0,Number(p.get('offset'))||0)};};
 const setUrl=(changes,replace=false)=>{const url=new URL(location.href);for(const [key,value]of Object.entries(changes)){if(value===null||value===''||value===0)url.searchParams.delete(key);else url.searchParams.set(key,String(value));}(replace?history.replaceState:history.pushState).call(history,{creatorScroll:window.scrollY},'',url);};
 const returnTo=()=>location.pathname+location.search;
 const withReturn=href=>{const url=new URL(href,location.origin);url.searchParams.set('returnTo',returnTo());return url.pathname+url.search;};
 const typeName=type=>c[type]||type;
 const stateName=row=>row.state==='review'&&row.type==='entry'&&row.raw_status==='merged'?c.syncing:row.state==='attention'&&row.type==='gallery'&&row.raw_status==='approved'?c.partial:c.status[row.state]||row.raw_status;
 const openButton=(row,label=c.open)=>{const button=text('button',label);button.type='button';button.onclick=()=>openRecord(row.type,row.id,button);return button;};
 function renderRows(){const tbody=$('[data-creator-rows]');tbody.replaceChildren();for(const row of items){const tr=document.createElement('tr');const title=text('td',row.title);const kind=text('td',typeName(row.type));const status=document.createElement('td'),pill=text('span',stateName(row),'creator-state');pill.dataset.state=row.state;status.append(pill);const date=text('td',(row.updated_at||'').slice(0,16));const action=document.createElement('td');action.append(openButton(row));tr.append(title,kind,status,date,action);tbody.append(tr);}if(!items.length){const tr=document.createElement('tr'),td=text('td',c.empty);td.colSpan=5;tr.append(td);tbody.append(tr);}const f=filters();$('[data-page-previous]').disabled=f.offset===0;$('[data-page-next]').disabled=nextOffset===null;$('[data-records-status]').textContent=items.length?`${f.offset+1}–${f.offset+items.length}`:c.empty;}
 async function loadRows(){const current=++listGeneration,f=filters(),query=new URLSearchParams({offset:String(f.offset)});if(f.q)query.set('q',f.q);if(f.type)query.set('type',f.type);if(f.state)query.set('state',f.state);if(!owner){items=[];nextOffset=null;renderRows();$('[data-creator-status]').textContent='';$('[data-records-status]').textContent=c.loginHint;return;}$('[data-records-status]').textContent=c.loading;try{const data=await account('/contributions?'+query);if(current!==listGeneration)return;items=data.items;nextOffset=data.nextOffset;renderRows();$('[data-creator-status]').textContent='';}catch(error){if(current!==listGeneration)return;items=[];nextOffset=null;renderRows();$('[data-creator-status]').textContent=error.status===401?c.login:c.error;}}
 function renderTodo(rows){const target=$('[data-creator-todo]');target.replaceChildren();$('[data-todo-count]').textContent=rows.length?String(rows.length):'';if(!rows.length){target.append(text('p',owner?c.todoEmpty:c.loginHint));return;}for(const row of rows.slice(0,5)){const item=text('div','','creator-todo-row');item.append(text('strong',row.title),openButton(row,c.open));if(row.note)item.append(text('p',row.note));target.append(item);}}
 async function loadSummary(){const current=ownerGeneration;if(!owner){for(const key of ['attention','review','published','draft'])$(`[data-metric-count="${key}"]`).textContent='—';renderTodo([]);return;}try{const [summary,todo]=await Promise.all([account('/contributions/summary'),account('/contributions?state=attention')]);if(current!==ownerGeneration)return;for(const key of ['attention','review','published','draft'])$(`[data-metric-count="${key}"]`).textContent=summary.summary[key]??0;renderTodo(todo.items);}catch{if(current===ownerGeneration)$('[data-creator-todo]').replaceChildren(text('p',c.error));}}
 function renderNotifications(data){notifications=data.items||[];unreadCount=data.unread||0;const target=$('[data-creator-notifications]');target.replaceChildren();$('[data-notification-count]').textContent=unreadCount?`${unreadCount} ${c.unread}`:'';root.querySelectorAll('[data-creator-unread]').forEach(badge=>{badge.hidden=!unreadCount;badge.textContent=unreadCount||'';});if(!notifications.length){target.append(text('p',owner?c.noNotifications:c.loginHint));return;}for(const event of notifications){const row=text('div','','creator-notification-row');row.dataset.unread=String(!event.read_at);const content=document.createElement('div');content.append(text('strong',c.events[event.event_type]||event.event_type),text('small',' · '+(event.created_at||'').slice(0,16)));const button=text('button',c.open);button.type='button';button.onclick=()=>openRecord(event.source_type,event.record_id,button);row.append(content,button);target.append(row);}}
 async function loadNotifications(){if(!owner){renderNotifications({items:[],unread:0});return;}try{renderNotifications(await account('/notifications'));}catch{$('[data-creator-notifications]').replaceChildren(text('p',c.error));}}
 function localDrafts(){const target=$('[data-creator-drafts]');target.replaceChildren();if(!owner){target.append(text('p',c.login));return;}let found=0;try{for(let i=0;i<localStorage.length;i++){const key=localStorage.key(i),match=key?.match(/^kamitsubaki-(?:visual-editor(?:-pr-demo)?-v1|article-workbench-v1:([^:]+)):(zh|ja|en)$/);if(!match)continue;const draft=JSON.parse(localStorage.getItem(key)||'null');if(draft?.ownerId!==owner||!draft.meta||!draft.blocks||!(draft.meta.title||draft.meta.name))continue;const isArticle=key.startsWith('kamitsubaki-article-'),row=text('div','','creator-local-row'),href=isArticle?`/${match[2]}/articles/submit/?draft=${encodeURIComponent(match[1])}`:`/${match[2]}/contribute/editor/`;row.append(text('strong',draft.meta.title||draft.meta.name));const link=text('a',c.continue);link.href=withReturn(href);row.append(link);target.append(row);found++;}}catch{}if(!found)target.append(text('p',c.todoEmpty));}
 function addDetailAction(parent,label,href,secondary=false){const link=text('a',label,`creator-detail-action${secondary?' secondary':''}`);link.href=withReturn(href);parent.append(link);}
 function addImages(parent,images){if(!images?.length)return;parent.append(text('h3',c.images));for(const item of images){const row=text('div','','creator-detail-image');if(item.previewUrl){const img=document.createElement('img');img.src=item.previewUrl;img.alt=item.metadata?.title||'';img.loading='lazy';row.append(img);}else row.append(text('span',''));const detail=document.createElement('div');detail.append(text('strong',item.metadata?.title||item.metadata?.name||item.id),text('small',[item.status,item.published?c.published:null,item.review_note].filter(Boolean).join(' · ')));row.append(detail);parent.append(row);}}
 async function detailData(type,id){if(type==='entry')return {kind:'entry',data:await request(editorApi,'/api/editor/submissions/'+encodeURIComponent(id))};if(type==='article')return {kind:'article',data:(await request(api,'/api/articles/revisions/'+encodeURIComponent(id))).revision};try{return {kind:'set',data:await request(api,'/api/gallery/set-revisions/'+encodeURIComponent(id))};}catch(error){if(error.status!==404)throw error;}try{return {kind:'batch',data:await request(api,'/api/gallery/batches/'+encodeURIComponent(id)+'/submissions')};}catch(error){if(error.status!==404)throw error;}return {kind:'legacy',data:(await request(api,'/api/gallery/revisions/'+encodeURIComponent(id))).revision};}
 function buildDetail(type,id,result){const target=$('[data-detail-content]');target.replaceChildren();const {kind,data}=result;let title='',status='',note='';const meta=text('p','','creator-detail-meta');if(kind==='entry'){title=data.title||data.path||id;status=data.status||data.sync;note=data.syncError||'';meta.append(text('span',`${typeName(type)} · ${status} · ${data.sync||''}`));if(data.commentCount)meta.append(text('span',`${data.commentCount} ${c.feedback}`));}else if(kind==='article'){title=data.content?.title||id;status=data.status;note=data.review_note;meta.append(text('span',`${typeName(type)} · ${status} · ${data.locale}`));}else if(kind==='set'){title=data.revision.metadata.title||data.revision.metadata.character||id;status=data.revision.status;note=data.revision.review_note;meta.append(text('span',`${typeName(type)} · ${status}`));}else if(kind==='batch'){title=data.revisions.map(r=>r.metadata.title||r.metadata.character).join(' / ')||c.newGallery;status=data.batch.status;meta.append(text('span',`${typeName(type)} · ${status} · ${data.revisions.length} ${c.gallery}`));}else{title=data.metadata.title||data.metadata.character||id;status=data.status;note=data.review_note;meta.append(text('span',`${typeName(type)} · ${status}`));}
  const h=text('h2',title);h.id='creator-detail-title';target.append(h,meta,text('p',`${c.recordId} · ${id}`));if(note){target.append(text('h3',c.feedback),text('p',note,'creator-detail-note'));}
  if(kind==='entry'){const comments=data.comments?.items||data.comments||[];if(Array.isArray(comments)&&comments.length){target.append(text('h3',c.feedback));for(const comment of comments.slice(-5))target.append(text('p',comment.body||comment.text||''));}addDetailAction(target,c.open,`/${locale}/contribute/editor/?view=submissions&submission=${encodeURIComponent(id)}`);}
  if(kind==='article'){if(status==='draft'||status==='rejected')addDetailAction(target,status==='rejected'?c.revise:c.continue,`/${data.locale||locale}/articles/submit/?revision=${encodeURIComponent(id)}&draft=${encodeURIComponent(id)}`);if(status==='approved')addDetailAction(target,c.viewPublic,`/${data.locale||locale}/articles/read/?id=${encodeURIComponent(data.article_id)}`,true);}
  if(kind==='set'){addImages(target,data.images);if(status!=='pending'&&!data.images?.some(image=>image.status==='pending'))addDetailAction(target,c.revise,`/${locale}/gallery/manage/?revision=${encodeURIComponent(id)}`);}
  if(kind==='batch'){for(const revision of data.revisions){const section=document.createElement('section');section.append(text('h3',revision.metadata.title||revision.metadata.character||revision.id),text('p',revision.review_note||revision.status));addImages(section,revision.images);target.append(section);}if(status==='draft')addDetailAction(target,c.continue,`/${locale}/gallery/manage/?batch=${encodeURIComponent(id)}`);}
  if(kind==='legacy'){if(data.previewUrl)addImages(target,[data]);if(status!=='pending')addDetailAction(target,c.revise,`/${locale}/gallery/manage/legacy/?revision=${encodeURIComponent(id)}`);}
  h.tabIndex=-1;h.focus({preventScroll:true});
 }
 async function markRecordRead(type,id){for(const event of notifications.filter(item=>item.source_type===type&&item.record_id===id&&!item.read_at)){try{await account('/notifications/'+encodeURIComponent(event.id)+'/read','POST',{accountId:owner});event.read_at=new Date().toISOString();unreadCount=Math.max(0,unreadCount-1);}catch{}}renderNotifications({items:notifications,unread:unreadCount});}
 const detailModal=()=>window.innerWidth<1250;
 function syncDetailPresentation(){const pane=$('[data-creator-detail]'),modal=!pane.hidden&&detailModal();pane.setAttribute('aria-modal',String(modal));$('[data-detail-backdrop]').hidden=!modal;document.documentElement.classList.toggle('creator-detail-open',modal);}
 async function showDetail(type,id){const pane=$('[data-creator-detail]');pane.hidden=false;syncDetailPresentation();$('[data-detail-content]').replaceChildren(text('p',c.loading));if(detailModal())$('[data-detail-close]').focus({preventScroll:true});const current=ownerGeneration;try{const data=await detailData(type,id);if(current!==ownerGeneration||params().get('record')!==id)return;buildDetail(type,id,data);await markRecordRead(type,id);}catch(error){if(current!==ownerGeneration||params().get('record')!==id)return;$('[data-detail-content]').replaceChildren(text('p',error.status===401?c.login:c.error));}}
 function openRecord(type,id,trigger){detailTrigger=trigger;openedFromList=true;setUrl({recordType:type,record:id,batch:null,revision:null});void showDetail(type,id);}
 function closeDetail(){const fromList=openedFromList;openedFromList=false;$('[data-creator-detail]').hidden=true;syncDetailPresentation();if(fromList)history.back();else{setUrl({recordType:null,record:null},true);route();}const target=detailTrigger?.isConnected?detailTrigger:$('#creator-records-title');if(target?.tagName==='H2')target.tabIndex=-1;target?.focus({preventScroll:true});detailTrigger=null;}
 function route(){normalizeLegacy();const p=params(),type=p.get('recordType'),id=p.get('record');if(owner&&type&&id&&['entry','article','gallery'].includes(type)){void showDetail(type,id);}else{$('[data-creator-detail]').hidden=true;syncDetailPresentation();}const f=filters(),form=$('[data-creator-filters]');form.elements.q.value=f.q;form.elements.type.value=f.type;form.elements.state.value=f.state;void loadRows();}
 $('[data-detail-close]').onclick=closeDetail;$('[data-detail-backdrop]').onclick=closeDetail;window.addEventListener('resize',syncDetailPresentation);document.addEventListener('keydown',event=>{const pane=$('[data-creator-detail]');if(pane.hidden)return;if(event.key==='Escape'){closeDetail();return;}if(event.key!=='Tab'||!detailModal())return;const focusable=Array.from(pane.querySelectorAll('a[href],button:not([disabled]),input:not([disabled]),select:not([disabled]),textarea:not([disabled]),[tabindex]:not([tabindex="-1"])')).filter(node=>node.getClientRects().length);if(!focusable.length)return;const first=focusable[0],last=focusable.at(-1);if(event.shiftKey&&document.activeElement===first){event.preventDefault();last.focus();}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first.focus();}});
 window.addEventListener('popstate',()=>{openedFromList=false;route();});
 $('[data-creator-filters]').addEventListener('submit',event=>event.preventDefault());
 $('[data-creator-filters]').addEventListener('input',event=>{if(event.target.name!=='q')return;clearTimeout(searchTimer);searchTimer=setTimeout(()=>{setUrl({q:event.target.value,offset:null,record:null,recordType:null});route();},240);});
 $('[data-creator-filters]').addEventListener('change',event=>{if(event.target.name==='q')return;const form=event.currentTarget;setUrl({type:form.elements.type.value,state:form.elements.state.value,offset:null,record:null,recordType:null});route();});
 $('[data-page-previous]').onclick=()=>{setUrl({offset:Math.max(0,filters().offset-20)});route();};
 $('[data-page-next]').onclick=()=>{if(nextOffset!==null){setUrl({offset:nextOffset});route();}};
 $('[data-creator-refresh]').onclick=()=>{route();void loadSummary();void loadNotifications();};
 root.querySelectorAll('[data-metric]').forEach(button=>button.onclick=()=>{setUrl({state:button.dataset.metric,offset:null,record:null,recordType:null});route();$('#creator-records-title').scrollIntoView({block:'start'});});
 function syncOwner(next){owner=next;ownerGeneration++;listGeneration++;items=[];notifications=[];unreadCount=0;$('[data-creator-guest]').hidden=Boolean(owner);root.querySelectorAll('.creator-section').forEach(section=>{section.hidden=!owner;});localDrafts();route();void loadSummary();void loadNotifications();}
 window.addEventListener('kamitsubaki-account-state',()=>{const next=state.viewer?.userId||null;if(next!==owner)syncOwner(next);});
 void refreshAuth().then(viewer=>{if((viewer?.userId||null)!==owner)syncOwner(viewer?.userId||null);else if(!owner)syncOwner(null);}).catch(()=>{$('[data-creator-status]').textContent=c.error;});
}
