import {formatBytes,uploadLimits} from '../lib/uploadPresentation.mjs';
const root=document.querySelector('[data-creation-prototype]');
if(root){
 const $=s=>root.querySelector(s),all=s=>[...root.querySelectorAll(s)];
 const text=(tag,value)=>{const e=document.createElement(tag);e.textContent=value;return e;};
 let active='set-1',serial=1,files=[],selectedFile=null,simulating=false;
 const status=message=>$('[data-upload-status]').textContent=message;
 const sets=()=>all('[data-set]');
 function index(){const nav=$('[data-set-index]');nav.replaceChildren();sets().forEach((set,i)=>{const name=set.querySelector('[name=title]').value||`设定 ${String(i+1).padStart(2,'0')}`,count=files.filter(f=>f.set===set.dataset.set).length,link=text('a',`${name} · ${count} 张`);link.href='#'+set.id;if(set.dataset.set===active)link.setAttribute('aria-current','location');link.onclick=()=>{active=set.dataset.set;index();};nav.append(link);set.querySelector('h3').textContent=name;set.querySelector('[data-set-photo-count]').textContent=`${count} 张`;});$('[data-upload-count]').textContent=`${files.length} 张图片 · ${sets().length} 套设定`;$('[data-simulate-upload]').disabled=!files.length||simulating;}

 function preview(item){selectedFile=item.id;$('[data-preview-image]').src=item.url;$('[data-preview-image]').hidden=false;$('[data-preview-empty]').hidden=true;$('[data-preview-name]').textContent=item.file.name;$('[data-preview-size]').textContent=formatBytes(item.file.size);$('[data-preview-resolution]').textContent=item.width?`${item.width} × ${item.height} px`:item.decodeError?'无法读取':'读取中…';$('[data-preview-format]').textContent=(item.file.type.split('/')[1]||'未知').toUpperCase();$('[data-preview-counter]').textContent=`${files.indexOf(item)+1} / ${files.length}`;$('[data-preview-open]').disabled=false;}
 function progress(item){const row=root.querySelector(`[data-file-id="${item.id}"]`);if(!row)return;row.querySelector('progress').value=item.progress||0;row.querySelector('[data-file-state]').textContent=item.decodeError?'无法解码图片，请移除此文件':item.state==='staged'?'演示 · 已暂存（未发送）':item.state==='saving'?'演示 · 正在校验并保存':item.state==='uploading'?`演示 · ${item.progress}% · ${formatBytes(item.file.size*item.progress/100)} / ${formatBytes(item.file.size)}`:'待上传 · '+formatBytes(item.file.size);}
 function render(){all('[data-image-list]').forEach(list=>list.replaceChildren());for(const set of sets()){const items=files.filter(f=>f.set===set.dataset.set);items.forEach((item,i)=>{
 const row=text('div','');row.className='creation-image-row';row.dataset.fileId=item.id;
 const thumb=text('button','');thumb.type='button';thumb.className='creation-image-thumbnail';thumb.setAttribute('aria-label',`预览 ${item.file.name}`);const img=new Image();img.src=item.url;img.alt=item.file.name;thumb.append(img);thumb.onclick=()=>preview(item);
 const data=text('div','');data.className='creation-image-data';data.append(text('strong',item.file.name),text('small',`${formatBytes(item.file.size)} · ${item.width?`${item.width} × ${item.height} px`:'正在读取尺寸'} · ${item.file.type.split('/')[1].toUpperCase()}`));
 const fields=text('div','');fields.className='creation-image-inputs';for(const [key,label]of [['title','图片标题'],['notes','独立说明'],['sourceUrl','独立来源（留空使用设定来源）']]){const field=text('label',label),input=document.createElement('input');input.type=key==='sourceUrl'?'url':'text';input.value=item[key]||'';input.oninput=()=>item[key]=input.value;field.append(input);fields.append(field);}data.append(fields);
 const tools=text('div','');tools.className='creation-image-tools';for(const [label,fn]of [[i===0?'封面':'设为封面',()=>{files=files.filter(f=>f!==item);files.unshift(item);render();}],['上移',()=>{const before=items[i-1];if(!before)return;const a=files.indexOf(item),b=files.indexOf(before);[files[a],files[b]]=[files[b],files[a]];render();}],['下移',()=>{const after=items[i+1];if(!after)return;const a=files.indexOf(item),b=files.indexOf(after);[files[a],files[b]]=[files[b],files[a]];render();}],['移除',()=>{if(simulating)return;files=files.filter(f=>f!==item);URL.revokeObjectURL(item.url);render();if(selectedFile===item.id){if(files.length)preview(files[0]);else{$('[data-preview-image]').hidden=true;$('[data-preview-empty]').hidden=false;$('[data-preview-open]').disabled=true;}}}]]){const button=text('button',label);button.type='button';button.onclick=fn;button.disabled=simulating||(label==='上移'&&i===0)||(label==='下移'&&i===items.length-1);if(label==='封面')button.setAttribute('aria-pressed','true');tools.append(button);}data.append(tools);const line=text('p','');line.dataset.fileState='';line.className='creation-image-state';const bar=document.createElement('progress');bar.max=100;bar.value=item.progress||0;bar.setAttribute('aria-label',`${item.file.name} 上传演示进度`);data.append(line,bar);row.append(thumb,data);set.querySelector('[data-image-list]').append(row);progress(item);
 });}index();}
 async function addFiles(list,setId=active){if(simulating)return;const messages=[];for(const file of list){if(files.length>=uploadLimits.batchFiles){messages.push('每批最多 100 张');break;}if(!['image/png','image/jpeg','image/webp','image/gif'].includes(file.type)){messages.push(`${file.name}：格式不支持`);continue;}if(file.size>uploadLimits.fileBytes){messages.push(`${file.name}：超过 20 MB`);continue;}const item={id:crypto.randomUUID(),set:setId,file,url:URL.createObjectURL(file),state:'queued',progress:0};files.push(item);const image=new Image();image.src=item.url;try{await image.decode();item.width=image.naturalWidth;item.height=image.naturalHeight;}catch{item.decodeError=true;}render();preview(item);}status(messages.length?messages.join('；'):'图片仅在本机预览，尚未上传。');}
 $('[data-demo-files]').onclick=async()=>{const button=$('[data-demo-files]');button.disabled=true;try{const examples=await Promise.all(['/images/albums/fate-vwp-1400x1400.jpg','/images/albums/koko/prayer.jpg'].map(async(path,i)=>{const response=await fetch(path);if(!response.ok)throw Error();return new File([await response.blob()],`界面示例-${i+1}.jpg`,{type:'image/jpeg'});}));await addFiles(examples);}catch{status('示例图片未能读取，请选择本地图片。');}finally{button.disabled=false;}};
 root.addEventListener('change',event=>{if(!event.target.matches('[data-file-picker]'))return;const set=event.target.closest('[data-set]');void addFiles([...event.target.files],set.dataset.set);event.target.value='';});
 root.addEventListener('click',event=>{const trigger=event.target.closest('[data-select-set]');if(trigger){active=trigger.dataset.selectSet;index();trigger.closest('[data-set]').querySelector('[data-file-picker]').click();}});
 root.addEventListener('input',event=>{if(event.target.matches('[name=title]'))index();});
 root.addEventListener('dragover',event=>{const zone=event.target.closest('[data-drop-set]');if(zone){event.preventDefault();zone.dataset.dragging='';}});root.addEventListener('dragleave',event=>event.target.closest('[data-drop-set]')?.removeAttribute('data-dragging'));root.addEventListener('drop',event=>{const zone=event.target.closest('[data-drop-set]');if(!zone)return;event.preventDefault();zone.removeAttribute('data-dragging');active=zone.dataset.dropSet;void addFiles([...event.dataTransfer.files],active);});
 root.addEventListener('paste',event=>{const set=event.target.closest('[data-set]');if(!set)return;const images=[...event.clipboardData.files].filter(f=>f.type.startsWith('image/'));if(images.length){event.preventDefault();void addFiles(images,set.dataset.set);}});
 $('[data-add-set]').onclick=()=>{if(simulating)return;serial++;const node=sets()[0].cloneNode(true);node.dataset.set=`set-${serial}`;node.id=`creation-set-${serial}`;node.querySelector('.creation-caption').textContent=`${String(serial).padStart(2,'0')} / SET`;node.querySelector('h3').textContent=`第 ${serial} 套设定`;node.querySelector('[data-image-list]').replaceChildren();node.querySelectorAll('[name]').forEach(e=>{e.value='';e.id=`set-${serial}-${e.name}`;e.closest('label')?.setAttribute('for',e.id);});node.querySelectorAll('[data-select-set]').forEach(e=>e.dataset.selectSet=node.dataset.set);node.querySelector('[data-drop-set]').dataset.dropSet=node.dataset.set;$('[data-set-container]').append(node);active=node.dataset.set;index();node.scrollIntoView({block:'start',behavior:matchMedia('(prefers-reduced-motion:reduce)').matches?'instant':'smooth'});};
 const dialog=$('[data-image-dialog]');$('[data-preview-open]').onclick=()=>{const item=files.find(f=>f.id===selectedFile);if(!item)return;$('[data-dialog-title]').textContent=item.file.name;$('[data-dialog-image]').src=item.url;dialog.showModal();};$('[data-dialog-close]').onclick=()=>dialog.close();
 $('[data-simulate-upload]').onclick=async()=>{if(simulating)return;if(files.some(f=>f.decodeError)){status('请先移除无法读取的图片');return;}simulating=true;render();status('演示进度：没有文件发送到服务器。真实上传将以传输字节和服务端响应为准。');let next=0;const worker=async()=>{while(next<files.length){const item=files[next++];item.state='uploading';for(let n=0;n<=100;n+=20){item.progress=n;item.state=n===100?'saving':'uploading';progress(item);$('[data-total-progress]').value=files.reduce((sum,f)=>sum+f.progress,0)/files.length;await new Promise(r=>setTimeout(r,180));}item.state='staged';progress(item);}};await Promise.all(Array.from({length:Math.min(uploadLimits.concurrency,files.length)},worker));simulating=false;render();status('演示完成。未上传、未创建投稿；实际提交会在后端联调后接入。');};
 const assets=['/images/albums/fate-vwp-1400x1400.jpg','/images/albums/koko/prayer.jpg'];
 const samples={gallery:[{title:'演示设定 · 舞台服装',note:'示例投稿者 · 新建 · 2 张图片',before:'尚未公开 · 新设定',after:'角色：演示角色\n设定名称：舞台服装\n图片：正面与补充图\n来源：示例来源（非真实投稿）'},{title:'演示设定 · 资料补充',note:'示例投稿者 · 修改资料 · 2 张图片',before:'来源名称未填写',after:'补充来源名称与图片说明'}],article:[{title:'演示文章 · 创作记录',note:'示例作者 · 修改 · 待审核',before:'本文介绍相关作品。',after:'本文介绍相关作品，并补充制作过程与资料来源。'}],entry:[{title:'演示词条 · 资料整理',note:'示例贡献者 · GitHub 审核流程',before:'原词条资料摘要',after:'新增资料来源与明确的关联字段。\n正文变更在此逐项对照，最终合并仍在 GitHub 完成。'}]};
 let reviewType='gallery',reviewIndex=0,imageIndex=0,imageStates=['待审核','待审核'];
 function review(){const list=$('[data-review-queue]');list.replaceChildren();const q=$('[data-review-search]').value; samples[reviewType].forEach((sample,i)=>{if(q&&!sample.title.includes(q))return;const b=text('button','');b.type='button';b.setAttribute('aria-pressed',String(i===reviewIndex));b.append(text('strong',sample.title),text('small',sample.note));b.onclick=()=>{reviewIndex=i;imageStates=['待审核','待审核'];review();};list.append(b);});const current=samples[reviewType][reviewIndex];$('[data-review-title]').textContent=current.title;$('[data-review-description]').textContent=current.note;$('[data-review-meta]').textContent=reviewType==='gallery'?'VISUAL ARCHIVE / DEMO':reviewType==='article'?'ARTICLE / DEMO':'ENTRY / DEMO';$('[data-review-before]').textContent=current.before;$('[data-review-after]').textContent=current.after;$('[data-review-gallery]').hidden=reviewType!=='gallery';$('[data-shared-review]').hidden=reviewType!=='gallery';$('[data-review-scope]').closest('label').hidden=reviewType!=='gallery';$('[data-review-help]').textContent=reviewType==='gallery'?'图片支持逐张处理；公共资料通过后，已通过图片才可公开。':reviewType==='entry'?'展示正文差异与审核意见；沿用 GitHub 审核和合并。':'核对正文、来源与关联词条，再通过或退回。';$('[data-review-status]').textContent='';all('[data-review-image-status]').forEach(e=>e.textContent=imageStates[Number(e.dataset.reviewImageStatus)]);}
 all('[data-review-image]').forEach(b=>b.onclick=()=>{imageIndex=Number(b.dataset.reviewImage);all('[data-review-image]').forEach(e=>e.setAttribute('aria-pressed',String(e===b)));$('[data-review-large]').src=assets[imageIndex];});
 $('[data-review-type]').onchange=event=>{reviewType=event.target.value;reviewIndex=0;review();};$('[data-review-search]').oninput=review;
 function decide(approved){const note=$('[data-review-note]');if(!approved&&!note.value.trim()){$('[data-review-status]').textContent='退回需要填写修改意见。';note.focus();return;}if(reviewType==='gallery'){const scope=$('[data-review-scope]').value;imageStates=imageStates.map((state,i)=>scope==='all'||i===imageIndex?(approved?'已通过':'已退回'):state);all('[data-review-image-status]').forEach(e=>e.textContent=imageStates[Number(e.dataset.reviewImageStatus)]);const accepted=imageStates.filter(s=>s==='已通过').length;$('[data-review-status]').textContent=`演示：${accepted}/2 张通过。`+(accepted&&!$('[data-approve-metadata]').checked?'公共资料仍待审核，尚不可公开。':accepted===1?'部分通过，其他图片可继续处理。':'');}else $('[data-review-status]').textContent=reviewType==='entry'?'演示：意见已记录，实际词条合并仍在 GitHub 完成。':approved?'演示：文章通过。':'演示：文章退回修改。';}
 $('[data-review-approve]').onclick=()=>decide(true);$('[data-review-reject]').onclick=()=>decide(false);
 all('[data-creation-mode]').forEach(button=>button.onclick=()=>{all('[data-creation-mode]').forEach(b=>b.setAttribute('aria-pressed',String(b===button)));$('[data-creation-upload]').hidden=button.dataset.creationMode!=='upload';$('[data-creation-review]').hidden=button.dataset.creationMode!=='review';});
 window.addEventListener('pagehide',()=>{files.forEach(f=>URL.revokeObjectURL(f.url));});index();review();
}
