import {formatBytes,uploadLimits,uploadFile} from '../lib/uploadPresentation.mjs';
import {showContributionReceipt} from '../lib/submissionReceipt.mjs';
import {galleryQueueSummary} from '../lib/galleryQueue.mjs';
import {imageViewer} from '../lib/imageViewer.mjs';
import {galleryDraft} from '../lib/galleryDraftStore.mjs';
import {state,refreshAuth} from './accountStore.js';
const root=document.querySelector('[data-creation-uploader]');
if(root){
 const $=s=>root.querySelector(s),all=s=>[...root.querySelectorAll(s)];
 const text=(tag,value)=>{const e=document.createElement(tag);e.textContent=value;return e;};
 let active='set-1',serial=1,files=[],selectedFile=null,simulating=false,owner=null,batch=null,saveTimer,hydrating=false,dirty=false,disposed=false,characters=[];
 const formCache=new Map();
 const api=document.querySelector('[data-gallery-api]').dataset.galleryApi.replace(/\/$/,'');
 const admin=new URLSearchParams(location.search).get('admin')==='1';
 const controller=new AbortController();
 const locale=document.documentElement.lang.startsWith('zh')?'zh':document.documentElement.lang;
 if(admin){
  const page=document.querySelector('.gallery-manage-shell');
  const intro=document.querySelector('.gallery-manage-shell .workspace-heading p:last-child');
  if(intro)intro.textContent=page?.dataset.adminIntro||intro.textContent;
  const back=document.querySelector('.gallery-manage-shell .workspace-back');
  if(back){back.href=api+'/admin/content?type=gallery';back.querySelector('span:last-child').textContent=locale==='en'?'Content management':locale==='ja'?'コンテンツ管理':'内容管理';}
 }
 const flowText=({zh:{submitted:'设定与图片已提交审核，公开前可在创作者中心查看逐图结果。'},ja:{submitted:'設定と画像を審査に提出しました。結果はクリエイターセンターで確認できます。'},en:{submitted:'Sets and images submitted for review. Track each image in the creator center.'}})[locale]||({zh:{submitted:'设定与图片已提交审核，公开前可在创作者中心查看逐图结果。'}}).zh;
 const returnTo=new URLSearchParams(location.search).get('returnTo');
 const batchUrl=id=>{const url=new URL(location.pathname,location.origin);url.searchParams.set('batch',id);if(returnTo)url.searchParams.set('returnTo',returnTo);if(admin)url.searchParams.set('admin','1');return url.pathname+url.search;};
 const receipt=id=>{showContributionReceipt(root,{id,state:admin?'设定已公开，可从内容管理查看。':flowText.submitted,href:admin?api+'/admin/content?type=gallery':`/${locale}/account/creator/?recordType=gallery&record=${encodeURIComponent(id)}`,...(admin?{title:'发布完成',recordLabel:'批次编号',linkLabel:'查看内容管理'}:{})});root.dataset.complete='';};
 if(returnTo){try{const target=new URL(returnTo,location.origin);if(target.origin===location.origin&&/^\/(zh|ja|en)\/account\/creator\/$/.test(target.pathname)){const back=document.querySelector('.gallery-manage-shell .workspace-back');if(back){back.href=target.pathname+target.search;back.textContent='← '+(locale==='en'?'Creator center':locale==='ja'?'クリエイターセンター':'创作者中心');}}}catch{}}
 const template=$('[data-set]').cloneNode(true);
 const metadata=set=>Object.fromEntries([...set.querySelectorAll('[name]')].map(input=>[input.name,input.name==='tags'?input.value.split(/[,，]/).map(x=>x.trim()).filter(Boolean):input.value]));
 const manifest=()=>({sets:sets().map(set=>({id:set.dataset.set,setId:set.dataset.existing||null,baseVersion:Number(set.dataset.version)||0,metadata:metadata(set),images:files.filter(f=>f.set===set.dataset.set).map(f=>({fileId:f.id,metadata:Object.fromEntries(['title','notes','sourceUrl','sourceTitle','author','rightsBasis','rightsEvidence'].filter(k=>f[k]).map(k=>[k,f[k]]))}))}))});
 const request=async(path,body,method=body?'POST':'GET')=>{const url=new URL(api+'/api/gallery'+path);if(owner)url.searchParams.set('accountId',owner);const response=await fetch(url,{method,credentials:'include',signal:controller.signal,headers:body?{'Content-Type':'application/json'}:{},body:body?JSON.stringify(body):undefined});const data=await response.json();if(!response.ok)throw Object.assign(Error(data.error?.message||'服务异常'),{status:response.status});if(disposed)throw Error('账号已切换');return data;};
 const adminRequest=async(path,body)=>{const response=await fetch(api+'/api/admin/gallery'+path,{method:body?'POST':'GET',credentials:'include',signal:controller.signal,headers:body?{'Content-Type':'application/json'}:{},body:body?JSON.stringify(body):undefined});const data=await response.json();if(!response.ok)throw Object.assign(Error(data.error?.message||'管理员权限或服务不可用'),{status:response.status});return data;};
 async function persist(){if(!owner||hydrating||disposed)return;const draft={id:batch?.id,version:batch?.version,manifest:manifest(),files:files.map(({url,...f})=>({...f,state:f.state==='staged'?'staged':'queued'}))};try{await galleryDraft('put',owner,draft);dirty=false;}catch{try{await galleryDraft('put',owner,{...draft,files:draft.files.map(({file,...f})=>({...f,fileInfo:{name:file.name,size:file.size,type:file.type}}))});}catch{}dirty=true;status('本机空间不足：文件未备份。已暂存文件可恢复，其他文件请勿关闭页面。');}}
 function changed(){if(hydrating||disposed)return;dirty=true;clearTimeout(saveTimer);saveTimer=setTimeout(()=>void persist(),500);}
 async function saveRemote(){if(!batch){batch=(await request('/batches',{id:crypto.randomUUID()})).batch;history.replaceState(null,'',batchUrl(batch.id));}const result=await request('/batches/'+batch.id,{version:batch.version,manifest:manifest()},'PUT');batch=result.batch;await persist();}

 const status=message=>$('[data-upload-status]').textContent=message;
 const sets=()=>all('[data-set]');
 const setName=(set,i)=>set.querySelector('[name=title]').value.trim()||`设定 ${String(i+1).padStart(2,'0')}`;
 function queueState(){return galleryQueueSummary(sets().map((set,i)=>({id:set.dataset.set,title:setName(set,i),character:set.querySelector('[name=character]').value})),files);}
 function index(){
  const nav=$('[data-set-index]');nav.replaceChildren();
  sets().forEach((set,i)=>{const name=setName(set,i),count=files.filter(f=>f.set===set.dataset.set).length,link=text('a',`${name} · ${count} 张`);link.href='#'+set.id;set.dataset.active=String(set.dataset.set===active);if(set.dataset.set===active)link.setAttribute('aria-current','location');link.onclick=()=>{active=set.dataset.set;index();};nav.append(link);set.querySelector('[data-remove-set]').disabled=sets().length===1||count>0||simulating;set.querySelector('[data-remove-set]').title=count?'先移除本组照片，再删除空设定':'';set.querySelector('[data-set-photo-count]').textContent=`${count} 张`;set.querySelectorAll('[data-select-set],[data-file-picker]').forEach(button=>button.disabled=!owner||simulating||disposed);set.querySelector('h3').textContent=name;set.querySelector('.creation-caption').textContent=`${String(i+1).padStart(2,'0')} / SET`;const role=characters.find(value=>value.id===set.querySelector('[name=character]').value),form=set.querySelector('[name=form]').value.trim();set.querySelector('[data-set-destination]').textContent=role?`${role.labels?.[locale]||role.name} / ${form||'未分类'} · ${count} 张图片将作为一套设定展示`:'选择角色后，这套设定会归入该角色的图库。';});
  const summary=queueState();$('[data-add-set]').disabled=simulating||disposed;
  $('[data-total-progress]').value=files.length?files.reduce((total,file)=>total+(file.progress||0),0)/files.length:0;
  $('[data-upload-count]').textContent=`${summary.total} 张 · ${sets().length} 套设定 · 已暂存 ${summary.staged} 张${summary.failed?` · 失败 ${summary.failed} 张`:''}`;
  const upload=$('[data-simulate-upload]'),submit=$('[data-submit-batch]');upload.disabled=!owner||!summary.total||!summary.pending||simulating||disposed;submit.disabled=!owner||!summary.ready||simulating||disposed;
  if(admin)submit.textContent='发布全部设定';
  upload.textContent=simulating?'处理中…':summary.total&&!summary.pending?'图片已暂存':summary.failed?`重试未完成照片（${summary.pending}）`:`上传全部照片${summary.pending?`（${summary.pending}）`:''}`;
  upload.dataset.tone=summary.ready?'secondary':'primary';submit.dataset.tone=summary.ready?'primary':'secondary';
  const issues=$('[data-upload-issues]');issues.replaceChildren();for(const issue of summary.issues){const li=text('li',''),button=text('button',issue.message);button.type='button';button.onclick=()=>{const set=sets().find(s=>s.dataset.set===issue.set);set?.scrollIntoView({block:'center',behavior:'smooth'});set?.querySelector(issue.field==='character'?'[name=character]':'[data-select-set]')?.focus({preventScroll:true});};li.append(button);issues.append(li);}issues.hidden=!summary.total||!summary.issues.length;
 }
 function roleOptions(set,query=''){const select=set.querySelector('[name=character]'),value=select.value;select.replaceChildren(new Option('请选择角色',''));for(const role of characters){if(role.id!==value&&query&&!`${role.name} ${role.id}`.toLowerCase().includes(query.toLowerCase()))continue;select.add(new Option(role.name,role.id));}select.value=value;}
 async function formOptions(set){const role=set.querySelector('[name=character]').value,list=set.querySelector('[data-form-options]');if(!list)return;list.replaceChildren();if(!role)return;try{if(!formCache.has(role)){const data=await request('/sets/facets?character='+encodeURIComponent(role));formCache.set(role,[...new Set(data.facets.map(row=>row.form).filter(Boolean))]);}if(!set.isConnected||set.querySelector('[name=character]').value!==role)return;for(const form of formCache.get(role))list.append(new Option(form,form));}catch{/* A new form remains editable even when suggestions cannot load. */}}
 function preview(item){selectedFile=item.id;$('[data-preview-image]').src=item.url;$('[data-preview-image]').hidden=false;$('[data-preview-empty]').hidden=true;$('[data-preview-name]').textContent=item.file.name;$('[data-preview-size]').textContent=formatBytes(item.file.size);$('[data-preview-resolution]').textContent=item.width?`${item.width} × ${item.height} px`:item.decodeError?'无法读取':'读取中…';$('[data-preview-format]').textContent=(item.file.type.split('/')[1]||'未知').toUpperCase();const group=files.filter(f=>f.set===item.set),set=sets().find(s=>s.dataset.set===item.set);$('[data-preview-counter]').textContent=`本组 ${group.indexOf(item)+1} / ${group.length}`;$('[data-preview-set]').textContent=setName(set,sets().indexOf(set));$('[data-preview-open]').disabled=false;}
 function progress(item){const row=root.querySelector(`[data-file-id="${item.id}"]`);if(!row)return;const bar=row.querySelector('progress');if(item.state==='uploading'&&item.progress===null)bar.removeAttribute('value');else bar.value=item.progress||0;row.querySelector('[data-file-state]').textContent=item.error|| (item.decodeError?'无法解码图片，请移除此文件':item.state==='staged'?(admin?'已暂存 · 尚未发布':'已暂存 · 尚未提交审核'):item.state==='saving'?'正在校验并保存':item.state==='uploading'?`${item.progress??'…'}% · ${formatBytes(item.loaded)} / ${formatBytes(item.total)}`:'待上传 · '+formatBytes(item.file.size));}
 function render(){all('[data-image-list]').forEach(list=>list.replaceChildren());for(const set of sets()){const items=files.filter(f=>f.set===set.dataset.set);items.forEach((item,i)=>{
 const row=text('div','');row.className='creation-image-row';row.dataset.fileId=item.id;
 const thumb=text('button','');thumb.type='button';thumb.className='creation-image-thumbnail';thumb.setAttribute('aria-label',`预览 ${item.file.name}`);const img=new Image();img.src=item.url;img.alt=item.file.name;thumb.append(img);thumb.onclick=()=>preview(item);
 const data=text('div','');data.className='creation-image-data';data.append(text('strong',item.file.name),text('small',`${formatBytes(item.file.size)} · ${item.width?`${item.width} × ${item.height} px`:'正在读取尺寸'} · ${item.file.type.split('/')[1].toUpperCase()}`));
 const fields=text('div','');fields.className='creation-image-inputs';for(const [key,label]of [['title','图片标题'],['notes','独立说明'],['sourceUrl','独立来源（留空使用设定来源）']]){const field=text('label',label),input=document.createElement('input');input.type=key==='sourceUrl'?'url':'text';input.value=item[key]||'';input.placeholder=key==='sourceUrl'?'使用本套来源':key==='title'?'使用设定名称':'只补充这张图的说明';input.oninput=()=>{item[key]=input.value;changed();};field.append(input);fields.append(field);}data.append(fields);
 const rights=document.createElement('details');rights.className='creation-photo-rights';rights.append(text('summary','此图作者或使用依据不同？'));const rightsFields=text('div','');rightsFields.className='creation-image-inputs';for(const [key,label]of [['author','独立作者'],['sourceTitle','独立出处名称'],['rightsEvidence','授权说明']]){const field=text('label',label),input=document.createElement('input');input.type='text';input.value=item[key]||'';input.oninput=()=>{item[key]=input.value;changed();};field.append(input);rightsFields.append(field);}const basis=text('label','独立使用依据'),basisSelect=document.createElement('select');for(const [value,label]of [['','使用本组依据'],['official','官方公开素材'],['original','投稿者原创'],['authorized','已获授权']])basisSelect.append(new Option(label,value));basisSelect.value=item.rightsBasis||'';basisSelect.onchange=()=>{item.rightsBasis=basisSelect.value;changed();};basis.append(basisSelect);rightsFields.append(basis);rights.append(rightsFields);data.append(rights);
 const tools=text('div','');tools.className='creation-image-tools';for(const [label,fn]of [[i===0?'封面':'设为封面',()=>{files=files.filter(f=>f!==item);files.unshift(item);render();}],['上移',()=>{const before=items[i-1];if(!before)return;const a=files.indexOf(item),b=files.indexOf(before);[files[a],files[b]]=[files[b],files[a]];render();}],['下移',()=>{const after=items[i+1];if(!after)return;const a=files.indexOf(item),b=files.indexOf(after);[files[a],files[b]]=[files[b],files[a]];render();}],['移除',()=>{if(simulating)return;files=files.filter(f=>f!==item);URL.revokeObjectURL(item.url);render();if(selectedFile===item.id){if(files.length)preview(files[0]);else{selectedFile=null;$('[data-preview-set]').textContent='点击本组照片查看预览';$('[data-preview-counter]').textContent='—';$('[data-preview-image]').hidden=true;$('[data-preview-empty]').hidden=false;$('[data-preview-open]').disabled=true;}}}]]){const button=text('button',label);button.type='button';button.onclick=fn;button.disabled=simulating||(label==='上移'&&i===0)||(label==='下移'&&i===items.length-1);if(label==='封面')button.setAttribute('aria-pressed','true');tools.append(button);}if(item.state==='failed'){const retry=text('button','重试此图');retry.type='button';retry.onclick=async()=>{if(simulating||!batch)return;simulating=true;index();try{await uploadOne(item);}finally{simulating=false;render();}};tools.append(retry);}data.append(tools);const line=text('p','');line.dataset.fileState='';line.className='creation-image-state';const bar=document.createElement('progress');bar.max=100;bar.value=item.progress||0;bar.setAttribute('aria-label',`${item.file.name} 上传进度`);data.append(line,bar);row.append(thumb,data);set.querySelector('[data-image-list]').append(row);progress(item);
 });}index();changed();}
 async function addFiles(list,setId=active){if(simulating||disposed||!owner)return;const messages=[];for(const file of list){if(files.length>=uploadLimits.batchFiles){messages.push('每批最多 100 张');break;}if(!['image/png','image/jpeg','image/webp','image/gif'].includes(file.type)){messages.push(`${file.name}：格式不支持`);continue;}if(file.size>uploadLimits.fileBytes){messages.push(`${file.name}：超过 20 MB`);continue;}const item={id:crypto.randomUUID(),set:setId,file,url:URL.createObjectURL(file),state:'queued',progress:0};files.push(item);const image=new Image();image.src=item.url;try{await image.decode();item.width=image.naturalWidth;item.height=image.naturalHeight;}catch{item.decodeError=true;}render();preview(item);}status(messages.length?messages.join('；'):'图片已加入队列，尚未上传。');await persist();}
 root.addEventListener('change',event=>{if(!event.target.matches('[data-file-picker]'))return;const set=event.target.closest('[data-set]');void addFiles([...event.target.files],set.dataset.set);event.target.value='';});
 root.addEventListener('click',event=>{const old=event.target.closest('[data-set]');if(event.target.closest('[data-remove-set]')&&old&&!files.some(f=>f.set===old.dataset.set)&&sets().length>1){old.remove();if(active===old.dataset.set)active=sets()[0].dataset.set;index();changed();return;}const trigger=event.target.closest('[data-select-set]');if(trigger){active=trigger.dataset.selectSet;index();trigger.closest('[data-set]').querySelector('[data-file-picker]').click();}});
 root.addEventListener('input',event=>{if(event.target.matches('[data-character-filter]')){roleOptions(event.target.closest('[data-set]'),event.target.value);return;}if(event.target.matches('[name=title],[name=form]'))index();changed();});
 root.addEventListener('change',event=>{if(event.target.matches('[name=character]')){index();void formOptions(event.target.closest('[data-set]'));changed();}});
 root.addEventListener('dragover',event=>{const zone=event.target.closest('[data-drop-set]');if(zone){event.preventDefault();zone.dataset.dragging='';}});root.addEventListener('dragleave',event=>event.target.closest('[data-drop-set]')?.removeAttribute('data-dragging'));root.addEventListener('drop',event=>{const zone=event.target.closest('[data-drop-set]');if(!zone)return;event.preventDefault();zone.removeAttribute('data-dragging');active=zone.dataset.dropSet;void addFiles([...event.dataTransfer.files],active);});
 root.addEventListener('paste',event=>{const set=event.target.closest('[data-set]');if(!set)return;const images=[...event.clipboardData.files].filter(f=>f.type.startsWith('image/'));if(images.length){event.preventDefault();void addFiles(images,set.dataset.set);}});
 $('[data-add-set]').onclick=()=>{if(simulating||disposed)return;serial++;const node=template.cloneNode(true);node.dataset.set=`set-${serial}`;node.id=`creation-set-${serial}`;node.querySelector('.creation-caption').textContent=`${String(serial).padStart(2,'0')} / SET`;node.querySelector('h3').textContent=`第 ${serial} 套设定`;node.querySelector('[data-image-list]').replaceChildren();node.querySelectorAll('[name]').forEach(e=>{e.value='';e.id=`set-${serial}-${e.name}`;e.closest('label')?.setAttribute('for',e.id);});node.querySelector('[data-form-options]').id=`set-${serial}-forms`;node.querySelector('[name=form]').setAttribute('list',`set-${serial}-forms`);node.querySelectorAll('[data-select-set]').forEach(e=>e.dataset.selectSet=node.dataset.set);node.querySelector('[data-drop-set]').dataset.dropSet=node.dataset.set;$('[data-set-container]').append(node);roleOptions(node);active=node.dataset.set;index();changed();node.scrollIntoView({block:'start',behavior:matchMedia('(prefers-reduced-motion:reduce)').matches?'instant':'smooth'});};
 $('[data-preview-open]').onclick=()=>{const item=files.find(f=>f.id===selectedFile);if(!item)return;const group=files.filter(f=>f.set===item.set);imageViewer().open(group.map(f=>({src:f.url,title:f.title||f.file.name,notes:`${formatBytes(f.file.size)} · ${f.width} × ${f.height} px`})),group.indexOf(item),$('[data-preview-open]'));};
 async function uploadOne(item){
  if(item.state==='staged'||disposed)return;if(!(item.file instanceof Blob)){item.state='failed';item.error='本机文件未备份，请重新选择文件';progress(item);return;}
  item.error='';item.state='uploading';progress(item);const body=new FormData();body.set('image',item.file);body.set('metadata',JSON.stringify({name:item.file.name,width:item.width,height:item.height}));
  try{await uploadFile({url:api+'/api/gallery/uploads/'+batch.id+'/'+item.id+'?accountId='+encodeURIComponent(owner),body,signal:controller.signal,onProgress:p=>{item.state=p.phase;item.progress=p.percent;item.loaded=p.loaded;item.total=p.total;progress(item);$('[data-total-progress]').value=files.reduce((s,f)=>s+(f.progress||0),0)/files.length;}});item.state='staged';item.progress=100;await persist();}catch(error){item.state='failed';item.error=error.message;}progress(item);
 }
 $('[data-simulate-upload]').onclick=async()=>{if(simulating||disposed)return;if(queueState().issues.length){index();$('[data-upload-issues] button')?.click();return;}if(!sets().every(set=>[...set.querySelectorAll('input,textarea,select')].every(input=>input.reportValidity())))return;if(files.some(f=>f.decodeError)){status('请先移除无法读取的图片');return;}simulating=true;render();try{await persist();await saveRemote();const queue=files.filter(f=>f.state!=='staged');let next=0;await Promise.all(Array.from({length:Math.min(3,queue.length)},async()=>{while(next<queue.length&&!disposed)await uploadOne(queue[next++]);}));status(files.every(f=>f.state==='staged')?(admin?'所有文件已暂存。核对资料后点击「发布全部设定」。':'所有文件已暂存。检查资料后点击「提交全部设定审核」。'):'部分文件未完成，点击上传可重试失败文件；成功文件不会重复上传。');await quotaInfo();}catch(error){status(error.message);}finally{simulating=false;render();}};
 $('[data-submit-batch]').onclick=async()=>{if(simulating||disposed)return;simulating=true;index();try{await saveRemote();if(admin){await adminRequest('/batches/'+batch.id+'/publish',{version:batch.version});}else{try{await request('/batches/'+batch.id+'/submit',{version:batch.version});}catch(error){const probe=await request('/batches/'+batch.id).catch(()=>null);if(probe?.batch?.status!=='submitted')throw error;}}batch={...batch,status:'submitted'};await galleryDraft('delete',owner);dirty=false;status(admin?'设定已公开。':flowText.submitted);receipt(batch.id);disposed=true;}catch(error){status(error.message);}finally{simulating=false;index();}};
 async function quotaInfo(){
  const q=await request('/quota');
  $('[data-session-state]').textContent='可以上传';
  $('[data-quota-remaining]').textContent=String(q.remaining);
  $('[data-quota-limit]').textContent=String(q.limit);
  $('[data-session-concurrency]').textContent=String(q.concurrency);
  all('[data-session-stat]').forEach(item=>item.hidden=false);
  const expiry=$('[data-session-expiry]');expiry.hidden=!batch?.expires_at;
  if(batch?.expires_at){
   const raw=String(batch.expires_at),date=new Date(/[zZ]|[+-]\d\d:\d\d$/.test(raw)?raw:`${raw.replace(' ','T')}Z`);
   const value=$('[data-session-expiry-value]');value.textContent=Number.isNaN(date.getTime())?raw:new Intl.DateTimeFormat(locale==='ja'?'ja-JP':locale==='en'?'en-US':'zh-CN',{month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit'}).format(date);
   value.title=`${raw} UTC`;
  }
 }
 async function restore(draft,remote){hydrating=true;files.forEach(f=>URL.revokeObjectURL(f.url));files=[];$('[data-set-container]').replaceChildren();const data=draft&&(!remote||draft.version===remote.batch.version)?draft.manifest:remote?.batch.manifest;if(!data?.sets?.length){$('[data-set-container]').append(template.cloneNode(true));hydrating=false;return;}
  for(const [i,set]of data.sets.entries()){const node=template.cloneNode(true);node.dataset.set=set.id;node.dataset.existing=set.setId||'';node.dataset.version=set.baseVersion||0;node.id='creation-'+set.id;node.querySelector('h3').textContent=`第 ${i+1} 套设定`;roleOptions(node);node.querySelectorAll('[name]').forEach(input=>{input.value=Array.isArray(set.metadata[input.name])?set.metadata[input.name].join(', '):set.metadata[input.name]||'';input.id=set.id+'-'+input.name;input.closest('label').htmlFor=input.id;});node.querySelector('[data-form-options]').id=set.id+'-forms';node.querySelector('[name=form]').setAttribute('list',set.id+'-forms');node.querySelectorAll('[data-select-set]').forEach(e=>e.dataset.selectSet=set.id);node.querySelector('[data-drop-set]').dataset.dropSet=set.id;node.querySelector('[data-image-list]').replaceChildren();$('[data-set-container]').append(node);void formOptions(node);
   for(const image of set.images){const local=draft?.files.find(f=>f.id===image.fileId),server=remote?.files.find(f=>f.id===image.fileId),file=local?.file||local?.fileInfo||{name:server?.name||'需要重新选择文件',size:server?.size||0,type:server?.mime_type||'image/png'},item={...local,...image.metadata,id:image.fileId,set:set.id,file,width:server?.width||local?.width,height:server?.height||local?.height,state:server?.state==='staged'?'staged':'queued',progress:server?.state==='staged'?100:0};item.url=file instanceof Blob?URL.createObjectURL(file):server?.previewUrl||'';if(!(file instanceof Blob)&&item.state!=='staged')item.error='文件未备份，请重新选择';files.push(item);}
  }serial=Math.max(data.sets.length,...data.sets.map(s=>Number(s.id.replace('set-',''))||0));active=data.sets[0].id;render();if(files.length)preview(files[0]);hydrating=false;
 }
 async function initialize(){try{const viewer=await refreshAuth();owner=viewer?.userId;if(!owner){status('登录后可以恢复或新建上传批次。');const a=text('a','登录后继续');a.href=`/${locale}/account/?returnTo=`+encodeURIComponent(location.href);$('[data-session-state]').replaceChildren(a);index();return;}if(admin)await adminRequest('/catalog?offset=0');
  characters=(await request('/characters')).characters;roleOptions(template);sets().forEach(set=>roleOptions(set));
  const params=new URLSearchParams(location.search);let draft;try{draft=await galleryDraft('get',owner);}catch{status('本机存储不可用，请在上传成功前保留当前页面。');}
  let id=params.get('batch');let setId=params.get('set');const revision=params.get('revision');if(params.get('edit'))setId=(await request('/items/'+encodeURIComponent(params.get('edit')))).item.setId;if(setId||revision){const path=`/${setId?'sets/'+encodeURIComponent(setId)+'/edit-batch':'set-revisions/'+encodeURIComponent(revision)+'/resubmit'}`;batch=(await (admin?adminRequest(path,{id:crypto.randomUUID()}):request(path,{id:crypto.randomUUID()}))).batch;id=batch.id;history.replaceState(null,'',batchUrl(id));draft=null;}
  id=id||draft?.id;if(id){const remote=await request('/batches/'+encodeURIComponent(id));batch=remote.batch;if(batch.status==='submitted'){status(admin?'设定已公开。':flowText.submitted);receipt(batch.id);disposed=true;index();return;}if(batch.status!=='draft')throw Error('此批次已取消或过期，请在创作者中心查看记录。');await restore(draft?.id===id?draft:null,remote);history.replaceState(null,'',batchUrl(id));}else if(draft)await restore(draft,null);
  await quotaInfo();index();}catch(error){status(error.message);$('[data-session-state]').textContent='上传暂不可用';}}
 window.addEventListener('beforeunload',event=>{if(dirty||simulating){event.preventDefault();event.returnValue='';}});
 window.addEventListener('kamitsubaki-account-state',()=>{if(owner&&state.viewer?.userId!==owner){disposed=true;controller.abort();imageViewer().close();files.forEach(f=>URL.revokeObjectURL(f.url));files=[];root.querySelectorAll('input,textarea').forEach(e=>e.value='');all('[data-image-list]').forEach(e=>e.replaceChildren());$('[data-preview-image]').hidden=true;status('账号已变化，请刷新页面后继续。上一账号的资料已隐藏。');index();}});
 index();void initialize();
}
