import {uploadFile,uploadLimits,formatBytes} from '../lib/uploadPresentation.mjs';
import {galleryDraft} from '../lib/galleryDraftStore.mjs';
import {refreshAuth,state} from './accountStore.js';

const root=document.querySelector('[data-photo-workbench]');
if(root){
 const $=selector=>root.querySelector(selector),api=root.dataset.api.replace(/\/$/,''),copy=JSON.parse(root.dataset.copy||'{}'),locale=root.dataset.locale;
 const create=(tag,value='')=>{const node=document.createElement(tag);node.textContent=value;return node;};
 let owner=null,batch=null,files=[],busy=false,busyAction='',entities=[],mediaTypes=[],disposed=false;
 const draftKey=()=>`photos:${owner}`;
 const say=(value,tone='info')=>{const status=$('[data-photo-status]');status.textContent=value;status.dataset.tone=tone;};
 const request=async(path,method='GET',body)=>{const url=new URL(api+'/api/gallery'+path);if(owner)url.searchParams.set('accountId',owner);const response=await fetch(url,{method,credentials:'include',headers:body?{'Content-Type':'application/json'}:{},body:body?JSON.stringify(body):undefined,signal:AbortSignal.timeout(20000)});const data=await response.json();if(!response.ok)throw Error(data.error?.message||copy.failed);return data;};
 const defaults=()=>{const fields=Object.fromEntries([...root.querySelectorAll('[data-default]')].map(input=>[input.dataset.default,input.value.trim()]));return {...fields,mediaType:fields.mediaType||null,tags:fields.tags.split(/[,，]/).map(value=>value.trim()).filter(Boolean),entityIds:[...root.querySelectorAll('[data-entity-options] input:checked')].map(input=>input.value)};};
 const manifest=()=>({kind:'photos',defaults:defaults(),photos:files.map(file=>({fileId:file.id,metadata:Object.fromEntries(Object.entries(file.metadata).filter(([,value])=>value!==''&&value!==undefined))}))});
 function fieldsFromManifest(data){for(const [key,value] of Object.entries(data.defaults||{})){const input=root.querySelector(`[data-default="${key}"]`);if(input)input.value=Array.isArray(value)?value.join(', '):value||'';}root.querySelectorAll('[data-entity-options] input').forEach(input=>{input.checked=(data.defaults?.entityIds||[]).includes(input.value);});toggleEvidence();}
 async function saveLocal(){if(!owner||disposed)return;try{await galleryDraft('put',draftKey(),{id:batch?.id,version:batch?.version,manifest:manifest(),files:files.map(({url,...file})=>file)});}catch{say(copy.localStorageFull,'error');}}
 async function saveRemote(){if(!batch){batch=(await request('/batches','POST',{id:crypto.randomUUID(),kind:'photos'})).batch;const url=new URL(location.href);url.searchParams.set('batch',batch.id);history.replaceState(null,'',url);}const result=await request('/batches/'+encodeURIComponent(batch.id),'PUT',{version:batch.version,manifest:manifest()});batch=result.batch;await saveLocal();}
 function updateButtons(){const can=Boolean(owner&&!busy&&!disposed);for(const key of ['save','stage','submit']){const button=$(`[data-photo-${key}]`);button.disabled=!can;button.dataset.busy=String(busyAction===key);button.textContent=busyAction===key?copy[{save:'saving',stage:'staging',submit:'submitting'}[key]]:copy[key];}$('[data-photo-count]').textContent=`${files.length} ${copy.photos} · ${files.filter(file=>file.state==='staged').length} ${copy.staged}`;}
 const begin=action=>{busy=true;busyAction=action;updateButtons();say(copy[{save:'saving',stage:'staging',submit:'submitting'}[action]],'progress');};
 const end=()=>{busy=false;busyAction='';updateButtons();};
 function showSuccess(){const dialog=$('[data-photo-success]');$('[data-photo-success-link]').href=$('[data-photo-receipt]').href;if(typeof dialog.showModal==='function')dialog.showModal();else dialog.setAttribute('open','');$('[data-photo-success-link]').focus();}
 function rowField(label,key,file,type='text'){const wrapper=create('label',label),input=document.createElement('input');input.type=type;input.value=Array.isArray(file.metadata[key])?file.metadata[key].join(', '):file.metadata[key]||'';input.maxLength=key==='sourceUrl'?2000:key==='tags'?1000:200;input.placeholder=key==='title'?'':copy.inherit;input.oninput=()=>{const value=input.value.trim();if(value)file.metadata[key]=key==='tags'?value.split(/[,，]/).map(tag=>tag.trim()).filter(Boolean):value;else delete file.metadata[key];void saveLocal();};wrapper.append(input);return wrapper;}
 function rowSelect(label,key,file,options){const wrapper=create('label',label),select=document.createElement('select');for(const [value,text] of options)select.add(new Option(text,value));select.value=key==='mediaType'&&file.metadata[key]===null?'__none__':file.metadata[key]||'';select.onchange=()=>{if(select.value==='')delete file.metadata[key];else file.metadata[key]=select.value==='__none__'?null:select.value;void saveLocal();};wrapper.append(select);return wrapper;}
 function rowEntities(file){const section=create('div'),toggle=document.createElement('label'),checkbox=document.createElement('input'),options=create('div');section.className='gallery-photo-row__entities';toggle.className='gallery-photo-row__entity-toggle';checkbox.type='checkbox';checkbox.checked=Object.hasOwn(file.metadata,'entityIds');toggle.append(checkbox,create('span',copy.differentEntities));options.className='gallery-photo-row__entity-options';options.hidden=!checkbox.checked;for(const entity of entities){const label=document.createElement('label'),input=document.createElement('input');input.type='checkbox';input.value=entity.id;input.checked=file.metadata.entityIds?.includes(entity.id)||false;input.onchange=()=>{file.metadata.entityIds=[...options.querySelectorAll('input:checked')].map(item=>item.value);void saveLocal();};label.append(input,create('span',entity.labels?.[locale]||entity.name));options.append(label);}checkbox.onchange=()=>{if(checkbox.checked){file.metadata.entityIds=defaults().entityIds;options.querySelectorAll('input').forEach(input=>{input.checked=file.metadata.entityIds.includes(input.value);});}else delete file.metadata.entityIds;options.hidden=!checkbox.checked;void saveLocal();};section.append(toggle,options);return section;}
 function render(){const list=$('[data-photo-list]');list.replaceChildren();if(!files.length)list.append(create('p',copy.empty));for(const file of files){const row=create('div');row.className='gallery-photo-row';const image=new Image();image.src=file.url||'';image.alt=file.metadata.title||file.name||'';image.loading='lazy';const body=create('div');body.className='gallery-photo-row__body';const top=create('div');top.className='gallery-photo-row__top';const title=create('strong',file.name||file.file?.name||'Photo'),remove=create('button',copy.remove);remove.type='button';remove.disabled=busy;remove.onclick=()=>{if(file.url?.startsWith('blob:'))URL.revokeObjectURL(file.url);files=files.filter(item=>item!==file);render();void saveLocal();};top.append(title,remove);const detail=create('small',`${formatBytes(file.file?.size||file.size||0)} · ${file.state==='staged'?copy.staged:file.state==='failed'?copy.failed:copy.queued}${file.error?' · '+file.error:''}`);const extra=create('details'),summary=create('summary',copy.override),fields=create('div');fields.className='gallery-photo-row__fields';for(const [label,key,type] of [[copy.photoTitle,'title','text'],[copy.author,'author','text'],[copy.sourceTitle,'sourceTitle','text'],[copy.sourceUrl,'sourceUrl','url'],[copy.evidence,'rightsEvidence','text'],[copy.tags,'tags','text']])fields.append(rowField(label,key,file,type));fields.append(rowSelect(copy.basis,'rightsBasis',file,[['',copy.inherit],['official',copy.official],['original',copy.original],['authorized',copy.authorized]]),rowSelect(copy.type,'mediaType',file,[['',copy.inherit],['__none__',copy.noType],...mediaTypes.map(type=>[type.id,type.labels?.[locale]||type.labels?.zh||type.id])]));extra.append(summary,fields,rowEntities(file));body.append(top,detail);if(file.reviewNote){const note=create('p',`${copy.reviewReason}：${file.reviewNote}`);note.className='gallery-photo-row__review-note';body.append(note);}body.append(extra);row.append(image,body);list.append(row);}updateButtons();}
 function toggleEvidence(){const authorized=$('[data-default="rightsBasis"]').value==='authorized';$('[data-evidence-field]').hidden=!authorized;}
 async function addFiles(input){const errors=[];for(const file of input){if(files.length>=uploadLimits.batchFiles){errors.push(copy.tooMany);break;}if(!['image/png','image/jpeg','image/webp','image/gif'].includes(file.type)||file.size>uploadLimits.fileBytes){errors.push(`${file.name}：${copy.invalidFile}`);continue;}const duplicate=files.some(row=>row.name===file.name&&row.size===file.size);if(duplicate){errors.push(`${file.name}：${copy.duplicateFile}`);continue;}files.push({id:crypto.randomUUID(),file,name:file.name,size:file.size,url:URL.createObjectURL(file),metadata:{},state:'queued'});}render();say(errors.length?errors.join('；'):copy.queued,errors.length?'error':'info');await saveLocal();}
 $('[data-photo-files]').onchange=event=>{void addFiles([...event.target.files]);event.target.value='';};
 const drop=$('[data-photo-drop]');drop.ondragover=event=>{event.preventDefault();drop.dataset.dragging='';};drop.ondragleave=()=>delete drop.dataset.dragging;drop.ondrop=event=>{event.preventDefault();delete drop.dataset.dragging;void addFiles([...event.dataTransfer.files]);};
 root.querySelectorAll('[data-default]').forEach(input=>input.addEventListener('input',()=>{if(input.dataset.default==='rightsBasis')toggleEvidence();void saveLocal();}));
 $('[data-entity-search]').oninput=event=>{const q=event.target.value.trim().toLocaleLowerCase();root.querySelectorAll('[data-entity-options] label').forEach(label=>{label.hidden=Boolean(q&&!label.textContent.toLocaleLowerCase().includes(q));});};
 $('[data-entity-options]').onchange=()=>void saveLocal();
 async function stageOne(file){if(file.state==='staged')return;if(!(file.file instanceof Blob)){file.state='failed';file.error=copy.reselectFile;render();return;}const data=new FormData();let width=0,height=0;try{const bitmap=await createImageBitmap(file.file);width=bitmap.width;height=bitmap.height;bitmap.close();}catch{}data.set('metadata',JSON.stringify({name:file.name,width,height}));data.set('image',file.file);try{await uploadFile({url:api+'/api/gallery/uploads/'+encodeURIComponent(batch.id)+'/'+encodeURIComponent(file.id)+'?accountId='+encodeURIComponent(owner),body:data,onProgress:progress=>{file.progress=progress.percent;const line=[...root.querySelectorAll('.gallery-photo-row')][files.indexOf(file)]?.querySelector('small');if(line)line.textContent=`${file.name} · ${progress.percent??'…'}%`;}});file.state='staged';file.error='';}catch(error){file.state='failed';file.error=error.message;}render();await saveLocal();}
 $('[data-photo-save]').onclick=async()=>{if(busy)return;if(!files.length){say(copy.chooseFirst,'error');return;}begin('save');try{await saveRemote();say(copy.save+' ✓','success');}catch(error){say(error.message,'error');}finally{end();}};
 $('[data-photo-stage]').onclick=async()=>{if(busy)return;if(!files.length){say(copy.chooseFirst,'error');return;}begin('stage');try{await saveRemote();const queue=files.filter(file=>file.state!=='staged');let next=0;await Promise.all(Array.from({length:Math.min(3,queue.length)},async()=>{while(next<queue.length)await stageOne(queue[next++]);}));say(files.every(file=>file.state==='staged')?`${copy.staged} · ${copy.submit}`:copy.failed,files.every(file=>file.state==='staged')?'success':'error');}catch(error){say(error.message,'error');}finally{end();}};
 $('[data-photo-submit]').onclick=async()=>{if(busy)return;if(!files.length){say(copy.chooseFirst,'error');return;}if(files.some(file=>file.state!=='staged')){say(copy.stageFirst,'error');$('[data-photo-stage]').focus();return;}begin('submit');try{await saveRemote();await request('/batches/'+encodeURIComponent(batch.id)+'/submit','POST',{version:batch.version});try{await galleryDraft('delete',draftKey());}catch{}disposed=true;say(copy.review,'success');$('[data-photo-receipt]').href=`/${locale}/account/creator/?recordType=gallery&record=${encodeURIComponent(batch.id)}`;$('[data-photo-receipt]').hidden=false;showSuccess();}catch(error){say(error.message,'error');}finally{end();}};
 $('[data-photo-success-close]').onclick=()=>{const dialog=$('[data-photo-success]');if(typeof dialog.close==='function')dialog.close();else dialog.removeAttribute('open');};
 async function initialize(){try{const viewer=await refreshAuth();owner=viewer?.userId;if(!owner){$('[data-photo-login]').href=`/${locale}/account/?returnTo=${encodeURIComponent(location.href)}`;$('[data-photo-login]').hidden=false;updateButtons();return;}const [catalog,types]=await Promise.all([request('/entities'),request('/types')]);entities=catalog.entities;mediaTypes=types.types;for(const type of mediaTypes){const option=new Option(type.labels?.[locale]||type.labels?.zh||type.id,type.id);$('[data-default="mediaType"]').add(option);}const options=$('[data-entity-options]');for(const entity of entities){const label=create('label'),checkbox=document.createElement('input');checkbox.type='checkbox';checkbox.value=entity.id;label.append(checkbox,create('span',entity.labels?.[locale]||entity.name));options.append(label);}const local=await galleryDraft('get',draftKey()).catch(()=>null),search=new URLSearchParams(location.search),retry=search.get('retry');let id=search.get('batch')||(!retry&&local?.id);let remote=null;if(retry&&!id){let retryDraft=search.get('retryDraft');if(!retryDraft||!/^[-\w]{1,100}$/.test(retryDraft)){retryDraft=crypto.randomUUID();const url=new URL(location.href);url.searchParams.set('retryDraft',retryDraft);history.replaceState(null,'',url);}const resumed=await request('/batches/'+encodeURIComponent(retry)+'/retry','POST',{id:retryDraft});id=resumed.batch.id;const url=new URL(location.href);url.searchParams.delete('retry');url.searchParams.delete('retryDraft');url.searchParams.set('batch',id);history.replaceState(null,'',url);}if(id){remote=await request('/batches/'+encodeURIComponent(id));batch=remote.batch;if(batch.kind!=='photos')throw Error(copy.wrongBatch);if(batch.status!=='draft'){say(copy.review);$('[data-photo-receipt]').href=`/${locale}/account/creator/?recordType=gallery&record=${encodeURIComponent(batch.id)}`;$('[data-photo-receipt]').hidden=false;disposed=true;updateButtons();return;}}const data=local&&(!remote||local.id===remote.batch.id&&local.version===remote.batch.version)?local.manifest:remote?.batch.manifest;if(data){fieldsFromManifest(data);files=(data.photos||[]).map(photo=>{const saved=local?.files.find(file=>file.id===photo.fileId),server=remote?.files.find(file=>file.id===photo.fileId),file=saved?.file;return {id:photo.fileId,metadata:photo.metadata||{},file,name:saved?.name||server?.name||'Photo',size:saved?.size||server?.size||0,url:file instanceof Blob?URL.createObjectURL(file):server?.previewUrl||'',state:server?.state==='staged'?'staged':'queued',reviewNote:server?.previousReviewNote||''};});}render();say(retry?copy.retryReady:copy.readyStatus);}catch(error){say(error.message,'error');}updateButtons();}
 window.addEventListener('kamitsubaki-account-state',()=>{if(owner&&state.viewer?.userId!==owner){disposed=true;files.forEach(file=>{if(file.url?.startsWith('blob:'))URL.revokeObjectURL(file.url);});files=[];render();say(copy.accountChanged,'error');}});
 updateButtons();void initialize();
}
