import {refreshAuth} from './accountStore.js';
import {readableGalleryPhotoName} from '../lib/galleryPhotoName.mjs';

const root=document.querySelector('[data-gallery-classify]');
if(root){
 const $=selector=>root.querySelector(selector),api=root.dataset.api.replace(/\/$/,''),copy=JSON.parse(root.dataset.copy||'{}'),locale=root.dataset.locale;
 const params=new URLSearchParams(location.search),ids=[...new Set((params.get('ids')||params.get('photo')||'').split(',').map(value=>value.trim()).filter(Boolean))].slice(0,50);
 let owner=null,photos=[],sets=new Map(),entityNames=new Map(),typeNames=new Map(),busy=false,searchTimer;
 const node=(tag,value='')=>{const element=document.createElement(tag);element.textContent=value;return element;};
 const say=value=>{$('[data-classify-status]').textContent=value;};
 const request=async(path,method='GET',body)=>{const response=await fetch(api+'/api/gallery'+path,{method,credentials:'include',headers:body?{'Content-Type':'application/json'}:{},body:body?JSON.stringify(body):undefined,signal:AbortSignal.timeout(20000)});const data=await response.json();if(!response.ok)throw Error(data.error?.message||'请求未完成');return data;};
 function renderPhotos(){const area=$('[data-classify-photos]');area.replaceChildren();for(const photo of photos){const card=node('article'),image=new Image(),info=node('div'),subjects=(photo.entityIds?.length?photo.entityIds:[photo.character]).filter(Boolean).map(id=>entityNames.get(id)||id).join(' / '),type=typeNames.get(photo.mediaType)||'',title=readableGalleryPhotoName(photo)||photo.setTitle||[subjects,type].filter(Boolean).join(' · ')||copy.unknownPhoto;image.src=photo.thumbnail||photo.src;image.alt='';image.loading='lazy';info.append(node('strong',title),node('small',photo.sourceTitle||photo.setSourceTitle||copy.source));card.append(image,info);area.append(card);}if(!photos.length)area.append(node('p',copy.empty));}
 function showEntities(entities){const target=$('[data-classify-entities]');target.replaceChildren();for(const entity of entities){const label=node('label'),input=document.createElement('input');input.type='checkbox';input.value=entity.id;if(photos.length===1)input.checked=photos[0].entityIds?.includes(entity.id)||false;label.append(input,node('span',entity.labels?.[locale]||entity.name));target.append(label);}}
 async function searchSets(query=''){const search=new URLSearchParams({summary:'1',q:query});const data=await request('/sets?'+search);sets=new Map();const list=$('[data-classify-set-list]');list.replaceChildren();for(const set of data.sets){const label=`${set.title||set.character||set.id} · ${set.id}`,option=document.createElement('option');option.value=label;list.append(option);sets.set(label,set);}}
 $('[data-classify-set]').oninput=event=>{clearTimeout(searchTimer);searchTimer=setTimeout(()=>void searchSets(event.target.value).catch(error=>say(error.message)),250);};
 $('[data-classify-entity-search]').oninput=event=>{const value=event.target.value.trim().toLocaleLowerCase();root.querySelectorAll('[data-classify-entities] label').forEach(label=>{label.hidden=Boolean(value&&!label.textContent.toLocaleLowerCase().includes(value));});};
 $('[data-classify-form]').onsubmit=async event=>{event.preventDefault();if(busy||!owner||!photos.length)return;busy=true;const submit=$('[data-classify-form] button[type="submit"]');submit.disabled=true;try{
  const selected=[...root.querySelectorAll('[data-classify-entities] input:checked')].map(input=>input.value),typed=$('[data-classify-tags]').value.split(/[,，]/).map(value=>value.trim()).filter(Boolean),type=$('[data-classify-type]').value;
  const setValue=$('[data-classify-set]').value.trim(),set=setValue?sets.get(setValue):null;if(setValue&&!set)throw Error('请从搜索结果选择一个设定组');
  const items=photos.map(photo=>{const multiple=photos.length>1;const patch={mediaType:type==='__keep__'?photo.mediaType||null:type||null,entityIds:multiple?[...new Set([...(photo.entityIds||[]),...selected])]:selected,tags:multiple?[...new Set([...(photo.tags||[]),...typed])]:typed};if(set){patch.setId=set.id;patch.setBaseVersion=set.version;}return {itemId:photo.id,baseVersion:photo.version,patch};});
  const result=await request('/proposals','POST',{id:crypto.randomUUID(),items});say(copy.review);$('[data-classify-receipt]').href=`/${locale}/account/creator/?recordType=gallery&record=${encodeURIComponent(result.batchId)}`;$('[data-classify-receipt]').hidden=false;
 }catch(error){say(error.message);}finally{busy=false;submit.disabled=false;}};
 async function initialize(){if(!ids.length){renderPhotos();say(copy.empty);return;}try{const [viewer,catalog,types,...items]=await Promise.all([refreshAuth(),request('/entities'),request('/types'),...ids.map(id=>request('/items/'+encodeURIComponent(id)))]);owner=viewer?.userId;photos=items.map(result=>result.item);entityNames=new Map((catalog.entities||[]).map(entity=>[entity.id,entity.labels?.[locale]||entity.labels?.zh||entity.name||entity.id]));typeNames=new Map((types.types||[]).map(type=>[type.id,type.labels?.[locale]||type.labels?.zh||type.id]));renderPhotos();showEntities(catalog.entities);for(const type of types.types)$('[data-classify-type]').add(new Option(type.labels?.[locale]||type.labels?.zh||type.id,type.id));if(photos.length===1){$('[data-classify-type]').value=photos[0].mediaType||'';$('[data-classify-tags]').value=(photos[0].tags||[]).join(', ');}await searchSets();say('');if(!owner){$('[data-classify-form] button[type="submit"]').disabled=true;$('[data-classify-login]').href=`/${locale}/account/?returnTo=${encodeURIComponent(location.href)}`;$('[data-classify-login]').hidden=false;}}catch(error){renderPhotos();say(error.message);}}
 const returnTo=params.get('returnTo');if(returnTo){try{const target=new URL(returnTo,location.origin);if(target.origin===location.origin&&target.pathname.startsWith(`/${locale}/gallery/`)){const back=root.querySelector('.workspace-back');if(back)back.href=target.pathname+target.search+target.hash;}}catch{}}
 void initialize();
}
