import {GALLERY_PUBLIC_ORIGIN} from '../src/lib/galleryConfig.mjs';
import {readFile,access,writeFile,mkdir} from 'node:fs/promises';import {z} from 'astro/zod';
import {getEntityRegistry} from '../src/lib/entityRegistry.mjs';import {createEntitySchema} from '../src/lib/entitySchema.mjs';import {entityEdges,stableIdPattern} from '../src/lib/entityModel.mjs';import {loadFeatureData,loadTaxonomy} from '../src/lib/featureData.mjs';import {hash,parseDocument} from './v3/io.mjs';
const r=await getEntityRegistry(),schema=createEntitySchema(z),errors=[],warnings=[];const check=(ok,message)=>{if(!ok)errors.push(message);};
const dictionaries=Object.fromEntries(await Promise.all(['genres','roles','tracks','event-types','gallery-tags','forms'].map(async name=>[name,new Set((await loadTaxonomy(name)).values)])));
for(const [id,group]of r.entities){check(group.has('zh'),`${id}: missing zh source`);for(const [locale,e]of group){const parsed=schema.safeParse(e.data);if(!parsed.success)for(const issue of parsed.error.issues)errors.push(`${id}/${locale}: ${issue.path.join('.')} ${issue.message}`);for(const role of e.data.roles||[])check(dictionaries.roles.has(role),`${id}: unknown role ${role}`);for(const genre of e.data.genres||[])check(dictionaries.genres.has(genre),`${id}: unknown genre ${genre}`);for(const edge of entityEdges(e.data))check(r.entities.has(edge.target),`${id}: missing target ${edge.target}`);
 for(const match of e.body.matchAll(/\[\[([a-z0-9-]+)(?:\|[^\]]+)?\]\]/g))check(r.entities.has(match[1]),`${id}: broken WikiLink ${match[1]}`);
 }
}
function validDate(date){if(!/^\d{4}(?:-\d{2}(?:-\d{2})?)?$/.test(date||''))return false;const [year,month=1,day=1]=date.split('-').map(Number);const d=new Date(Date.UTC(year,month-1,day));return d.getUTCFullYear()===year&&d.getUTCMonth()===month-1&&d.getUTCDate()===day;}
const data=await loadFeatureData(),ids=new Set(r.entities.keys());
for(const e of data.events){check(stableIdPattern.test(e.id)&&!ids.has(e.id),'Duplicate/invalid event ID '+e.id);ids.add(e.id);check(validDate(e.date.start),'Invalid date '+e.id);check(({day:10,month:7,year:4})[e.date.precision]===e.date.start.length,'Date precision mismatch '+e.id);if(e.date.end)check(validDate(e.date.end)&&e.date.end>=e.date.start,'Invalid date interval '+e.id);check(!!e.text.zh?.title&&!!e.text.zh?.summary,'Missing Chinese event text '+e.id);for(const locale of ['ja','en'])if(!e.text[locale])warnings.push(`${e.id}: pending ${locale} translation`);for(const t of e.tracks)check(dictionaries.tracks.has(t),'Unknown track '+t);for(const t of e.eventTypes)check(dictionaries['event-types'].has(t),'Unknown event type '+t);for(const ref of e.related||[])check(r.entities.has(ref.entity),'Missing event entity '+ref.entity);for(const id of e.articles||[])check(r.resolveEntity(id)?.data.entityType==='editorial-article','Invalid article reference '+id);if(e.importance!=='regular')check(e.sources?.some(s=>s.url||s.title&&s.page),'Major event lacks source '+e.id);}
const sourceTypes=new Set(['official-site','official-artbook','official-x','art-exhibition','product-packaging','game-client-extract','bd-bonus-booklet']);
for(const item of data.gallery){check(stableIdPattern.test(item.id)&&!ids.has(item.id),'Duplicate gallery ID '+item.id);ids.add(item.id);check(r.entities.has(item.subject),'Invalid gallery subject '+item.subject);for(const id of item.characters||[])check(r.entities.has(id),'Invalid gallery character '+id);if(item.characters?.length)check(!!item.form,'Character art requires form '+item.id);if(item.form)check(dictionaries.forms.has(item.form),'Unknown gallery form '+item.form);for(const tag of item.tags)check(dictionaries['gallery-tags'].has(tag),'Unknown gallery tag '+tag);check(!!item.uploader&&validDate(item.uploadedAt),'Missing gallery collector '+item.id);check(sourceTypes.has(item.source?.type)&&!!(item.source.url||item.source.title&&item.source.page),'Missing gallery provenance '+item.id);const src=item.image?.src;check(!!src,'Missing image '+item.id);if(src?.startsWith('/')&&!src.startsWith('//'))try{await access('public'+src);}catch{errors.push('Missing local image '+src);}else if(src&&!/^https:\/\//.test(src)&&(!(process.env.PUBLIC_GALLERY_R2_URL||GALLERY_PUBLIC_ORIGIN)))warnings.push('R2 public base is not configured: '+item.id);}
// Content enrichment is append-only: verify each original body is still a prefix.
const relocation=JSON.parse(await readFile('docs/v3/reports/content-layout.json','utf8').catch(()=>'{"moves":[]}'));const moved=new Map(relocation.moves.map(m=>[m.from,m.to]));const currentPath=path=>{const seen=new Set();while(moved.has(path)&&!seen.has(path)){seen.add(path);path=moved.get(path);}return path;};
let preserved=0;try{const report=JSON.parse(await readFile('docs/v3/reports/migration-report.json','utf8'));for(const item of report.files){const current=parseDocument(await readFile(currentPath(item.path),'utf8')).body;const marker=current.indexOf('\n\n<!-- V3 RESEARCH SUPPLEMENT');const original=marker>=0?current.slice(0,marker):current;check(hash(original)===item.bodyHash,'Original body changed '+item.path);preserved++;}}catch(e){errors.push('Migration audit unavailable: '+e.message);}
await mkdir('docs/v3/reports',{recursive:true});await writeFile('docs/v3/reports/validation.json',JSON.stringify({entities:r.entities.size,events:data.events.length,gallery:data.gallery.length,preserved,errors,warnings},null,2));console.log(JSON.stringify({entities:r.entities.size,events:data.events.length,gallery:data.gallery.length,preserved,errors:errors.length,warnings:warnings.length},null,2));for(const e of errors.slice(0,30))console.error(e);process.exitCode=errors.length?1:0;
